"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CIVILIAN_WATERCRAFT = void 0;
const shared_1 = require("./shared");
const water = (speed, combatSpeed, modeFuel) => (0, shared_1.movementMode)("water", "Waterborne", "water", { travelSpeed: speed, combatSpeed, fuel: modeFuel });
exports.CIVILIAN_WATERCRAFT = [
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:kayak-one-man",
        name: "One-Man Kayak",
        barterValue: "GG60",
        streetPrice: 1200,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "kayak"],
        description: "A covered one-person craft meant for rough-water paddling.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1 },
            cargoKg: 35,
            weightKg: 35,
            maintenanceHours: 1,
            movementModes: [(0, shared_1.movementMode)("paddle", "Paddle", "water", { travelSpeed: 3, combatSpeed: 8, traits: ["vehicle:human-powered"] })],
            traits: ["vehicle:soft-skinned", "vehicle:encumbrance-sensitive"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:kayak-two-man",
        name: "Two-Man Kayak",
        barterValue: "GG100",
        streetPrice: 2000,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "kayak"],
        description: "A two-person rough-water kayak including one double-bladed paddle per occupant.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1, passengers: 1 },
            cargoKg: 100,
            weightKg: 45,
            maintenanceHours: 1,
            movementModes: [(0, shared_1.movementMode)("paddle", "Paddle", "water", { travelSpeed: 3, combatSpeed: 8, traits: ["vehicle:human-powered"] })],
            traits: ["vehicle:soft-skinned", "vehicle:encumbrance-sensitive"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:canoe",
        name: "Canoe",
        barterValue: "GG50",
        streetPrice: 1000,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "canoe"],
        description: "An open-topped fiberglass canoe for calm-water paddling.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1, passengers: 1 },
            cargoKg: 100,
            weightKg: 50,
            maintenanceHours: 1,
            movementModes: [(0, shared_1.movementMode)("paddle", "Paddle", "water", { travelSpeed: 3, combatSpeed: 8, traits: ["vehicle:human-powered"] })],
            traits: ["vehicle:soft-skinned", "vehicle:encumbrance-sensitive"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:personal-watercraft",
        name: "Personal Watercraft",
        barterValue: "GG750",
        streetPrice: 12000,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "personal-watercraft"],
        description: "A noisy jet-driven personal craft with a dead-man switch.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1, passengers: 1 },
            cargoKg: 50,
            weightKg: 250,
            maintenanceHours: 2,
            movementModes: [water(25, 70, (0, shared_1.fuel)(["G"], 30, 5))],
            traits: ["vehicle:soft-skinned", "vehicle:encumbrance-sensitive", "vehicle:dead-man-switch"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:motorboat",
        name: "Motorboat",
        barterValue: "GG5,000",
        streetPrice: 20000,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "motorboat"],
        description: "A small motorized boat covering everything from bass boats to RHIBs.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1, passengers: 3 },
            cargoKg: 200,
            weightKg: 1200,
            maintenanceHours: 3,
            movementModes: [water(20, 56, (0, shared_1.fuel)(["G"], 450, 20))],
            armor: { Hull: { rating: 1 }, Waterline: { rating: 1 } },
            systems: {
                comm: "Vehicular shortwave radio on some civilian models.",
                sensors: "Mapping GPS and navigational radar on some civilian models.",
            },
            traits: ["vehicle:soft-skinned"],
            notes: ["Electronics-upgraded examples cost GG11,250 / $45,000."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:speedboat",
        name: "Speedboat",
        barterValue: "GG24,000",
        streetPrice: 120000,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "speedboat"],
        description: "A high-powered craft associated with racing, smuggling, and other impractical pursuits.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1, passengers: 3 },
            cargoKg: 200,
            weightKg: 4500,
            maintenanceHours: 6,
            movementModes: [water(60, 167, (0, shared_1.fuel)(["G"], 820, 100))],
            armor: { Hull: { rating: 1 }, Waterline: { rating: 1 } },
            systems: {
                comm: "Vehicular shortwave radio.",
                sensors: "Civilian mapping GPS; navigational radar.",
            },
            traits: ["vehicle:soft-skinned"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:day-sailer",
        name: "Day Sailer",
        barterValue: "GG5,000",
        streetPrice: 20000,
        sourcePages: [293],
        tags: ["civilian", "watercraft", "sailboat"],
        description: "A six-meter recreational sailboat meant for daytime use on calm water.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 1, passengers: 2 },
            cargoKg: 200,
            weightKg: 260,
            maintenanceHours: 2,
            movementModes: [(0, shared_1.movementMode)("sail", "Sail", "sail", { travelSpeed: 5, combatSpeed: 14, traits: ["vehicle:wind-limited"] })],
            armor: { Hull: { rating: 0 }, Waterline: { rating: 1 } },
            systems: {
                comm: "Vehicular shortwave radio on some civilian models.",
                sensors: "Mapping GPS and navigational radar on some civilian models.",
            },
            traits: ["vehicle:soft-skinned", "vehicle:encumbrance-sensitive"],
            notes: ["Electronics-upgraded examples cost GG11,250 / $45,000."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:cabin-cruiser",
        name: "Cabin Cruiser",
        barterValue: "GG12,000",
        streetPrice: 120000,
        sourcePages: [294],
        tags: ["civilian", "watercraft", "cabin-cruiser"],
        description: "A family-sized inland or coastal motor craft with several days of endurance.",
        vehicle: {
            configuration: "superstructure",
            crew: { crew: 1, passengers: 5 },
            cargoKg: 500,
            weightKg: 7000,
            maintenanceHours: 5,
            movementModes: [water(17, 47, (0, shared_1.fuel)(["D"], 750, 40))],
            armor: { Hull: { rating: 1 }, Superstructure: { rating: 1 }, Waterline: { rating: 1 } },
            systems: {
                comm: "Vehicular shortwave radio.",
                sensors: "Civilian mapping GPS; navigational radio.",
                aux: "Living quarters (4 bunks, shower, chemical toilet, kitchenette, 200 L fresh water tank).",
            },
            traits: ["vehicle:soft-skinned"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:yacht-ocean-sailboat",
        name: "Yacht (Ocean Sailboat)",
        barterValue: "GG37,500",
        streetPrice: 375000,
        sourcePages: [294],
        tags: ["civilian", "watercraft", "yacht", "sailboat"],
        description: "An oceangoing sail yacht with an auxiliary diesel engine and home-like amenities.",
        vehicle: {
            configuration: "superstructure",
            crew: { crew: 3, passengers: 7 },
            crewText: "3 on-duty sailing crew + 7 additional berths.",
            cargoKg: 2000,
            weightKg: 21000,
            maintenanceHours: 6,
            movementModes: [
                (0, shared_1.movementMode)("sail", "Sail", "sail", {
                    travelSpeed: 7,
                    combatSpeed: 21,
                    traits: ["vehicle:wind-limited"],
                }),
                (0, shared_1.movementMode)("diesel", "Auxiliary Diesel", "water", {
                    travelSpeed: 4,
                    combatSpeed: 11,
                    fuel: (0, shared_1.fuel)(["D"], 460, 20),
                    notes: ["Generator-only operation consumes 2.5 L/hr."],
                }),
            ],
            armor: { Hull: { rating: 2 }, Superstructure: { rating: 1 }, Waterline: { rating: 2 } },
            systems: {
                comm: "Vehicular shortwave radio.",
                sensors: "Civilian mapping GPS; navigational radar.",
                aux: "Living quarters (5 double berths, shower, toilet, galley, 700 L fresh water tank); desalination system (100 L/day).",
            },
            traits: ["vehicle:soft-skinned", "vehicle:generator:10kw"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:barge",
        name: "Barge",
        barterValue: "GG40,000",
        streetPrice: 750000,
        sourcePages: [294],
        tags: ["civilian", "watercraft", "barge"],
        description: "An unpowered bulk-cargo barge built to be assembled into larger rafts.",
        vehicle: {
            configuration: "flush-deck",
            crew: { crew: 0 },
            cargoKg: 2100000,
            cargoText: "Hopper barge; tanker variant carries 5,000,000 liters.",
            weightKg: 1050000,
            maintenanceHours: 3,
            movementModes: [(0, shared_1.movementMode)("raft", "Towed or Pushed", "towed", {
                    notes: ["Unpowered; moved by towboat or tugboat as part of a raft."],
                    traits: ["vehicle:watercraft:towed"],
                })],
            armor: { Hull: { rating: 3 }, Waterline: { rating: 6 } },
            traits: ["vehicle:soft-skinned", "vehicle:towed"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:civilian:towboat",
        name: "Towboat",
        barterValue: "GG130,000",
        streetPrice: 2100000,
        sourcePages: [294, 295],
        tags: ["civilian", "watercraft", "towboat"],
        description: "A shallow-draft inland commercial boat built to push or pull large barge rafts.",
        vehicle: {
            configuration: "superstructure",
            crew: { crew: 2, passengers: 7 },
            crewText: "2 on watch (helmsman, lookout) + 7 additional working crew.",
            cargoKg: 5000,
            weightKg: 120000,
            maintenanceHours: 24,
            movementModes: [water(6, 17, (0, shared_1.fuel)(["D"], 20000, 160))],
            armor: { Hull: { rating: 3 }, Superstructure: { rating: 2 }, Waterline: { rating: 5 } },
            systems: {
                comm: "Vehicular shortwave radio.",
                sensors: "Civilian mapping GPS, navigational radar, 2 searchlights.",
                aux: "Living quarters (bunks for 7, shower, toilet, galley, 400 L fresh water tank).",
            },
            traits: ["vehicle:soft-skinned", "vehicle:barge-raft-capable"],
            notes: ["Listed speeds apply to rafts of zero to four barges; every additional barge slows movement further."],
        },
    }),
];
