"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MILITARY_VEHICLES = void 0;
const shared_1 = require("./shared");
const drive = (road, crossCountry, combatRoad, combatCrossCountry, modeFuel) => (0, shared_1.movementMode)("drive", "Drive", "ground", {
    travelSpeed: (0, shared_1.groundSpeed)(road, crossCountry),
    combatSpeed: (0, shared_1.groundSpeed)(combatRoad, combatCrossCountry),
    fuel: modeFuel,
});
const water = (speed, combatSpeed) => (0, shared_1.movementMode)("water", "Waterborne", "water", { travelSpeed: speed, combatSpeed });
// Source: Twilight 2013 Core OEF PDF p.286+ (military vehicle catalog in this pass)
exports.MILITARY_VEHICLES = [
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:truck-2-5-ton",
        name: "Truck, 2.5-ton (Military)",
        barterValue: "GG4,500",
        streetPrice: 36000,
        sourcePages: [284],
        tags: ["military", "ground", "cargo-truck"],
        description: "The standard military 2.5-ton cargo truck chassis used by transport units worldwide.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 1, passengers: 2 },
            cargoKg: 2500,
            towingCapacityKg: 6000,
            weightKg: 6500,
            maintenanceHours: 8,
            movementModes: [drive(30, 5, 83, 14, (0, shared_1.fuel)(["D"], 190, 24))],
            armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
            systems: { sensors: "Headlights." },
            traits: ["vehicle:soft-skinned", "vehicle:truck-variant-compatible"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:truck-5-ton",
        name: "Truck, 5-ton (Military)",
        barterValue: "GG6,000",
        streetPrice: 48000,
        sourcePages: [285],
        tags: ["military", "ground", "cargo-truck"],
        description: "A heavier military cargo truck built on the common 5-ton chassis.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 1, passengers: 2 },
            cargoKg: 5000,
            towingCapacityKg: 11000,
            weightKg: 9000,
            maintenanceHours: 8,
            movementModes: [drive(30, 7, 83, 19, (0, shared_1.fuel)(["D"], 240, 30))],
            armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
            systems: { sensors: "Headlights." },
            traits: ["vehicle:soft-skinned", "vehicle:truck-variant-compatible"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:truck-10-ton",
        name: "Truck, 10-ton (Military)",
        barterValue: "GG8,500",
        streetPrice: 70000,
        sourcePages: [285],
        tags: ["military", "ground", "cargo-truck"],
        description: "A military 10-ton cargo truck sharing the same listed chassis traits as the civilian version.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 1, passengers: 2 },
            cargoKg: 10000,
            towingCapacityKg: 11000,
            weightKg: 19000,
            maintenanceHours: 8,
            movementModes: [drive(30, 7, 83, 19, (0, shared_1.fuel)(["D"], 480, 60))],
            armor: { HF: { rating: 2 }, HS: { rating: 2 }, HR: { rating: 1 }, Susp: { rating: 4 } },
            systems: {
                sensors: "Headlights.",
                aux: "Cargo-handling crane (3-ton load limit).",
            },
            traits: ["vehicle:soft-skinned", "vehicle:truck-variant-compatible"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:truck-tactical",
        name: "Truck, Tactical",
        barterValue: "GG6,250",
        streetPrice: 50000,
        sourcePages: [286, 287],
        tags: ["military", "ground", "tactical-truck"],
        description: "A generic unarmored 4x4 tactical truck covering HMMWVs and similar patrol vehicles.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 1, passengers: 5 },
            cargoKg: 1250,
            weightKg: 2400,
            maintenanceHours: 6,
            movementModes: [drive(40, 10, 111, 28, (0, shared_1.fuel)(["D"], 90, 8))],
            armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
            systems: {
                armament: ["Weapon mount."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio.",
                sensors: "Headlights.",
                aux: "Self-recovery winch.",
            },
            equipment: { selfRecoveryWinch: true, weaponMounts: 1 },
            traits: ["vehicle:soft-skinned"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:truck-tactical-up-armored",
        name: "Truck, Tactical, Up-Armored",
        barterValue: "GG8,750",
        streetPrice: 70000,
        sourcePages: [286],
        tags: ["military", "ground", "tactical-truck", "up-armored"],
        description: "A tactical truck fitted with bolt-on armor kits optimized against asymmetric threats.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 2, passengers: 2 },
            crewText: "Driver and gunner plus two passengers.",
            cargoKg: 500,
            weightKg: 3000,
            maintenanceHours: 8,
            movementModes: [drive(40, 10, 111, 28, (0, shared_1.fuel)(["D"], 90, 11))],
            armor: { HF: { rating: 4 }, HS: { rating: 4 }, HR: { rating: 4 }, Susp: { rating: 3 } },
            systems: {
                armament: ["Protected weapon mount."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio.",
                sensors: "Headlights.",
                aux: "Self-recovery winch.",
            },
            equipment: { selfRecoveryWinch: true, weaponMounts: 1 },
            traits: ["vehicle:soft-skinned", "vehicle:crew-may-be-trapped-by-buckled-armor"],
            notes: ["Hot-weather models add air conditioning because sealed laminate windows do not open."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:armored-car",
        name: "Armored Car",
        barterValue: "GG32,500",
        streetPrice: 65000,
        sourcePages: [287],
        tags: ["military", "ground", "armored-car"],
        description: "A sloped-armored 4x4 reconnaissance or convoy-security vehicle with run-flat tires.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 3 },
            crewText: "Driver, gunner, commander.",
            cargoKg: 600,
            weightKg: 3500,
            maintenanceHours: 8,
            movementModes: [drive(35, 10, 97, 28, (0, shared_1.fuel)(["D"], 100, 12))],
            armor: { HF: { rating: 3 }, HS: { rating: 2 }, HR: { rating: 2 }, Susp: { rating: 3 } },
            systems: {
                armament: ["Weapon mount (usually GPMG)."],
                comm: "Military vehicular radio.",
                sensors: "Headlights; searchlight (gunner).",
                aux: "Self-recovery winch.",
            },
            equipment: { selfRecoveryWinch: true, weaponMounts: 1 },
            traits: ["vehicle:recon", "vehicle:usually-amphibious-quarter-cross-country-speed"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:mine-protected-vehicle",
        name: "Mine-Protected Vehicle",
        barterValue: "GG25,000",
        streetPrice: 125000,
        sourcePages: [287, 288],
        tags: ["military", "ground", "mpv"],
        description: "A V-hulled mine-protected truck optimized to survive IED and underbody blast threats.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 2, passengers: 4 },
            cargoKg: 2200,
            weightKg: 8900,
            maintenanceHours: 10,
            movementModes: [drive(40, 8, 111, 22, (0, shared_1.fuel)(["D"], 210, 20))],
            armor: { HF: { rating: 4 }, HS: { rating: 3 }, HR: { rating: 3 }, Susp: { rating: 4 } },
            systems: {
                armament: ["Protected weapon mount."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio.",
                sensors: "Headlights.",
            },
            traits: [
                "vehicle:soft-skinned",
                "vehicle:blast-underbody-armor-12",
                "vehicle:blast-frag-armor-tripled",
            ],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:m1126-stryker-icv",
        name: "M1126 Stryker ICV",
        barterValue: "GG1,000,000",
        streetPrice: 2000000,
        sourcePages: [287, 288],
        tags: ["military", "ground", "apc", "stryker"],
        description: "The standard U.S. Stryker infantry carrier vehicle with an unmanned remote mount.",
        vehicle: {
            configuration: "crew-in-hull",
            suspension: "or",
            crew: { crew: 2, passengers: 9 },
            crewText: "Driver and commander plus nine passengers.",
            cargoKg: 1800,
            weightKg: 16500,
            maintenanceHours: 14,
            movementModes: [drive(33, 15, 97, 42, (0, shared_1.fuel)(["D"], 200, 35))],
            armor: {
                HF: { rating: 10 },
                HS: { rating: 6 },
                HR: { rating: 6 },
                TF: { rating: 2 },
                TS: { rating: 2 },
                TR: { rating: 2 },
                Susp: { rating: 5 },
            },
            systems: {
                armament: ["Modular remote weapons mount (standard stabilization)."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio; tactical data link.",
                sensors: "Headlights; night vision gunsight (commander); night vision system (driver).",
                aux: "NBC defense system; self-recovery winch.",
            },
            equipment: { nbcDefenseSystem: true, selfRecoveryWinch: true, weaponMounts: 1 },
            traits: ["vehicle:remote-weapon-station", "vehicle:weapon-mount:standard-stabilization"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:btr-80",
        name: "BTR-80",
        barterValue: "GG40,000",
        streetPrice: 80000,
        sourcePages: [287, 288],
        tags: ["military", "ground", "apc", "btr"],
        description: "A widely-exported Russian 8x8 APC with side doors between the axles.",
        vehicle: {
            configuration: "crew-in-hull",
            suspension: "or",
            crew: { crew: 3, passengers: 7 },
            crewText: "Driver, gunner, commander plus seven passengers.",
            cargoKg: 2300,
            weightKg: 13600,
            maintenanceHours: 12,
            movementModes: [drive(27, 20, 75, 56, (0, shared_1.fuel)(["D"], 300, 40)), water(5, 14)],
            armor: {
                HF: { rating: 9 },
                HS: { rating: 4 },
                HR: { rating: 4 },
                TF: { rating: 8 },
                TS: { rating: 4 },
                TR: { rating: 4 },
                Susp: { rating: 5 },
            },
            systems: {
                armament: ["KPV Heavy Machine Gun", "PKM Coaxial Machine Gun", "7 firing ports"],
                armamentIds: ["weapon:kpv:14-5x114mm", "weapon:pkm:7-62x54mmr"],
                ammo: "500 rounds belted 14.5mm; PKM ammunition carried as cargo.",
                comm: "Military vehicular radio.",
                sensors: "Headlights; IR searchlight on turret.",
                aux: "Amphibious running gear; NBC defense system; self-recovery winch.",
            },
            equipment: { amphibiousRunningGear: true, nbcDefenseSystem: true, selfRecoveryWinch: true, firingPorts: 7 },
            traits: ["vehicle:amphibious", "vehicle:afv"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:wz551",
        name: "Wz551",
        barterValue: "GG100,000",
        streetPrice: 200000,
        sourcePages: [288],
        tags: ["military", "ground", "apc", "wz551"],
        description: "A Chinese-built 6x6 APC representative of many local wheeled APC designs.",
        vehicle: {
            configuration: "crew-in-hull",
            suspension: "or",
            crew: { crew: 2, passengers: 11 },
            crewText: "Driver and commander plus eleven passengers.",
            cargoKg: 1600,
            weightKg: 14700,
            maintenanceHours: 12,
            movementModes: [drive(30, 15, 83, 42, (0, shared_1.fuel)(["D"], 290, 24)), water(3.75, 10.5)],
            armor: {
                HF: { rating: 4 },
                HS: { rating: 3 },
                HR: { rating: 3 },
                TF: { rating: 3 },
                TS: { rating: 3 },
                TR: { rating: 3 },
                Susp: { rating: 5 },
            },
            systems: {
                armament: ["NSV Heavy Machine Gun", "PKM Coaxial Machine Gun", "8 firing ports"],
                armamentIds: ["weapon:nsv:12-7x108mm", "weapon:pkm:7-62x54mmr"],
                ammo: "1,000 rounds belted 12.7mm; 1,000 rounds belted 7.62x54mm.",
                comm: "Military vehicular radio.",
                sensors: "Headlights; night vision system (commander, driver).",
                aux: "Amphibious running gear.",
            },
            equipment: { amphibiousRunningGear: true, firingPorts: 8 },
            traits: ["vehicle:amphibious", "vehicle:afv"],
            notes: ["Frontmost firing ports on each side accept a SAW or GPMG."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:fv510-warrior",
        name: "FV510 Warrior",
        barterValue: "GG1,415,000",
        streetPrice: 2830000,
        sourcePages: [288],
        tags: ["military", "ground", "ifv", "warrior"],
        description: "A British IFV whose RARDEN autocannon is powerful but mechanically awkward.",
        vehicle: {
            configuration: "turreted",
            suspension: "trk",
            crew: { crew: 3, passengers: 7 },
            crewText: "Driver, gunner, commander plus seven passengers.",
            cargoKg: 1500,
            weightKg: 24000,
            maintenanceHours: 24,
            movementModes: [drive(25, 16, 70, 44, (0, shared_1.fuel)(["D"], 770, 170))],
            armor: {
                HF: { rating: 6 },
                HS: { rating: 4 },
                HR: { rating: 3 },
                TF: { rating: 6 },
                TS: { rating: 2 },
                TR: { rating: 2 },
                Susp: { rating: 5 },
            },
            systems: {
                armament: ["L21A1 RARDEN 30mm Autocannon", "L94A1 Chain Gun"],
                armamentIds: ["vehicle-weapon:l21a1-rarden-30mm", "vehicle-weapon:l94a1-chain-gun"],
                ammo: "228 rounds of 30mm; 2,200 rounds belted 7.62mm NATO.",
                comm: "Military vehicular radio.",
                sensors: "Headlights; thermal and night vision system (driver); thermal and night vision gunsights (commander, gunner); laser rangefinder; military GPS receiver.",
                aux: "NBC defense system.",
            },
            equipment: { nbcDefenseSystem: true },
            traits: ["vehicle:afv"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:m113",
        name: "M113",
        barterValue: "GG630,000",
        streetPrice: 1260000,
        sourcePages: [289],
        tags: ["military", "ground", "apc", "m113"],
        description: "A late-upgrade M113 APC with restored amphibious capability and no true NBC seal.",
        vehicle: {
            configuration: "standard",
            suspension: "trk",
            crew: { crew: 2, passengers: 11 },
            crewText: "Driver and commander plus eleven passengers.",
            cargoKg: 2000,
            weightKg: 12300,
            maintenanceHours: 14,
            movementModes: [drive(22, 15, 61, 42, (0, shared_1.fuel)(["D"], 360, 36)), water(3.75, 10.5)],
            armor: { HF: { rating: 6 }, HS: { rating: 4 }, HR: { rating: 4 }, Susp: { rating: 5 } },
            systems: {
                armament: ["Protected weapon mount (usually M2HB)."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio.",
                sensors: "Headlights.",
                aux: "Amphibious running gear; filtered breathing mask system for crew and passengers.",
            },
            equipment: { amphibiousRunningGear: true, weaponMounts: 1 },
            traits: ["vehicle:afv", "vehicle:no-nbc-seal", "vehicle:filtered-breathing-masks"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:bmp-2",
        name: "BMP-2",
        barterValue: "GG950,000",
        streetPrice: 1900000,
        sourcePages: [289],
        tags: ["military", "ground", "ifv", "bmp-2"],
        description: "A widely-exported Cold War IFV with a dual-feed 30mm autocannon and AT-14 missiles.",
        vehicle: {
            configuration: "turreted",
            suspension: "trk",
            crew: { crew: 3, passengers: 7 },
            crewText: "Driver, gunner, commander plus seven passengers.",
            cargoKg: 1700,
            weightKg: 14300,
            maintenanceHours: 18,
            movementModes: [drive(22, 15, 61, 42, (0, shared_1.fuel)(["D"], 460, 130)), water(3.75, 10.5)],
            armor: {
                HF: { rating: 4 },
                HS: { rating: 3 },
                HR: { rating: 3 },
                TF: { rating: 5 },
                TS: { rating: 3 },
                TR: { rating: 2 },
                Susp: { rating: 5 },
            },
            systems: {
                armament: ["2A42 30mm Autocannon", "AT-14 Launcher", "PKM Coaxial Machine Gun"],
                armamentIds: ["vehicle-weapon:2a42-30mm", "vehicle-weapon:at14-launcher", "weapon:pkm:7-62x54mmr"],
                ammo: "1,000 rounds of 30mm; 5 AT-14 missiles; 2,000 rounds belted 7.62x54mm.",
                comm: "Military vehicular radio.",
                sensors: "Headlights; night vision gunsight (gunner); laser rangefinder.",
                aux: "Amphibious running gear; NBC defense system.",
            },
            equipment: { amphibiousRunningGear: true, nbcDefenseSystem: true },
            traits: ["vehicle:afv"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:m2a3-bradley-ifv",
        name: "M2A3 Bradley IFV",
        barterValue: "GG1,600,000",
        streetPrice: 3200000,
        sourcePages: [289, 290],
        tags: ["military", "ground", "ifv", "bradley"],
        description: "The A3 Bradley combines spaced armor, a Bushmaster cannon, and TOW missiles in a heavy tracked IFV.",
        vehicle: {
            configuration: "turreted",
            suspension: "trk",
            crew: { crew: 3, passengers: 6 },
            cargoKg: 1500,
            weightKg: 33000,
            maintenanceHours: 16,
            movementModes: [drive(22, 12, 66, 33, (0, shared_1.fuel)(["D"], 750, 190)), water(3, 8.25)],
            armor: {
                HF: { rating: 14, spaced: true },
                HS: { rating: 12, spaced: true },
                HR: { rating: 6 },
                TF: { rating: 12, spaced: true },
                TS: { rating: 6, spaced: true },
                TR: { rating: 4, spaced: true },
                Susp: { rating: 5 },
            },
            systems: {
                armament: ["M242 Bushmaster 25mm Autocannon (good stabilization)", "TOW Launcher (2 launch tubes)", "MAG Coaxial Machine Gun"],
                armamentIds: ["vehicle-weapon:m242-bushmaster-25mm", "vehicle-weapon:tow-launcher", "weapon:fn-mag:7-62x51mm"],
                ammo: "900 rounds of 25mm; 7 TOW missiles; 2,200 rounds belted 7.62mm NATO.",
                comm: "Military vehicular radio; tactical data link.",
                sensors: "Headlights; night vision system (driver); thermal and night vision gunsights (commander, gunner).",
                aux: "Amphibious running gear; NBC defense system.",
            },
            equipment: { amphibiousRunningGear: true, nbcDefenseSystem: true },
            traits: ["vehicle:afv", "vehicle:weapon:tow-reload-exposed-double-time"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:m577-toc",
        name: "M577 TOC",
        barterValue: "GG900,000",
        streetPrice: 1800000,
        sourcePages: [290],
        tags: ["military", "ground", "command-vehicle"],
        description: "A command-post vehicle on the M113 chassis designed for staff work rather than direct combat.",
        vehicle: {
            configuration: "standard",
            suspension: "trk",
            crew: { crew: 4, passengers: 2 },
            crewText: "Driver, commander, two radio operators plus two additional passengers.",
            cargoKg: 1500,
            weightKg: 12700,
            maintenanceHours: 18,
            movementModes: [drive(22, 15, 66, 42, (0, shared_1.fuel)(["D"], 500, 36)), water(3.75, 10.5)],
            armor: { HF: { rating: 6 }, HS: { rating: 4 }, HR: { rating: 4 }, Susp: { rating: 5 } },
            systems: {
                comm: "4 military vehicular radios; stationary shortwave radio.",
                sensors: "Headlights; military mapping GPS.",
                aux: "4.2 kW generator (1.5 L/hr); A-frame crane (200 kg); amphibious running gear; NBC defense system; command-post computers and office equipment.",
            },
            equipment: { amphibiousRunningGear: true, nbcDefenseSystem: true },
            traits: ["vehicle:command-post", "vehicle:generator:4-2kw"],
            notes: ["M1068 SICPS variant adds tactical data link and updated ruggedized computing gear."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:m88a2-hercules",
        name: "M88A2 HERCULES",
        barterValue: "GG500,000",
        streetPrice: 2100000,
        sourcePages: [291],
        tags: ["military", "ground", "recovery-vehicle"],
        description: "A heavy armored recovery vehicle built to tow, repair, and refuel disabled AFVs in the field.",
        vehicle: {
            configuration: "standard",
            suspension: "trk",
            crew: { crew: 3, passengers: 4 },
            crewText: "Driver, commander, mechanic plus four passengers.",
            cargoKg: 800,
            towingCapacityKg: 70000,
            weightKg: 70000,
            maintenanceHours: 18,
            movementModes: [drive(16, 8, 44, 22, (0, shared_1.fuel)(["D"], 1520, 160))],
            armor: { HF: { rating: 6 }, HS: { rating: 4 }, HR: { rating: 4 }, Susp: { rating: 6 } },
            systems: {
                armament: ["Weapon mount (usually M2HB)."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio.",
                sensors: "Headlights.",
                aux: "A-frame crane (35-ton); bulldozer blade; horizontal winch (70-ton); secondary winch (3-ton); fuel pump.",
            },
            equipment: { weaponMounts: 1 },
            traits: ["vehicle:recovery-vehicle", "vehicle:fuel-transfer-capable"],
            notes: ["Standard cargo includes basic tools, power tools, mechanic's tools, and model-specific tools."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:tpz-fuchs-nbc-recon",
        name: "TPz Fuchs (NBC Recon)",
        barterValue: "GG1,100,000",
        streetPrice: 2200000,
        sourcePages: [291],
        tags: ["military", "ground", "nbc-recon"],
        description: "A German 6x6 recon vehicle fitted for chemical, biological, and radiological survey work.",
        vehicle: {
            configuration: "standard",
            suspension: "or",
            crew: { crew: 3, passengers: 3 },
            crewText: "Driver, commander, sensor operator plus three passengers.",
            cargoKg: 2000,
            weightKg: 20300,
            maintenanceHours: 12,
            movementModes: [drive(35, 10, 97, 28, (0, shared_1.fuel)(["D"], 290, 40)), water(2.5, 7)],
            armor: { HF: { rating: 4 }, HS: { rating: 3 }, HR: { rating: 3 }, Susp: { rating: 4 } },
            systems: {
                armament: ["Weapon mount (typically MAG)."],
                ammo: "Dependent on mounted weapon; carried as cargo.",
                comm: "Military vehicular radio; tactical data net.",
                sensors: "Biological hazard sensor (50 m); headlights; military mapping GPS; radiation sensor (500 m); remote chemical hazard sensor (5 km); weather sensors.",
                aux: "Amphibious running gear; NBC defense system; 3 ruggedized notebook computers.",
            },
            equipment: { amphibiousRunningGear: true, nbcDefenseSystem: true, weaponMounts: 1 },
            traits: ["vehicle:nbc-recon", "vehicle:amphibious"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:leopard-2",
        name: "Leopard 2",
        barterValue: "GG2,000,000",
        streetPrice: 4000000,
        sourcePages: [291, 292],
        tags: ["military", "ground", "mbt", "leopard-2"],
        description: "A common NATO main battle tank and the backbone of many European armored forces.",
        vehicle: {
            configuration: "turreted",
            suspension: "trk",
            crew: { crew: 4 },
            crewText: "Driver, gunner, loader, commander.",
            cargoKg: 100,
            cargoText: "100 kg internal plus 500 kg in bustle rack.",
            weightKg: 62300,
            maintenanceHours: 26,
            movementModes: [drive(24, 15, 67, 42, (0, shared_1.fuel)(["D"], 1160, 140))],
            armor: {
                HF: { rating: 160, composite: true },
                HS: { rating: 24 },
                HR: { rating: 11 },
                TF: { rating: 100, composite: true },
                TS: { rating: 24 },
                TR: { rating: 20 },
                Susp: { rating: 6 },
            },
            systems: {
                armament: ["L44 120mm Cannon (good stabilization)", "MAG Coaxial Machine Gun", "Commander Weapons Mount (typically MAG)"],
                armamentIds: ["vehicle-weapon:l44-120mm", "weapon:fn-mag:7-62x51mm"],
                ammo: "42 rounds of 120mm ammunition; 4,800 rounds belted 7.62mm NATO.",
                comm: "Military vehicular radio; tactical data net on Canadian and EU vehicles.",
                sensors: "Headlights; night vision system (driver); thermal and night vision gunsights (commander, gunner).",
                aux: "NBC defense system.",
            },
            equipment: { nbcDefenseSystem: true, weaponMounts: 1 },
            traits: ["vehicle:afv", "vehicle:main-battle-tank"],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:t-55",
        name: "T-55",
        barterValue: "GG600,000",
        streetPrice: 1200000,
        sourcePages: [292],
        tags: ["military", "ground", "mbt", "t-55"],
        description: "An obsolete but still dangerous Soviet-era tank fielded across much of the world.",
        vehicle: {
            configuration: "turreted",
            suspension: "trk",
            crew: { crew: 4 },
            cargoKg: 100,
            cargoText: "100 kg internal plus 600 kg in bustle rack.",
            weightKg: 41000,
            maintenanceHours: 18,
            movementModes: [drive(17, 12, 47, 33, (0, shared_1.fuel)(["D"], 560, 27))],
            armor: {
                HF: { rating: 40 },
                HS: { rating: 16 },
                HR: { rating: 12 },
                TF: { rating: 41 },
                TS: { rating: 26 },
                TR: { rating: 12 },
                Susp: { rating: 6 },
            },
            systems: {
                armament: ["D-10 100mm Cannon", "PKM Coaxial Machine Gun", "Commander Pintle-Mounted NSV"],
                armamentIds: ["vehicle-weapon:d10-100mm", "weapon:pkm:7-62x54mmr", "weapon:nsv:12-7x108mm"],
                ammo: "43 rounds of 100mm; 3,000 rounds belted 7.62x54mm; 1,000 rounds belted 12.7mm.",
                comm: "Military vehicular radio.",
                sensors: "Headlights; night vision system (driver); night vision gunsights (commander, gunner).",
                aux: "Radiation shielding.",
            },
            equipment: { weaponMounts: 1 },
            traits: ["vehicle:afv", "vehicle:main-battle-tank"],
            notes: ["Listed fuel includes two optional 200 L rear drop tanks."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:t-72",
        name: "T-72",
        barterValue: "GG1,250,000",
        streetPrice: 2500000,
        sourcePages: [292, 293],
        tags: ["military", "ground", "mbt", "t-72"],
        description: "The most common Twilight War tank, kept in service by low cost and easy maintenance.",
        vehicle: {
            configuration: "turreted",
            suspension: "trk",
            crew: { crew: 3 },
            cargoKg: 75,
            cargoText: "75 kg internal plus 700 kg in bustle rack.",
            weightKg: 41500,
            maintenanceHours: 26,
            movementModes: [drive(20, 11, 56, 31, (0, shared_1.fuel)(["D"], 1000, 135))],
            armor: {
                HF: { rating: 100, composite: true },
                HS: { rating: 16 },
                HR: { rating: 10 },
                TF: { rating: 70 },
                TS: { rating: 24 },
                TR: { rating: 20 },
                Susp: { rating: 6 },
            },
            systems: {
                armament: ["2A46M 125mm Cannon", "PKM Coaxial Machine Gun", "Commander Pintle-Mounted NSV"],
                armamentIds: ["vehicle-weapon:2a46m-125mm", "weapon:pkm:7-62x54mmr", "weapon:nsv:12-7x108mm"],
                ammo: "40 rounds of 125mm; 2,000 rounds belted 7.62x54mm; 300 rounds belted 12.7mm.",
                comm: "2 military vehicular radios.",
                sensors: "Headlights; laser rangefinder; night vision system (driver); thermal and night vision gunsights (commander, gunner).",
                aux: "Autoloader; NBC defense system.",
            },
            equipment: { nbcDefenseSystem: true, weaponMounts: 1 },
            traits: ["vehicle:afv", "vehicle:main-battle-tank", "vehicle:autoloader:9-ticks:22-round-capacity"],
            notes: ["Drop tanks are listed separately in the source but not included in main fuel capacity here."],
        },
    }),
    (0, shared_1.defineVehicle)({
        id: "vehicle:military:patrol-boat",
        name: "Patrol Boat",
        barterValue: "GG3,500,000",
        streetPrice: 7000000,
        sourcePages: [295],
        tags: ["military", "watercraft", "patrol-boat"],
        description: "A coastal patrol craft used for naval security, rescue, customs, and fisheries enforcement.",
        vehicle: {
            configuration: "superstructure",
            crew: { crew: 8, passengers: 12 },
            crewText: "8 on duty + 8 off duty + 4 passengers.",
            cargoKg: 5000,
            weightKg: 170000,
            maintenanceHours: 30,
            movementModes: [(0, shared_1.movementMode)("water", "Waterborne", "water", { travelSpeed: 19, combatSpeed: 53, fuel: (0, shared_1.fuel)(["D"], 37000, 230) })],
            armor: { Hull: { rating: 2 }, Superstructure: { rating: 4 }, Waterline: { rating: 3 } },
            systems: {
                armament: [
                    "2A42 30mm Autocannon or M242 Bushmaster 25mm Autocannon (good stabilization, Armor 4 gunshield)",
                    "2 heavy machine guns on bridge rails",
                ],
                armamentIds: ["vehicle-weapon:2a42-30mm", "vehicle-weapon:m242-bushmaster-25mm"],
                ammo: "1,500 rounds autocannon ammunition; 5,000 rounds belted heavy machine gun ammunition.",
                comm: "Satellite communication system; vehicular CB radio; two vehicular shortwave radios, one with military encryption.",
                sensors: "Military mapping GPS; surface search and navigation radar; 6 searchlights.",
                aux: "Crane (2-ton capacity); motorboat; living quarters; desalination plant (1,800 L/day, 3,600 L fresh water tank); huge fixed generator.",
            },
            traits: ["vehicle:generator:large-fixed"],
        },
    }),
];
