"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FIXED_LBE_COMPONENT_CONTAINERS = exports.FIXED_LOAD_BEARING_CONTAINERS = void 0;
const helpers_1 = require("./helpers");
exports.FIXED_LOAD_BEARING_CONTAINERS = [
    (0, helpers_1.defineContainer)({
        id: "container:lbe:basic-belt-and-yoke",
        name: "Basic Belt and Yoke",
        weight: 1,
        tags: ["container", "load-bearing-equipment", "fixed-lbe"],
        barterValue: "GG20",
        streetPrice: 200,
        voucherCost: { "worn:torso": 1 },
        voucherLimits: { "lbe:component": 10, "lbe:belt-component": 4 },
        description: "Fixed load-bearing harness for up to 10 components, of which no more than 4 may be belt components.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineContainer)({
        id: "container:lbe:tactical-vest",
        name: "Tactical Vest",
        weight: 1.3,
        tags: ["container", "load-bearing-equipment", "fixed-lbe", "vest"],
        barterValue: "GG20",
        streetPrice: 200,
        voucherCost: { "worn:torso": 1 },
        voucherLimits: { "lbe:component": 10, "lbe:belt-component": 4 },
        description: "Fixed tactical vest for up to 10 attached LBE components, with no more than 4 designated as belt components.",
        defaultMode: "bag",
    }),
];
exports.FIXED_LBE_COMPONENT_CONTAINERS = [
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:cartridge-loop",
        name: "Cartridge Loop",
        weight: 0,
        tags: ["container", "load-bearing-component", "ammo-storage"],
        description: "Fixed LBE component sized for 10 rifle shells.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:holster",
        name: "Holster",
        weight: 0.2,
        tags: ["container", "load-bearing-component", "holster"],
        itemVoucherRules: [{ key: "stowed:handgun", acceptedItemTags: ["handgun"] }],
        voucherLimits: { "stowed:handgun": 1 },
        description: "Fixed LBE holster sized for 1 handgun.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:grenade-loop",
        name: "Grenade Loop",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "grenade-carriage"],
        description: "Fixed LBE component sized for 1 hand or launcher grenade.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:mag-carrier-rifle-double",
        name: "Mag Carrier, Rifle, Double",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "magazine-carrier"],
        itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
        voucherLimits: { "stowed:magazine": 2 },
        description: "Fixed LBE component sized for 2 rifle magazines.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:mag-carrier-pistol-triple",
        name: "Mag Carrier, Pistol, Triple",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "magazine-carrier"],
        itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
        voucherLimits: { "stowed:magazine": 3 },
        description: "Fixed LBE component sized for 3 handgun magazines.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:radio-pouch",
        name: "Radio Pouch",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "radio-pouch"],
        itemVoucherRules: [(0, helpers_1.createItemRule)("stowed:radio", ["radio"])],
        voucherLimits: { "stowed:radio": 1 },
        description: "Fixed LBE component sized for 1 radio or similarly sized device.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:sheath",
        name: "Sheath",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "sheath"],
        itemVoucherRules: [(0, helpers_1.createItemRule)("stowed:knife", ["knife"])],
        voucherLimits: { "stowed:knife": 1 },
        description: "Fixed LBE component sized for 1 knife.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:shell-loop",
        name: "Shell Loop",
        weight: 0,
        tags: ["container", "load-bearing-component", "ammo-storage"],
        description: "Fixed LBE component sized for 5 shotgun shells.",
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:canteen-carrier",
        name: "Canteen Carrier",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "canteen-carrier"],
        containerVoucherRules: [(0, helpers_1.createContainerRule)("stowed:canteen", ["water-container"])],
        voucherLimits: { "stowed:canteen": 1 },
        description: "Belt-mounted fixed LBE component sized for 1 canteen.",
        beltComponent: true,
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:mag-carrier-rifle-quad",
        name: "Mag Carrier, Rifle, Quad",
        weight: 0.2,
        tags: ["container", "load-bearing-component", "magazine-carrier"],
        itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
        voucherLimits: { "stowed:magazine": 4 },
        description: "Belt-mounted fixed LBE component sized for 4 rifle magazines.",
        beltComponent: true,
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:shell-carrier",
        name: "Shell Carrier",
        weight: 0.1,
        tags: ["container", "load-bearing-component", "ammo-storage"],
        description: "Belt-mounted fixed LBE component sized for 36 shotgun shells.",
        beltComponent: true,
        defaultMode: "bag",
    }),
    (0, helpers_1.defineAttachmentContainer)({
        id: "container:lbe:utility-pouch",
        name: "Utility Pouch",
        weight: 0.2,
        tags: ["container", "load-bearing-component", "utility-pouch"],
        description: "Belt-mounted fixed LBE utility pouch with roughly 12 x 18 x 8 cm of internal space.",
        beltComponent: true,
        defaultMode: "bag",
    }),
];
