import type { ItemDefinition } from "../types";
import {
	defineAcPoweredDevice,
	defineBatteryDevice,
	defineElectronicItem,
	defineRechargeableDevice,
} from "./helpers";

export const COMMUNICATION_ITEMS: ItemDefinition[] = [
	defineBatteryDevice({
		id: "communication:radio-cb-handheld",
		name: "CB Radio, Hand-held",
		weight: 2,
		tags: ["communication", "radio", "signal", "cb", "handheld"],
		barterValue: "GG50",
		streetPrice: 100,
		powerRequirement: "4 med/6 hrs",
		batteryCount: 4,
		batterySize: "med",
		runtimeHours: 6,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
		description: "Hand-held civilian CB set with short tactical range.",
	}),
	defineElectronicItem({
		id: "communication:radio-cb-vehicular",
		name: "CB Radio, Vehicular",
		weight: 4,
		tags: ["communication", "radio", "signal", "cb", "vehicular"],
		barterValue: "GG75",
		streetPrice: 150,
		powerRequirement: "0.5 kW",
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:receiver-emergency",
		name: "Emergency Receiver",
		weight: 0.3,
		tags: ["communication", "radio", "receiver", "signal"],
		barterValue: "GG50",
		streetPrice: 50,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineBatteryDevice({
		id: "communication:radio-personal",
		name: "Personal Radio",
		weight: 0.2,
		tags: ["communication", "radio", "signal", "personal", "handheld"],
		barterValue: "GG12.5",
		streetPrice: 50,
		powerRequirement: "4 sm/8 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 8,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineBatteryDevice({
		id: "communication:radio-personal-licensed",
		name: "Personal Radio, Licensed",
		weight: 0.5,
		tags: ["communication", "radio", "signal", "personal", "handheld"],
		barterValue: "GG35",
		streetPrice: 70,
		powerRequirement: "4 sm/6 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 6,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:radio-scanner",
		name: "Scanner",
		weight: 1,
		tags: ["communication", "radio", "receiver", "signal"],
		barterValue: "GG12.5",
		streetPrice: 50,
		powerRequirement: "0.2 kW",
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineAcPoweredDevice({
		id: "communication:radio-shortwave-vehicular",
		name: "Shortwave Radio, Vehicular",
		weight: 50,
		tags: ["communication", "radio", "signal", "shortwave", "vehicular"],
		barterValue: "GG1,000",
		streetPrice: 2000,
		powerRequirement: "1.2 kW",
		kilowatts: 1.2,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineAcPoweredDevice({
		id: "communication:radio-shortwave-stationary",
		name: "Shortwave Radio, Stationary",
		weight: 75,
		tags: ["communication", "radio", "signal", "shortwave", "stationary"],
		barterValue: "GG1,500",
		streetPrice: 3000,
		powerRequirement: "1.5 kW",
		kilowatts: 1.5,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineRechargeableDevice({
		id: "communication:radio-manpack",
		name: "Manpack Radio",
		weight: 10.5,
		tags: ["communication", "radio", "signal", "backpack"],
		barterValue: "GG4,875",
		streetPrice: 6500,
		powerRequirement: "charge/33 hrs",
		runtimeHours: 33,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineRechargeableDevice({
		id: "communication:radio-survival",
		name: "Survival Radio",
		weight: 1.2,
		tags: ["communication", "radio", "signal", "survival", "handheld"],
		barterValue: "GG2,250",
		streetPrice: 3000,
		powerRequirement: "charge/24 hrs",
		runtimeHours: 24,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineRechargeableDevice({
		id: "communication:radio-tactical",
		name: "Tactical Radio",
		weight: 1,
		tags: ["communication", "radio", "signal", "tactical", "handheld"],
		barterValue: "GG1,125",
		streetPrice: 1500,
		powerRequirement: "charge/20 hrs",
		runtimeHours: 20,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineAcPoweredDevice({
		id: "communication:radio-vehicular-military",
		name: "Vehicular Radio",
		weight: 14,
		tags: ["communication", "radio", "signal", "vehicular", "military"],
		barterValue: "GG4,875",
		streetPrice: 6500,
		powerRequirement: "2 kW",
		kilowatts: 2,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:radio-modem-shortwave",
		name: "Shortwave Radio Modem",
		weight: 1,
		tags: ["communication", "radio", "signal", "modem", "accessory"],
		barterValue: "GG75",
		streetPrice: 150,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:field-telephone",
		name: "Field Telephone",
		weight: 1.4,
		tags: ["communication", "signal", "wired", "telephone"],
		barterValue: "GG50",
		streetPrice: 500,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:field-telephone-wire-100m",
		name: "Field Telephone Wire, 100m",
		weight: 5,
		tags: ["communication", "signal", "wired", "telephone", "cable"],
		barterValue: "GG5",
		streetPrice: 50,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:field-telephone-switchboard",
		name: "Field Telephone Switchboard",
		weight: 13.6,
		tags: ["communication", "signal", "wired", "telephone", "switchboard"],
		barterValue: "GG120",
		streetPrice: 1200,
		source: ["Source: Twilight 2013 Core OEF PDF p.221"],
	}),
	defineElectronicItem({
		id: "communication:signal-strobe-light",
		name: "Strobe Light",
		weight: 0.1,
		tags: ["communication", "signal", "visual", "strobe", "electronic"],
		barterValue: "GG25",
		streetPrice: 50,
		source: ["Source: Twilight 2013 Core OEF PDF p.220"],
	}),
	defineElectronicItem({
		id: "communication:signal-strobe-light-ir",
		name: "Strobe Light, IR",
		weight: 0.2,
		tags: ["communication", "signal", "visual", "strobe", "infrared", "electronic"],
		barterValue: "GG100",
		streetPrice: 250,
		source: ["Source: Twilight 2013 Core OEF PDF p.220"],
	}),
];
