import type { ItemDefinition } from "../types";
import { defineBatteryDevice, defineElectronicItem, defineRechargeableDevice } from "./helpers";

const SRC_242 = "Source: Twilight 2013 Core OEF PDF p.242";

export const CONSUMER_ELECTRONICS: ItemDefinition[] = [
	defineBatteryDevice({
		id: "consumer:cd-player-personal",
		name: "CD Player, Personal",
		weight: 0.3,
		tags: ["consumer-electronics", "audio", "cd-player"],
		barterValue: "GG1.25",
		streetPrice: 20,
		powerRequirement: "2 sm/6 hrs",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 6,
		source: [SRC_242],
		description: "Portable personal CD player. CDs are an optical medium immune to EMP.",
	}),
	defineBatteryDevice({
		id: "consumer:cd-player-radio-portable",
		name: "CD Player/Radio, Portable",
		weight: 3,
		tags: ["consumer-electronics", "audio", "cd-player", "radio", "boombox"],
		barterValue: "GG3",
		streetPrice: 120,
		powerRequirement: "6 med/5 hrs",
		batteryCount: 6,
		batterySize: "med",
		runtimeHours: 5,
		source: [SRC_242],
		description: "Boom-box style AM/FM receiver and CD player combination.",
	}),
	defineBatteryDevice({
		id: "consumer:dictaphone",
		name: "Dictaphone",
		weight: 0.1,
		tags: ["consumer-electronics", "audio", "recorder"],
		barterValue: "GG6.25",
		streetPrice: 50,
		powerRequirement: "2 sm/12 hrs",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 12,
		source: [SRC_242],
		description: "Digital voice recorder with up to 20 hours of recording capacity.",
	}),
	defineRechargeableDevice({
		id: "consumer:digital-player-audio",
		name: "Digital Media Player, Audio",
		weight: 0.1,
		tags: ["consumer-electronics", "audio", "media-player"],
		barterValue: "GG3.25",
		streetPrice: 50,
		powerRequirement: "charge/20 hrs",
		runtimeHours: 20,
		source: [SRC_242],
		description: "Portable audio media player holding up to 400 hours of audio.",
	}),
	defineRechargeableDevice({
		id: "consumer:digital-player-video",
		name: "Digital Media Player, Video",
		weight: 0.1,
		tags: ["consumer-electronics", "video", "media-player"],
		barterValue: "GG6.25",
		streetPrice: 100,
		powerRequirement: "charge/20 hrs",
		runtimeHours: 20,
		source: [SRC_242],
		description: "Portable video media player holding up to 1,600 hours of audio or 200 hours of video.",
	}),
	defineBatteryDevice({
		id: "consumer:dvd-player-portable",
		name: "DVD Player, Portable",
		weight: 1.4,
		tags: ["consumer-electronics", "video", "dvd"],
		barterValue: "GG5",
		streetPrice: 80,
		powerRequirement: "2 med/4 hrs",
		batteryCount: 2,
		batterySize: "med",
		runtimeHours: 4,
		source: [SRC_242],
		description: "Hardcover-book-sized portable DVD player with flip-up screen and speakers.",
	}),
	defineBatteryDevice({
		id: "consumer:game-console-portable",
		name: "Game Console, Portable",
		weight: 1.3,
		tags: ["consumer-electronics", "gaming"],
		barterValue: "GG10",
		streetPrice: 400,
		powerRequirement: "4 sm/2 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 2,
		source: [SRC_242],
		description: "Self-contained portable video game system with screen, controller, and speakers.",
	}),
	defineElectronicItem({
		id: "consumer:radio-outreach",
		name: "Radio, Outreach",
		weight: 1.2,
		tags: ["consumer-electronics", "radio", "receiver"],
		barterValue: "GG1",
		streetPrice: 80,
		powerRequirement: "see text",
		source: [SRC_242],
		description: "Rugged hand-crank AM/FM receiver. 30 seconds of cranking charges the internal battery for 30 minutes of listening.",
		traits: ["hand-crank-power"],
	}),
	defineBatteryDevice({
		id: "consumer:radio-personal",
		name: "Radio, Personal",
		weight: 0.1,
		tags: ["consumer-electronics", "radio", "receiver"],
		barterValue: "GG0.25",
		streetPrice: 10,
		powerRequirement: "2 sm/20 hrs",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 20,
		source: [SRC_242],
		description: "Deck-of-cards-sized AM/FM receiver with headset but no external speaker.",
	}),
	defineBatteryDevice({
		id: "consumer:radio-portable",
		name: "Radio, Portable",
		weight: 1,
		tags: ["consumer-electronics", "radio", "receiver"],
		barterValue: "GG0.3",
		streetPrice: 30,
		powerRequirement: "2 med/10 hrs",
		batteryCount: 2,
		batterySize: "med",
		runtimeHours: 10,
		source: [SRC_242],
		description: "Larger AM/FM receiver with external speakers, digital tuning, and presets.",
	}),
	defineRechargeableDevice({
		id: "consumer:razor-electric",
		name: "Razor, Electric",
		weight: 1,
		tags: ["consumer-electronics", "personal-care"],
		barterValue: "GG5",
		streetPrice: 100,
		powerRequirement: "charge/45 min.",
		runtimeHours: 0.75,
		source: [SRC_242],
		description: "Rechargeable electric razor. Full charge takes ~6 hours at ~30-40 watts.",
	}),
];
