import type { ItemDefinition } from "../types";
import { defineAcPoweredDevice, defineElectronicItem } from "./helpers";

export const POWERED_TOOLS: ItemDefinition[] = [
	defineElectronicItem({
		id: "tool:air-compressor",
		name: "Air Compressor",
		weight: 39,
		tags: ["tool", "powered-tool", "compressor"],
		barterValue: "GG800",
		streetPrice: 3200,
		powered: true,
		powerRequirement: "see text",
	}),
	defineAcPoweredDevice({
		id: "tool:aircraft-tools",
		name: "Aircraft Tools",
		weight: 75,
		tags: ["tool", "powered-tool", "aircraft-tools"],
		barterValue: "GG625",
		streetPrice: 2500,
		powerRequirement: "0.3 kW",
		kilowatts: 0.3,
	}),
	defineAcPoweredDevice({
		id: "tool:aircraft-tools-model-specific",
		name: "Aircraft Tools, Model-Specific",
		weight: 20,
		tags: ["tool", "powered-tool", "aircraft-tools"],
		barterValue: "GG200",
		streetPrice: 20000,
		powerRequirement: "0.5 kW",
		kilowatts: 0.5,
	}),
	defineAcPoweredDevice({
		id: "tool:basic-power-tools",
		name: "Basic Power Tools",
		weight: 15,
		tags: ["tool", "powered-tool", "workshop"],
		barterValue: "GG150",
		streetPrice: 1200,
		powerRequirement: "0.5 kW",
		kilowatts: 0.5,
	}),
	defineAcPoweredDevice({
		id: "tool:cement-mixer-portable",
		name: "Cement Mixer, Portable",
		weight: 70,
		tags: ["tool", "powered-tool", "construction"],
		barterValue: "GG85",
		streetPrice: 680,
		powerRequirement: "0.6 kW",
		kilowatts: 0.6,
	}),
	defineAcPoweredDevice({
		id: "tool:chainsaw-electric",
		name: "Chainsaw, Electric",
		weight: 3.3,
		tags: ["tool", "powered-tool", "chainsaw"],
		barterValue: "GG25",
		streetPrice: 100,
		powerRequirement: "2.2 kW",
		kilowatts: 2.2,
	}),
	defineElectronicItem({
		id: "tool:chainsaw-gasoline",
		name: "Chainsaw, Gasoline",
		weight: 4.5,
		tags: ["tool", "powered-tool", "chainsaw", "gasoline"],
		barterValue: "GG50",
		streetPrice: 200,
		powered: true,
		powerRequirement: "see text",
	}),
	defineAcPoweredDevice({
		id: "tool:machine-shop-portable",
		name: "Machine Shop, Portable",
		weight: 2.5,
		tags: ["tool", "powered-tool", "machine-shop"],
		barterValue: "GG625",
		streetPrice: 5000,
		powerRequirement: "1 kW",
		kilowatts: 1,
	}),
	defineElectronicItem({
		id: "tool:rescue-saw",
		name: "Rescue Saw",
		weight: 11,
		tags: ["tool", "powered-tool", "rescue-saw"],
		barterValue: "GG350",
		streetPrice: 1400,
		powered: true,
		powerRequirement: "see text",
	}),
	defineAcPoweredDevice({
		id: "tool:vehicle-tools-model-specific",
		name: "Vehicle Tools, Model-Specific",
		weight: 10,
		tags: ["tool", "powered-tool", "vehicle-tools"],
		barterValue: "GG100",
		streetPrice: 10000,
		powerRequirement: "0.2 kW",
		kilowatts: 0.2,
	}),
	// Welding and Cutting Torches
	defineAcPoweredDevice({
		id: "tool:arc-welder",
		name: "Arc Welder",
		weight: 30,
		tags: ["tool", "powered-tool", "welding"],
		barterValue: "GG100",
		streetPrice: 400,
		powerRequirement: "2 kW",
		kilowatts: 2,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "tool:oxy-fuel-torch",
		name: "Oxy-Fuel Torch",
		weight: 20,
		tags: ["tool", "powered-tool", "welding", "cutting"],
		barterValue: "GG150",
		streetPrice: 600,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	// Hydraulic Tools
	defineElectronicItem({
		id: "tool:hydraulic-power-unit",
		name: "Hydraulic Power Unit",
		weight: 45,
		tags: ["tool", "powered-tool", "hydraulic"],
		barterValue: "GG160",
		streetPrice: 8000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "tool:rescue-cutter",
		name: "Rescue Cutter",
		weight: 20,
		tags: ["tool", "powered-tool", "hydraulic", "rescue"],
		barterValue: "GG160",
		streetPrice: 8000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "tool:rescue-ram",
		name: "Rescue Ram",
		weight: 15,
		tags: ["tool", "powered-tool", "hydraulic", "rescue"],
		barterValue: "GG100",
		streetPrice: 5000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
];

export const GENERATORS: ItemDefinition[] = [
	// Fixed Generators
	defineElectronicItem({
		id: "power:generator-fixed-small",
		name: "Generator, Fixed, Small",
		weight: 222,
		tags: ["power", "generator", "fixed"],
		barterValue: "GG460",
		streetPrice: 3700,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:generator-fixed-medium",
		name: "Generator, Fixed, Medium",
		weight: 295,
		tags: ["power", "generator", "fixed"],
		barterValue: "GG810",
		streetPrice: 6500,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:generator-fixed-large",
		name: "Generator, Fixed, Large",
		weight: 1400,
		tags: ["power", "generator", "fixed"],
		barterValue: "GG2500",
		streetPrice: 20000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:generator-fixed-huge",
		name: "Generator, Fixed, Huge",
		weight: 1800,
		tags: ["power", "generator", "fixed"],
		barterValue: "GG3600",
		streetPrice: 29000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:generator-fixed-enormous",
		name: "Generator, Fixed, Enormous",
		weight: 6400,
		tags: ["power", "generator", "fixed"],
		barterValue: "GG16000",
		streetPrice: 125000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	// Portable Generators
	defineElectronicItem({
		id: "power:generator-portable-tiny",
		name: "Generator, Portable, Tiny",
		weight: 14,
		tags: ["power", "generator", "portable", "gasoline"],
		barterValue: "GG190",
		streetPrice: 760,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:generator-portable-small",
		name: "Generator, Portable, Small",
		weight: 84,
		tags: ["power", "generator", "portable", "gasoline"],
		barterValue: "GG500",
		streetPrice: 4000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:generator-portable-medium",
		name: "Generator, Portable, Medium",
		weight: 550,
		tags: ["power", "generator", "portable", "diesel"],
		barterValue: "GG2500",
		streetPrice: 8000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:vehicle-inverter",
		name: "Vehicle Inverter",
		weight: 0.4,
		tags: ["power", "inverter"],
		barterValue: "GG25",
		streetPrice: 50,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	// Alternate Power Sources
	defineElectronicItem({
		id: "power:bicycle-generator",
		name: "Bicycle Generator",
		weight: 4,
		tags: ["power", "generator", "renewable"],
		barterValue: "GG850",
		streetPrice: 850,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:hydro-generator",
		name: "Hydro Generator",
		weight: 25,
		tags: ["power", "generator", "renewable", "hydro"],
		barterValue: "GG1150",
		streetPrice: 2300,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:solar-cell",
		name: "Solar Cell",
		weight: 54,
		tags: ["power", "generator", "renewable", "solar"],
		barterValue: "GG1100",
		streetPrice: 2200,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:wind-turbine-small",
		name: "Wind Turbine, Small",
		weight: 6,
		tags: ["power", "generator", "renewable", "wind"],
		barterValue: "GG320",
		streetPrice: 640,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:wind-turbine-medium",
		name: "Wind Turbine, Medium",
		weight: 1100,
		tags: ["power", "generator", "renewable", "wind"],
		barterValue: "GG13000",
		streetPrice: 26000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:wind-turbine-large",
		name: "Wind Turbine, Large",
		weight: 14500,
		tags: ["power", "generator", "renewable", "wind"],
		barterValue: "GG120000",
		streetPrice: 240000,
		powered: true,
		powerRequirement: "see text",
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:wind-turbine-tower-20m",
		name: "Wind Turbine Tower, 20 m",
		weight: 2000,
		tags: ["power", "generator", "renewable", "wind", "tower"],
		barterValue: "GG4700",
		streetPrice: 9400,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:wind-turbine-tower-40m",
		name: "Wind Turbine Tower, 40 m",
		weight: 26500,
		tags: ["power", "generator", "renewable", "wind", "tower"],
		barterValue: "GG42500",
		streetPrice: 85000,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
];

export const STILLS: ItemDefinition[] = [
	defineElectronicItem({
		id: "power:still-small",
		name: "Still, Small",
		weight: 30,
		tags: ["power", "still"],
		barterValue: "GG140",
		streetPrice: 700,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:still-medium",
		name: "Still, Medium",
		weight: 150,
		tags: ["power", "still"],
		barterValue: "GG400",
		streetPrice: 2000,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:still-large",
		name: "Still, Large",
		weight: 1200,
		tags: ["power", "still"],
		barterValue: "GG3600",
		streetPrice: 18000,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
	defineElectronicItem({
		id: "power:still-industrial",
		name: "Still, Industrial",
		weight: 16000,
		tags: ["power", "still"],
		barterValue: "GG20000",
		streetPrice: 100000,
		powered: false,
		source: ["Source: Twilight 2013 Core OEF PDF p.233"],
	}),
];