import type { ItemDefinition } from "../types";
import { defineWeaponAttachment } from "./helpers";

export const RAIL_ACCESSORIES: ItemDefinition[] = [
  defineWeaponAttachment({
    id: "attachment:rail:laser-sight",
    name: "Laser Sight",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "laser"],
    weight: 0.1,
    barterValue: "GG75",
    streetPrice: 300,
    powerRequirement: "1 micro/24 hrs",
  }),
  defineWeaponAttachment({
    id: "attachment:rail:laser-sight-ir",
    name: "Laser Sight, IR",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "laser", "infrared"],
    weight: 0.1,
    barterValue: "GG150",
    streetPrice: 600,
    powerRequirement: "1 micro/24 hrs",
  }),
  defineWeaponAttachment({
    id: "attachment:rail:multi-light",
    name: "Multi-Light",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "light"],
    weight: 0.2,
    barterValue: "GG125",
    streetPrice: 500,
    powerRequirement: "2 sm/2 hrs",
  }),
  defineWeaponAttachment({
    id: "attachment:rail:vertical-foregrip",
    name: "Vertical Foregrip",
    kind: "rail-accessory",
    compatibleWeaponTags: ["smg", "shotgun", "rifle", "machine-gun"],
    tags: ["weapon-accessory", "rail-accessory", "foregrip"],
    weight: 0.1,
    barterValue: "GG2",
    streetPrice: 40,
  }),
  defineWeaponAttachment({
    id: "attachment:rail:weapon-light-small",
    name: "Weapon Light, Small",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "light"],
    weight: 0.1,
    barterValue: "GG25",
    streetPrice: 100,
    powerRequirement: "1 sm/1 hr",
  }),
  defineWeaponAttachment({
    id: "attachment:rail:weapon-light-large",
    name: "Weapon Light, Large",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "light"],
    weight: 0.2,
    barterValue: "GG50",
    streetPrice: 200,
    powerRequirement: "2 sm/1 hr",
  }),
  defineWeaponAttachment({
    id: "attachment:rail:weapon-light-ir-small",
    name: "Weapon Light, IR, Small",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "light", "infrared"],
    weight: 0.1,
    barterValue: "GG40",
    streetPrice: 150,
    powerRequirement: "1 sm/1 hr",
  }),
  defineWeaponAttachment({
    id: "attachment:rail:weapon-light-ir-large",
    name: "Weapon Light, IR, Large",
    kind: "rail-accessory",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "rail-accessory", "light", "infrared"],
    weight: 0.2,
    barterValue: "GG75",
    streetPrice: 300,
    powerRequirement: "2 sm/1 hr",
  }),
];

export const MISCELLANEOUS_ACCESSORIES: ItemDefinition[] = [
  defineWeaponAttachment({
    id: "attachment:support:bipod",
    name: "Bipod",
    kind: "bipod-accessory",
    compatibleWeaponTags: ["rifle", "machine-gun"],
    tags: ["weapon-accessory", "support-accessory", "bipod"],
    weight: 0.4,
    barterValue: "GG1.25",
    streetPrice: 50,
  }),
  defineWeaponAttachment({
    id: "attachment:stock:folding-stock",
    name: "Folding Stock",
    kind: "support-accessory",
    compatibleWeaponTags: ["smg", "rifle", "shotgun"],
    tags: ["weapon-accessory", "stock-accessory"],
    weight: 0,
    barterValue: "GG5",
    streetPrice: 100,
  }),
  defineWeaponAttachment({
    id: "attachment:sling:weapon-sling",
    name: "Weapon Sling",
    kind: "sling-accessory",
    compatibleWeaponTags: ["rifle", "shotgun", "smg", "machine-gun"],
    tags: ["weapon-accessory", "sling"],
    weight: 0.2,
    barterValue: "GG1",
    streetPrice: 40,
    grantsCarryProfiles: {
      slung: {
        voucherCost: { "worn:shoulder": 1 },
        description: "Attached host item may be carried slung without using the hands.",
      },
    },
    voucherBonus: { "worn:shoulder": 1 },
  }),
  defineWeaponAttachment({
    id: "attachment:support:tripod-light",
    name: "Tripod, Light",
    kind: "tripod-accessory",
    compatibleWeaponTags: ["machine-gun"],
    tags: ["weapon-accessory", "support-accessory", "tripod"],
    weight: 7,
    barterValue: "GG10",
    streetPrice: 200,
  }),
  defineWeaponAttachment({
    id: "attachment:support:tripod-medium",
    name: "Tripod, Medium",
    kind: "tripod-accessory",
    compatibleWeaponTags: ["machine-gun"],
    tags: ["weapon-accessory", "support-accessory", "tripod"],
    weight: 11,
    barterValue: "GG15",
    streetPrice: 300,
  }),
  defineWeaponAttachment({
    id: "attachment:support:tripod-heavy",
    name: "Tripod, Heavy",
    kind: "tripod-accessory",
    compatibleWeaponTags: ["machine-gun"],
    tags: ["weapon-accessory", "support-accessory", "tripod"],
    weight: 20,
    barterValue: "GG20",
    streetPrice: 400,
  }),
];

export const FIRE_CONTROL_MODIFICATIONS: ItemDefinition[] = [
  defineWeaponAttachment({
    id: "attachment:fire-control:civilian-legal-conversion",
    name: "Weapon Modification: Civilian-Legal variant",
    kind: "fire-control-modification",
    compatibleWeaponTags: ["smg", "assault-rifle"],
    tags: ["weapon-accessory", "fire-control-modification", "civilian-legal"],
    weight: 0,
    description: "Converts a military-pattern SMG or assault rifle into a civilian-legal semiautomatic variant.",
    notes: [
      "Use the printed street price and halve the barter value for the civilian-legal version.",
      "Remove all burst or automatic rates of fire.",
      "If the host weapon is an SMG with Bulk 2, increase Bulk to 3 to represent the legally mandated longer barrel.",
      "Civilian-legal variants can still share magazines and most parts with their military counterpart.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:fire-control:full-auto-conversion",
    name: "Weapon Modification: Full-Auto Conversion",
    kind: "fire-control-modification",
    compatibleWeaponTags: ["smg", "assault-rifle"],
    tags: ["weapon-accessory", "fire-control-modification", "illegal-modification"],
    weight: 0,
    description: "Illicit fire-control conversion for a civilian-pattern semiautomatic military arm.",
    notes: [
      "Requires 1 hour and a successful Mechanic/Machinist (CDN, TN -1) or Artisan: Gunsmith (CDN) check.",
      "On success, the host weapon gains the highest listed rate of fire used by its military counterpart.",
      "If the margin of success is less than 5, the weapon also gains 1 permanent Wear.",
    ],
  }),
];

export const SHOTGUN_MODIFICATIONS: ItemDefinition[] = [
  defineWeaponAttachment({
    id: "attachment:shotgun:remove-stock",
    name: "Shotgun Modification: Remove Stock",
    kind: "sawed-off-modification",
    compatibleWeaponTags: ["shotgun"],
    tags: ["weapon-accessory", "shotgun-modification"],
    weight: 0,
    speedModifier: "-1/-1/-2",
    recoilModifierPercent: 50,
    bulkOverride: 3,
    weightModifierPercent: -20,
    notes: ["Keeps the original range profile.", "Represents cutting or removing the stock from a full-length shotgun."],
  }),
  defineWeaponAttachment({
    id: "attachment:shotgun:shorten-barrel",
    name: "Shotgun Modification: Shorten Barrel",
    kind: "sawed-off-modification",
    compatibleWeaponTags: ["shotgun"],
    tags: ["weapon-accessory", "shotgun-modification"],
    weight: 0,
    range: "GF/CQB",
    speedModifier: "-1/-1/-2",
    recoilModifierPercent: 25,
    bulkOverride: 3,
    weightModifierPercent: -20,
    notes: ["Changes the shotgun to the reduced Gunfighting/CQB range profile."],
  }),
  defineWeaponAttachment({
    id: "attachment:shotgun:sawed-off-complete",
    name: "Shotgun Modification: Sawed-Off",
    kind: "sawed-off-modification",
    compatibleWeaponTags: ["shotgun"],
    tags: ["weapon-accessory", "shotgun-modification"],
    weight: 0,
    range: "GF/CQB",
    speedModifier: "-2/-2/-3",
    recoilModifierPercent: 75,
    bulkOverride: 2,
    weightModifierPercent: -40,
    notes: ["Combines stock removal and barrel shortening into a full sawed-off conversion."],
  }),
];