import type { ItemDefinition } from "../types";
import { defineWeaponAttachment } from "./helpers";

export const OPTICS: ItemDefinition[] = [
  defineWeaponAttachment({
    id: "attachment:optic:night-sight",
    name: "Night Sight",
    kind: "iron-sight-replacement",
    compatibleWeaponTags: ["handgun", "smg", "shotgun", "assault-rifle"],
    tags: ["weapon-accessory", "optic", "gunsight"],
    weight: 0,
    barterValue: "GG30",
    streetPrice: 150,
    description: "Luminous iron-sight replacement for low-light shooting.",
    notes: [
      "Reduces dim or minimal-light range penalties by up to 2.",
      "Does not require batteries.",
      "Can be combined with another gunsight, but benefits do not stack.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:night-vision",
    name: "Night-Vision Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "smg", "machine-gun"],
    tags: ["weapon-accessory", "optic", "night-vision", "gunsight"],
    weight: 0.9,
    barterValue: "GG375",
    streetPrice: 1500,
    powerRequirement: "4 sm/60 hrs",
    speedModifier: "0/1/1",
    description: "Weapon-mounted night-vision sight for longarms.",
    notes: [
      "Provides the same low-light aiming benefits as night sights for snap and aimed attacks.",
      "Benefits never apply to hip shots.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:night-vision-mag-1",
    name: "Night-Vision Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "smg", "machine-gun"],
    tags: ["weapon-accessory", "optic", "night-vision", "gunsight"],
    traits: ["Mag-1"],
    weight: 1.4,
    barterValue: "GG500",
    streetPrice: 2000,
    powerRequirement: "4 sm/60 hrs",
    speedModifier: "0/2/2",
    visualRangeModifier: 1,
    description: "Night-vision sight with built-in low magnification.",
    notes: [
      "Provides the same low-light aiming benefits as night sights for snap and aimed attacks.",
      "Benefits never apply to hip shots.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:reflex-powered",
    name: "Reflex Sight, Powered",
    kind: "reflex-optic",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "optic", "reflex", "gunsight"],
    weight: 0.3,
    barterValue: "GG100",
    streetPrice: 400,
    powerRequirement: "2 sm/1 yr",
    speedModifier: "0/-1/-1",
    accuracyModifier: { snap: 2 },
    description: "Powered red-dot style reflex sight.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "Any firearm can accept a reflex sight; autoloaders may require a special bracket.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:reflex-unpowered",
    name: "Reflex Sight, Unpowered",
    kind: "reflex-optic",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "optic", "reflex", "gunsight"],
    weight: 0.2,
    barterValue: "GG500",
    streetPrice: 1000,
    speedModifier: "0/-1/-1",
    accuracyModifier: { snap: 2 },
    description: "Prism-based reflex sight that works in minimal through excessive lighting conditions.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "Any firearm can accept a reflex sight; autoloaders may require a special bracket.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:reflex-powered-mag-1",
    name: "Reflex Sight, Powered",
    kind: "reflex-optic",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "optic", "reflex", "gunsight"],
    traits: ["Mag-1"],
    weight: 0.3,
    barterValue: "GG150",
    streetPrice: 600,
    powerRequirement: "2 sm/1 yr",
    accuracyModifier: { snap: 2 },
    visualRangeModifier: 1,
    description: "Low-magnification powered reflex sight.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "Provides a +2 bonus to snap attacks and increases effective visual range by one band for snap and aimed attacks.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:reflex-unpowered-mag-1",
    name: "Reflex Sight, Unpowered",
    kind: "reflex-optic",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "optic", "reflex", "gunsight"],
    traits: ["Mag-1"],
    weight: 0.2,
    barterValue: "GG750",
    streetPrice: 1500,
    accuracyModifier: { snap: 2 },
    visualRangeModifier: 1,
    description: "Low-magnification prism reflex sight.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "Provides a +2 bonus to snap attacks and increases effective visual range by one band for snap and aimed attacks.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:reflex-magnifier",
    name: "Reflex Sight Magnifier",
    kind: "magnified-optic",
    compatibleWeaponTags: ["firearm"],
    tags: ["weapon-accessory", "optic", "reflex", "magnifier"],
    weight: 0.1,
    barterValue: "GG600",
    streetPrice: 800,
    speedModifier: "0/1/1",
    visualRangeModifier: 1,
    description: "Clip-on low magnifier for a reflex sight.",
    notes: ["Pairs with a reflex sight to extend effective visual range by one band for snap and aimed attacks."],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:telescopic-mag-1",
    name: "Telescopic Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "machine-gun"],
    tags: ["weapon-accessory", "optic", "telescopic", "gunsight"],
    traits: ["Mag-1"],
    weight: 0.3,
    barterValue: "GG75",
    streetPrice: 150,
    speedModifier: "0/1/1",
    visualRangeModifier: 1,
    description: "Low-power telescopic sight.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "At very close range the optic is too slow for meaningful observation and attacks using it may fail automatically.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:telescopic-mag-2",
    name: "Telescopic Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "machine-gun"],
    tags: ["weapon-accessory", "optic", "telescopic", "gunsight"],
    traits: ["Mag-2"],
    weight: 0.4,
    barterValue: "GG175",
    streetPrice: 350,
    speedModifier: "0/2/2",
    visualRangeModifier: 2,
    description: "Medium-power telescopic sight.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "At very close range the optic is too slow for meaningful observation and attacks using it may fail automatically.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:telescopic-mag-3",
    name: "Telescopic Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "machine-gun"],
    tags: ["weapon-accessory", "optic", "telescopic", "gunsight"],
    traits: ["Mag-3"],
    weight: 0.5,
    barterValue: "GG225",
    streetPrice: 450,
    speedModifier: "0/3/3",
    visualRangeModifier: 3,
    description: "High-power telescopic sight.",
    notes: [
      "Benefits apply to snap and aimed attacks only.",
      "At very close range the optic is too slow for meaningful observation and attacks using it may fail automatically.",
    ],
  }),
  defineWeaponAttachment({
    id: "attachment:optic:thermal",
    name: "Thermal Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "machine-gun"],
    tags: ["weapon-accessory", "optic", "thermal", "gunsight"],
    weight: 1.4,
    barterValue: "GG3,000",
    streetPrice: 12000,
    powerRequirement: "2 med/8 hrs",
    description: "Thermal imaging gunsight.",
  }),
  defineWeaponAttachment({
    id: "attachment:optic:thermal-mag-1",
    name: "Thermal Sight",
    kind: "magnified-optic",
    compatibleWeaponTags: ["rifle", "shotgun", "machine-gun"],
    tags: ["weapon-accessory", "optic", "thermal", "gunsight"],
    traits: ["Mag-1"],
    weight: 1.5,
    barterValue: "GG3,250",
    streetPrice: 13000,
    powerRequirement: "2 med/8 hrs",
    visualRangeModifier: 1,
    description: "Thermal imaging gunsight with low magnification.",
  }),
];