import { createItemDefinition } from "./inventory";
import type { ItemDefinition } from "./types";

type CloseCombatCategory =
  | "blunt-implement"
  | "sharp-thing"
  | "pepper-spray"
  | "improvised-weapon"
  | "thrown-weapon";

type CloseCombatRow = {
  id: string;
  name: string;
  category: CloseCombatCategory;
  damage: number | string;
  penetration: string;
  speed: string;
  bulk: number;
  weight: number;
  barterValue?: string;
  streetPrice?: number;
  voucherCost?: Record<string, number>;
  tags?: string[];
  description?: string;
  notes?: string[];
};

export const CLOSE_COMBAT_WEAPON_RULES = {
  designNote: [
    "Selections focus on practical close-combat tools and common emergency weapons rather than fantasy-style arsenals.",
    "A machete or hatchet is small enough to carry as a secondary weapon, while many larger polearms are intentionally omitted.",
    "When firearms are available, most users will not voluntarily choose extended melee exchanges against them.",
  ],
  specialCases: {
    batonTelescoping: "When collapsed, a telescoping baton performs like a sap. Ready it as a Novice Hand Weapons action to extend it.",
    bayonet: "A bayonet can be attached to a crude or service rifle for use as an attached melee weapon while the firearm still functions normally.",
    knifeWorking: "A working knife covers common 12-24 cm blades, including kitchen, survival, and fighting knives. Balanced-for-throwing versions use the thrown-weapon entry.",
    pepperSpray: [
      "A successful pepper spray attack inflicts no damage but doses the victim with one dose of pepper spray.",
      "A direct hit to the head inflicts an additional -2 penalty on the victim's Resolve check.",
      "Pepper spray can be used against targets in the Gunfighting range band at a -4 penalty.",
    ],
    improvisedWeapons: "Improvised weapons are grouped by size and whether they primarily crush or penetrate. They are assumed to be free unless the scenario says otherwise.",
  },
} as const;

function createCombatProfileNote(row: CloseCombatRow): string {
  return `Combat profile: Damage ${row.damage}, Penetration ${row.penetration}, Speed ${row.speed}, Bulk ${row.bulk}.`;
}

function createCloseCombatWeapon(row: CloseCombatRow): ItemDefinition {
  return createItemDefinition({
    id: row.id,
    name: row.name,
    weight: row.weight,
    tags: ["weapon", "close-combat-weapon", row.category, ...(row.tags ?? [])],
    barterValue: row.barterValue,
    streetPrice: row.streetPrice,
    voucherCost: row.voucherCost,
    description: row.description,
    source: [createCombatProfileNote(row), ...(row.notes ?? [])],
  });
}

export const BLUNT_IMPLEMENTS: ItemDefinition[] = [
  createCloseCombatWeapon({
    id: "weapon:close-combat:brass-knuckles",
    name: "Brass Knuckles",
    category: "blunt-implement",
    damage: 2,
    penetration: "x4",
    speed: "1/2/4",
    bulk: 0,
    weight: 0.1,
    barterValue: "GG2.5",
    streetPrice: 25,
    voucherCost: { "worn:hands": 1 },
    tags: ["one-handed"],
    description: "Weighted striking implement worn over the hand.",
    notes: ["Use the knuckles' traits rather than bare-hand traits when making hand-to-hand attacks."],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:sap-blackjack",
    name: "Sap / Blackjack",
    category: "blunt-implement",
    damage: 2,
    penetration: "x4",
    speed: "1/2/4",
    bulk: 1,
    weight: 0.2,
    barterValue: "GG0.3",
    streetPrice: 30,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:baton-club",
    name: "Baton / Club",
    category: "blunt-implement",
    damage: 3,
    penetration: "x4",
    speed: "2/3/5",
    bulk: 2,
    weight: 0.4,
    barterValue: "GG0.4",
    streetPrice: 40,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:baton-telescoping",
    name: "Baton, Telescoping",
    category: "blunt-implement",
    damage: 3,
    penetration: "x4",
    speed: "2/3/5",
    bulk: 2,
    weight: 0.5,
    barterValue: "GG0.5",
    streetPrice: 50,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "collapsible"],
    notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.batonTelescoping],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:hammer",
    name: "Hammer",
    category: "blunt-implement",
    damage: 4,
    penetration: "x3",
    speed: "2/3/5",
    bulk: 2,
    weight: 0.6,
    barterValue: "GG0.6",
    streetPrice: 30,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "tool"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:bat",
    name: "Bat",
    category: "blunt-implement",
    damage: 5,
    penetration: "x4",
    speed: "3/5/7",
    bulk: 3,
    weight: 1,
    barterValue: "GG0.2",
    streetPrice: 20,
    voucherCost: { "held:hands": 2 },
    tags: ["two-handed", "sporting-goods"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:sledgehammer",
    name: "Sledgehammer",
    category: "blunt-implement",
    damage: 8,
    penetration: "x4",
    speed: "6/9/14",
    bulk: 5,
    weight: 5,
    barterValue: "GG0.7",
    streetPrice: 35,
    voucherCost: { "held:hands": 2 },
    tags: ["two-handed", "tool"],
  }),
];

export const SHARP_THINGS: ItemDefinition[] = [
  createCloseCombatWeapon({
    id: "weapon:close-combat:knife-folding",
    name: "Knife, Folding",
    category: "sharp-thing",
    damage: 2,
    penetration: "x2",
    speed: "1/2/4",
    bulk: 1,
    weight: 0.2,
    barterValue: "GG0.8",
    streetPrice: 40,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "knife"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:knife-working",
    name: "Knife, Working",
    category: "sharp-thing",
    damage: 3,
    penetration: "x1",
    speed: "1/2/4",
    bulk: 1,
    weight: 0.5,
    barterValue: "GG1.2",
    streetPrice: 60,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "knife", "tool"],
    notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.knifeWorking],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:machete",
    name: "Machete",
    category: "sharp-thing",
    damage: 3,
    penetration: "x2",
    speed: "2/3/5",
    bulk: 2,
    weight: 0.7,
    barterValue: "GG1",
    streetPrice: 50,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "tool"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:sword-stabbing",
    name: "Sword, Stabbing",
    category: "sharp-thing",
    damage: 4,
    penetration: "x1",
    speed: "2/3/5",
    bulk: 2,
    weight: 1.4,
    barterValue: "GG5",
    streetPrice: 250,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "sword"],
    description: "One-handed fighting blade designed primarily for straight thrusts.",
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:sword-slashing",
    name: "Sword, Slashing",
    category: "sharp-thing",
    damage: 5,
    penetration: "x2",
    speed: "3/5/7",
    bulk: 3,
    weight: 1.7,
    barterValue: "GG5",
    streetPrice: 250,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "sword"],
    description: "One-handed fighting blade designed primarily for forcing cuts.",
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:hatchet",
    name: "Hatchet",
    category: "sharp-thing",
    damage: 5,
    penetration: "x3",
    speed: "2/3/5",
    bulk: 2,
    weight: 0.4,
    barterValue: "GG0.6",
    streetPrice: 30,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "tool"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:axe",
    name: "Axe",
    category: "sharp-thing",
    damage: 9,
    penetration: "x3",
    speed: "5/8/11",
    bulk: 4,
    weight: 2.7,
    barterValue: "GG0.6",
    streetPrice: 30,
    voucherCost: { "held:hands": 2 },
    tags: ["two-handed", "tool"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:bayonet-bulk-3-rifle",
    name: "Bayonet (Bulk 3 Rifle)",
    category: "sharp-thing",
    damage: 4,
    penetration: "x1",
    speed: "3/5/7",
    bulk: 3,
    weight: 0.5,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "knife", "bayonet"],
    description: "Bayonet profile when mounted on a Bulk 3 rifle or used as a crude spear.",
    notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.bayonet],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:bayonet-bulk-4-rifle",
    name: "Bayonet (Bulk 4 Rifle)",
    category: "sharp-thing",
    damage: 5,
    penetration: "x1",
    speed: "4/6/9",
    bulk: 4,
    weight: 0.5,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "knife", "bayonet"],
    description: "Bayonet profile when mounted on a Bulk 4 rifle or longer arm.",
    notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.bayonet],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:short-spear",
    name: "Short Spear",
    category: "sharp-thing",
    damage: 5,
    penetration: "x2",
    speed: "4/6/9",
    bulk: 4,
    weight: 0.7,
    barterValue: "GG0.2",
    voucherCost: { "held:hands": 2 },
    tags: ["two-handed", "spear"],
    description: "Well-balanced hunting or defensive spear between 1 and 1.5 meters long.",
  }),
];

export const PEPPER_SPRAY_CANISTERS: ItemDefinition[] = [
  createCloseCombatWeapon({
    id: "weapon:close-combat:pepper-spray-keychain",
    name: "Pepper Spray, Keychain",
    category: "pepper-spray",
    damage: "see text",
    penetration: "-",
    speed: "1/2/4",
    bulk: 0,
    weight: 0,
    barterValue: "GG3",
    streetPrice: 15,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "chemical-irritant"],
    notes: [...CLOSE_COMBAT_WEAPON_RULES.specialCases.pepperSpray, "Holds 10 doses."],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:pepper-spray-police",
    name: "Pepper Spray, Police",
    category: "pepper-spray",
    damage: "see text",
    penetration: "-",
    speed: "1/2/4",
    bulk: 1,
    weight: 0.1,
    barterValue: "GG5",
    streetPrice: 25,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "chemical-irritant"],
    notes: [...CLOSE_COMBAT_WEAPON_RULES.specialCases.pepperSpray, "Holds 10 doses."],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:pepper-spray-institutional",
    name: "Pepper Spray, Institutional",
    category: "pepper-spray",
    damage: "see text",
    penetration: "-",
    speed: "2/3/5",
    bulk: 2,
    weight: 0.3,
    barterValue: "GG10",
    streetPrice: 50,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "chemical-irritant"],
    notes: [...CLOSE_COMBAT_WEAPON_RULES.specialCases.pepperSpray, "Holds 30 doses."],
  }),
];

export const IMPROVISED_WEAPONS: ItemDefinition[] = [
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:blunt-tiny", name: "Blunt, Tiny", category: "improvised-weapon", damage: 2, penetration: "x4", speed: "2/3/5", bulk: 1, weight: 0.5, voucherCost: { "held:hands": 1 }, tags: ["one-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:blunt-small", name: "Blunt, Small", category: "improvised-weapon", damage: 3, penetration: "x4", speed: "3/5/7", bulk: 2, weight: 1.5, voucherCost: { "held:hands": 1 }, tags: ["one-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:blunt-medium", name: "Blunt, Medium", category: "improvised-weapon", damage: 5, penetration: "x4", speed: "4/6/9", bulk: 3, weight: 3, voucherCost: { "held:hands": 2 }, tags: ["two-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:blunt-large", name: "Blunt, Large", category: "improvised-weapon", damage: 7, penetration: "x4", speed: "5/8/11", bulk: 4, weight: 5, voucherCost: { "held:hands": 2 }, tags: ["two-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:sharp-tiny", name: "Sharp, Tiny", category: "improvised-weapon", damage: 2, penetration: "x2", speed: "2/3/5", bulk: 1, weight: 0.2, voucherCost: { "held:hands": 1 }, tags: ["one-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:sharp-small", name: "Sharp, Small", category: "improvised-weapon", damage: 3, penetration: "x2", speed: "3/5/7", bulk: 2, weight: 0.5, voucherCost: { "held:hands": 1 }, tags: ["one-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:sharp-medium", name: "Sharp, Medium", category: "improvised-weapon", damage: 4, penetration: "x3", speed: "4/6/9", bulk: 3, weight: 2, voucherCost: { "held:hands": 2 }, tags: ["two-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
  createCloseCombatWeapon({ id: "weapon:close-combat:improvised:sharp-large", name: "Sharp, Large", category: "improvised-weapon", damage: 5, penetration: "x3", speed: "5/8/11", bulk: 4, weight: 3, voucherCost: { "held:hands": 2 }, tags: ["two-handed", "improvised"], notes: [CLOSE_COMBAT_WEAPON_RULES.specialCases.improvisedWeapons] }),
];

export const THROWN_WEAPONS: ItemDefinition[] = [
  createCloseCombatWeapon({
    id: "weapon:close-combat:thrown-dart",
    name: "Dart, Throwing",
    category: "thrown-weapon",
    damage: 1,
    penetration: "x3",
    speed: "1/2/4",
    bulk: 0,
    weight: 0.1,
    barterValue: "GG0.8",
    streetPrice: 40,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "thrown"],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:thrown-working-knife",
    name: "Knife, Working (Thrown)",
    category: "thrown-weapon",
    damage: 2,
    penetration: "x2",
    speed: "1/2/4",
    bulk: 1,
    weight: 0.5,
    barterValue: "GG1.6",
    streetPrice: 80,
    voucherCost: { "held:hands": 1 },
    tags: ["one-handed", "thrown", "knife"],
    notes: ["Balanced throwing variant of the working knife entry."],
  }),
  createCloseCombatWeapon({
    id: "weapon:close-combat:thrown-short-spear",
    name: "Short Spear (Thrown)",
    category: "thrown-weapon",
    damage: 4,
    penetration: "x2",
    speed: "4/6/9",
    bulk: 4,
    weight: 0.7,
    barterValue: "GG0.2",
    voucherCost: { "held:hands": 2 },
    tags: ["two-handed", "thrown", "spear"],
  }),
];

export const CLOSE_COMBAT_WEAPONS: ItemDefinition[] = [
  ...BLUNT_IMPLEMENTS,
  ...SHARP_THINGS,
  ...PEPPER_SPRAY_CANISTERS,
  ...IMPROVISED_WEAPONS,
  ...THROWN_WEAPONS,
];