import { createItemDefinition } from "./inventory";
import type { ItemDefinition } from "./types";

export const CIVILIAN_CLOTHING: ItemDefinition[] = [
  createItemDefinition({
    id: "clothing:civilian:outfit-extreme-hot",
    name: "Outfit, Extreme Hot Weather",
    weight: 0.8,
    tags: ["clothing", "civilian", "outfit", "hot-weather"],
    barterValue: "GG5",
    streetPrice: 100,
    voucherCost: { "worn:torso": 1 },
    description: "Light civilian outfit suitable for extreme heat, including basic undergarments and climate-appropriate garments.",
  }),
  createItemDefinition({
    id: "clothing:civilian:outfit-hot",
    name: "Outfit, Hot Weather",
    weight: 0.9,
    tags: ["clothing", "civilian", "outfit", "hot-weather"],
    barterValue: "GG3.25",
    streetPrice: 65,
    voucherCost: { "worn:torso": 1 },
    description: "Civilian outfit intended for hot climates.",
  }),
  createItemDefinition({
    id: "clothing:civilian:outfit-mild",
    name: "Outfit, Mild Weather",
    weight: 1.3,
    tags: ["clothing", "civilian", "outfit", "mild-weather"],
    barterValue: "GG4.5",
    streetPrice: 90,
    voucherCost: { "worn:torso": 1 },
    description: "Everyday civilian outfit for mild temperatures.",
  }),
  createItemDefinition({
    id: "clothing:civilian:outfit-cold",
    name: "Outfit, Cold Weather",
    weight: 2.8,
    tags: ["clothing", "civilian", "outfit", "cold-weather"],
    barterValue: "GG15",
    streetPrice: 300,
    voucherCost: { "worn:torso": 1 },
    description: "Layered civilian cold-weather outfit with thermal underlayers.",
  }),
  createItemDefinition({
    id: "clothing:civilian:outerwear-cold",
    name: "Outerwear, Cold Weather",
    weight: 1,
    tags: ["clothing", "civilian", "outerwear", "cold-weather"],
    barterValue: "GG10",
    streetPrice: 200,
    voucherCost: { "worn:torso": 1 },
    description: "Insulated jacket, hat, and boots for extended exposure below mild temperatures.",
  }),
  createItemDefinition({
    id: "clothing:civilian:outerwear-extreme-cold",
    name: "Outerwear, Extreme Cold Weather",
    weight: 1.7,
    tags: ["clothing", "civilian", "outerwear", "extreme-cold-weather"],
    barterValue: "GG32.5",
    streetPrice: 650,
    voucherCost: { "worn:torso": 1 },
    description: "Heavy parka ensemble with insulated overboots and pants for extreme cold.",
  }),
  createItemDefinition({
    id: "clothing:civilian:rain-gear",
    name: "Rain Gear",
    weight: 1.2,
    tags: ["clothing", "civilian", "outerwear", "rain-gear"],
    barterValue: "GG6.25",
    streetPrice: 125,
    voucherCost: { "worn:torso": 1 },
    description: "Waterproof jacket and pants intended to be worn over a base layer.",
  }),
  createItemDefinition({
    id: "clothing:civilian:shoes-casual",
    name: "Shoes, Casual",
    weight: 1,
    tags: ["clothing", "civilian", "footwear", "shoes"],
    barterValue: "GG1.25",
    streetPrice: 50,
    voucherCost: { "worn:feet": 2 },
    description: "Common everyday footwear with no special game effects.",
  }),
  createItemDefinition({
    id: "clothing:civilian:shoes-running",
    name: "Shoes, Running",
    weight: 0.7,
    tags: ["clothing", "civilian", "footwear", "shoes", "running"],
    barterValue: "GG2",
    streetPrice: 80,
    voucherCost: { "worn:feet": 2 },
    description: "Light running shoes.",
    traits: ["sprint-bonus-1m"],
  }),
  createItemDefinition({
    id: "clothing:civilian:boots-hiking",
    name: "Boots, Hiking",
    weight: 1.7,
    tags: ["clothing", "civilian", "footwear", "boots", "hiking"],
    barterValue: "GG7.5",
    streetPrice: 150,
    voucherCost: { "worn:feet": 2 },
    description: "Durable hiking boots for rough outdoor travel.",
  }),
  createItemDefinition({
    id: "clothing:civilian:boots-winter",
    name: "Boots, Winter",
    weight: 2.4,
    tags: ["clothing", "civilian", "footwear", "boots", "winter"],
    barterValue: "GG7.5",
    streetPrice: 150,
    voucherCost: { "worn:feet": 2 },
    description: "Insulated boots intended for cold-weather conditions.",
  }),
  createItemDefinition({
    id: "clothing:civilian:boots-work",
    name: "Boots, Work",
    weight: 2.3,
    tags: ["clothing", "civilian", "footwear", "boots", "work"],
    barterValue: "GG6",
    streetPrice: 120,
    voucherCost: { "worn:feet": 2 },
    description: "Heavy work boots.",
    traits: ["foot-hit-armor-1-25pct"],
  }),
];

export const MILITARY_CLOTHING: ItemDefinition[] = [
  createItemDefinition({
    id: "clothing:military:fatigues-hot",
    name: "Fatigues, Hot Weather",
    weight: 1.2,
    tags: ["clothing", "military", "uniform", "fatigues", "hot-weather"],
    barterValue: "GG7.5",
    streetPrice: 150,
    voucherCost: { "worn:torso": 1 },
    description: "Military fatigue uniform for hot climates.",
  }),
  createItemDefinition({
    id: "clothing:military:fatigues-mild",
    name: "Fatigues, Mild Weather",
    weight: 1.2,
    tags: ["clothing", "military", "uniform", "fatigues", "mild-weather"],
    barterValue: "GG6",
    streetPrice: 120,
    voucherCost: { "worn:torso": 1 },
    description: "Standard working or combat uniform for temperate conditions.",
  }),
  createItemDefinition({
    id: "clothing:military:fatigues-cold",
    name: "Fatigues, Cold Weather",
    weight: 1.4,
    tags: ["clothing", "military", "uniform", "fatigues", "cold-weather"],
    barterValue: "GG9",
    streetPrice: 180,
    voucherCost: { "worn:torso": 1 },
    //TODO: vouchers not correct; this is an ensemble. other entries have same problem
    description: "Military fatigue ensemble with additional cold-weather layers.",
  }),
  createItemDefinition({
    id: "clothing:military:flight-suit",
    name: "Flight Suit",
    weight: 1.4,
    tags: ["clothing", "military", "uniform", "flight-suit", "coveralls"],
    barterValue: "GG11",
    streetPrice: 220,
    voucherCost: { "worn:torso": 1 },
    description: "One-piece garment worn by aviators, mechanics, and vehicle crews.",
  }),
  createItemDefinition({
    id: "clothing:military:overwhites-cold",
    name: "Overwhites, Cold Weather",
    weight: 0.8,
    tags: ["clothing", "military", "outerwear", "overwhites", "cold-weather", "camouflage"],
    barterValue: "GG6.75",
    streetPrice: 135,
    voucherCost: { "worn:torso": 1 },
    description: "Cold-weather camouflage outerwear meant to fit over fatigues and armor.",
  }),
  createItemDefinition({
    id: "clothing:military:overwhites-extreme-cold",
    name: "Overwhites, Extreme Cold Weather",
    weight: 1.4,
    tags: ["clothing", "military", "outerwear", "overwhites", "extreme-cold-weather", "camouflage"],
    barterValue: "GG28.5",
    streetPrice: 570,
    voucherCost: { "worn:torso": 1 },
    description: "Heavier arctic overwhites worn over fatigues and body armor.",
  }),
  createItemDefinition({
    id: "clothing:military:combat-boots",
    name: "Combat Boots",
    weight: 2,
    tags: ["clothing", "military", "footwear", "boots", "combat-boots"],
    barterValue: "GG5",
    streetPrice: 100,
    voucherCost: { "worn:feet": 2 },
    description: "Standard leather military combat boots.",
  }),
  createItemDefinition({
    id: "clothing:military:combat-boots-desert",
    name: "Combat Boots, Desert",
    weight: 1.8,
    tags: ["clothing", "military", "footwear", "boots", "combat-boots", "desert"],
    barterValue: "GG6",
    streetPrice: 120,
    voucherCost: { "worn:feet": 2 },
    description: "Combat boots optimized for hotter climates.",
  }),
  createItemDefinition({
    id: "clothing:military:combat-boots-winter",
    name: "Combat Boots, Winter",
    weight: 2.2,
    tags: ["clothing", "military", "footwear", "boots", "combat-boots", "winter"],
    barterValue: "GG8",
    streetPrice: 160,
    voucherCost: { "worn:feet": 2 },
    description: "Combat boots intended for cold-weather operations.",
  }),
];

export const CLOTHING_CATALOG: ItemDefinition[] = [
  ...CIVILIAN_CLOTHING,
  ...MILITARY_CLOTHING,
];