import { createContainerDefinition } from "./inventory";
import type { ContainerDefinition, ContainerDefinitionInit, VoucherPool } from "./types";

type PortableContainerDefinition = ContainerDefinitionInit & {
  id: string;
  name: string;
  weight: number;
};

function defineContainer(input: PortableContainerDefinition): ContainerDefinition {
  return createContainerDefinition(input);
}

function createItemRule(key: string, acceptedItemTags: string[], unitsPerItem = 1) {
  return { key, acceptedItemTags, unitsPerItem };
}

function createContainerRule(key: string, acceptedContainerTags: string[], unitsPerContainer = 1) {
  return { key, acceptedContainerTags, unitsPerContainer };
}

function defineAttachmentContainer(
  input: PortableContainerDefinition & {
    attachmentPointCost?: number;
    beltComponent?: boolean;
  },
): ContainerDefinition {
  const voucherCost: VoucherPool = {
    ...(input.voucherCost ?? {}),
    ...(input.attachmentPointCost !== undefined ? { "mlbe:ap": input.attachmentPointCost } : {}),
    ...(input.attachmentPointCost === undefined
      ? (input.beltComponent ? { "lbe:component": 1, "lbe:belt-component": 1 } : { "lbe:component": 1 })
      : {}),
  };

  return defineContainer({
    ...input,
    attachmentPointCost: input.attachmentPointCost,
    voucherCost,
  });
}
//TODO: capacity weight is used for Liters AND kilogram carrying capacities.
// Need to figure out how to handle this better, since it's confusing to have a weight capacity that isn't actually a weight. 
// Maybe need to add a separate "capacityVolume" stat or something like that, 
// and then have some way of indicating whether the "capacityWeight" is actually a weight or a volume?
export const PACK_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:pack:frame-civilian",
    name: "Frame Pack, Civilian",
    weight: 2.7,
    capacityWeight: 80,
    tags: ["container", "pack", "frame-pack"],
    barterValue: "GG8.75",
    streetPrice: 175,
    voucherCost: { "worn:back": 1 },
    description: "80-liter civilian frame backpack with a lightweight frame and accessory attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:frame-high-capacity",
    name: "Frame Pack, High-Capacity",
    weight: 4,
    capacityWeight: 125,
    tags: ["container", "pack", "frame-pack"],
    barterValue: "GG15",
    streetPrice: 300,
    voucherCost: { "worn:back": 1 },
    description: "Large expedition frame pack with about 125 liters of capacity.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:frame-military",
    name: "Frame Pack, Military",
    weight: 3,
    tags: ["container", "pack", "frame-pack", "military"],
    barterValue: "GG5",
    streetPrice: 100,
    voucherCost: { "worn:back": 1 },
    description: "Rugged military frame pack with subdued colors and field-oriented construction.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:rucksack-civilian",
    name: "Rucksack, Civilian",
    weight: 1.3,
    capacityWeight: 40,
    tags: ["container", "pack", "rucksack"],
    barterValue: "GG2.5",
    streetPrice: 50,
    voucherCost: { "worn:back": 1 },
    description: "Simple 40-liter backpack with basic ergonomic support.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:waist-pack",
    name: "Waist Pack",
    weight: 0.2,
    tags: ["container", "pack", "waist-pack"],
    barterValue: "GG0.5",
    streetPrice: 20,
    voucherCost: { "worn:waist": 1 },
    description: "Small zippered pouch with an integral belt for waist carry.",
    defaultMode: "bag",
  }),
];

export const FIXED_LOAD_BEARING_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:lbe:basic-belt-and-yoke",
    name: "Basic Belt and Yoke",
    weight: 1,
    tags: ["container", "load-bearing-equipment", "fixed-lbe"],
    barterValue: "GG20",
    streetPrice: 200,
    voucherCost: { "worn:torso": 1 },
    voucherLimits: { "lbe:component": 10, "lbe:belt-component": 4 },
    description: "Fixed load-bearing harness for up to 10 components, of which no more than 4 may be belt components.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:lbe:tactical-vest",
    name: "Tactical Vest",
    weight: 1.3,
    tags: ["container", "load-bearing-equipment", "fixed-lbe", "vest"],
    barterValue: "GG20",
    streetPrice: 200,
    voucherCost: { "worn:torso": 1 },
    voucherLimits: { "lbe:component": 10, "lbe:belt-component": 4 },
    description: "Fixed tactical vest for up to 10 attached LBE components, with no more than 4 designated as belt components.",
    defaultMode: "bag",
  }),
];

export const FIXED_LBE_COMPONENT_CONTAINERS: ContainerDefinition[] = [
  defineAttachmentContainer({
    id: "container:lbe:cartridge-loop",
    name: "Cartridge Loop",
    weight: 0,
    tags: ["container", "load-bearing-component", "ammo-storage"],
    description: "Fixed LBE component sized for 10 rifle shells.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:holster",
    name: "Holster",
    weight: 0.2,
    tags: ["container", "load-bearing-component", "holster"],
    itemVoucherRules: [{ key: "stowed:handgun", acceptedItemTags: ["handgun"] }],
    voucherLimits: { "stowed:handgun": 1 },
    description: "Fixed LBE holster sized for 1 handgun.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:grenade-loop",
    name: "Grenade Loop",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "grenade-carriage"],
    description: "Fixed LBE component sized for 1 hand or launcher grenade.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:mag-carrier-rifle-double",
    name: "Mag Carrier, Rifle, Double",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "magazine-carrier"],
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 2 },
    description: "Fixed LBE component sized for 2 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:mag-carrier-pistol-triple",
    name: "Mag Carrier, Pistol, Triple",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "magazine-carrier"],
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 3 },
    description: "Fixed LBE component sized for 3 handgun magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:radio-pouch",
    name: "Radio Pouch",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "radio-pouch"],
    itemVoucherRules: [createItemRule("stowed:radio", ["radio"])],
    voucherLimits: { "stowed:radio": 1 },
    description: "Fixed LBE component sized for 1 radio or similarly sized device.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:sheath",
    name: "Sheath",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "sheath"],
    itemVoucherRules: [createItemRule("stowed:knife", ["knife"])],
    voucherLimits: { "stowed:knife": 1 },
    description: "Fixed LBE component sized for 1 knife.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:shell-loop",
    name: "Shell Loop",
    weight: 0,
    tags: ["container", "load-bearing-component", "ammo-storage"],
    description: "Fixed LBE component sized for 5 shotgun shells.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:canteen-carrier",
    name: "Canteen Carrier",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "canteen-carrier"],
    containerVoucherRules: [createContainerRule("stowed:canteen", ["water-container"])],
    voucherLimits: { "stowed:canteen": 1 },
    description: "Belt-mounted fixed LBE component sized for 1 canteen.",
    beltComponent: true,
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:mag-carrier-rifle-quad",
    name: "Mag Carrier, Rifle, Quad",
    weight: 0.2,
    tags: ["container", "load-bearing-component", "magazine-carrier"],
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 4 },
    description: "Belt-mounted fixed LBE component sized for 4 rifle magazines.",
    beltComponent: true,
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:shell-carrier",
    name: "Shell Carrier",
    weight: 0.1,
    tags: ["container", "load-bearing-component", "ammo-storage"],
    description: "Belt-mounted fixed LBE component sized for 36 shotgun shells.",
    beltComponent: true,
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:lbe:utility-pouch",
    name: "Utility Pouch",
    weight: 0.2,
    tags: ["container", "load-bearing-component", "utility-pouch"],
    description: "Belt-mounted fixed LBE utility pouch with roughly 12 x 18 x 8 cm of internal space.",
    beltComponent: true,
    defaultMode: "bag",
  }),
];

export const MODULAR_LOAD_BEARING_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:mlbe:fighting-load-carrier",
    name: "Fighting Load Carrier",
    weight: 1,
    tags: ["container", "load-bearing-equipment", "mlbe"],
    barterValue: "GG100",
    streetPrice: 200,
    voucherCost: { "worn:torso": 1 },
    voucherLimits: { "mlbe:ap": 46 },
    description: "Modular load-bearing vest with 30 front and 16 rear attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-patrol",
    name: "Pack, Patrol",
    weight: 1.5,
    tags: ["container", "load-bearing-equipment", "mlbe", "pack"],
    barterValue: "GG100",
    streetPrice: 200,
    voucherCost: { "worn:back": 1 },
    voucherLimits: { "mlbe:ap": 17 },
    description: "Small modular patrol pack with 17 external attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-field",
    name: "Pack, Field",
    weight: 2,
    tags: ["container", "load-bearing-equipment", "mlbe", "pack"],
    barterValue: "GG87.5",
    streetPrice: 175,
    voucherCost: { "worn:back": 1 },
    voucherLimits: { "mlbe:ap": 24 },
    description: "Field pack with 24 attachment points and volume comparable to a 3-day pack.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-medic",
    name: "Pack, Medic",
    weight: 2,
    tags: ["container", "load-bearing-equipment", "mlbe", "pack", "medical"],
    barterValue: "GG100",
    streetPrice: 200,
    voucherCost: { "worn:back": 1 },
    voucherLimits: { "mlbe:ap": 24 },
    description: "Field-pack-derived medical pack with additional internal organization and 24 attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-frame",
    name: "Pack Frame",
    weight: 1,
    tags: ["container", "load-bearing-equipment", "mlbe", "frame"],
    barterValue: "GG32.5",
    streetPrice: 65,
    voucherCost: { "worn:back": 1 },
    description: "Frame sized to accept compatible patrol, field, or medic packs as a modular frame-pack setup.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:thigh-carrier",
    name: "Thigh Carrier",
    weight: 0.2,
    tags: ["container", "load-bearing-equipment", "mlbe", "thigh-rig"],
    barterValue: "GG32.5",
    streetPrice: 65,
    voucherCost: { "worn:legs": 1 },
    voucherLimits: { "mlbe:ap": 4 },
    description: "Drop-leg platform with 4 attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:thigh-holster",
    name: "Thigh Holster",
    weight: 0.2,
    tags: ["container", "load-bearing-equipment", "mlbe", "holster"],
    barterValue: "GG32.5",
    streetPrice: 65,
    voucherCost: { "worn:legs": 1 },
    itemVoucherRules: [
      { key: "stowed:handgun", acceptedItemTags: ["handgun"] },
      { key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] },
    ],
    voucherLimits: { "stowed:handgun": 1, "stowed:magazine": 1 },
    description: "Drop-leg holster sized for 1 handgun with an extra pocket for one spare magazine.",
    defaultMode: "bag",
  }),
];

export const MODULAR_LOAD_BEARING_POUCHES: ContainerDefinition[] = [
  defineAttachmentContainer({
    id: "container:mlbe:belted-ammo-small",
    name: "Belted Ammo, Small",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG43.5",
    streetPrice: 87,
    attachmentPointCost: 3,
    description: "Modular pouch sized for 100 rounds of belted ammunition.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:belted-ammo-large",
    name: "Belted Ammo, Large",
    weight: 0.3,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG60",
    streetPrice: 120,
    attachmentPointCost: 6,
    description: "Modular pouch sized for 200 rounds of belted ammunition.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-handgun",
    name: "Magazine, Handgun",
    weight: 0,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG12.5",
    streetPrice: 25,
    attachmentPointCost: 1,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 1 },
    description: "Single modular magazine pouch for 1 handgun magazine.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-single",
    name: "Magazine, Rifle, Single",
    weight: 0,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG13.5",
    streetPrice: 27,
    attachmentPointCost: 2,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 1 },
    description: "Single modular magazine pouch for 1 rifle magazine.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-double",
    name: "Magazine, Rifle, Double",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG18",
    streetPrice: 36,
    attachmentPointCost: 2,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 2 },
    description: "Double modular magazine pouch for 2 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-quad",
    name: "Magazine, Rifle, Quad",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG20",
    streetPrice: 40,
    attachmentPointCost: 3,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 4 },
    description: "Quad modular magazine placard for 4 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-six",
    name: "Magazine, Rifle, Six",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG27.5",
    streetPrice: 55,
    attachmentPointCost: 4,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 6 },
    description: "Large modular magazine placard for 6 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:rifle-cartridge-loops",
    name: "Rifle Cartridge Loops",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG15",
    streetPrice: 30,
    attachmentPointCost: 3,
    description: "Modular ammunition panel sized for 20 rifle rounds.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:shotgun-shell-loops",
    name: "Shotgun Shell Loops",
    weight: 0,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG14",
    streetPrice: 28,
    attachmentPointCost: 3,
    description: "Modular shell panel sized for 12 shotgun shells.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:shotgun-shell-roll",
    name: "Shotgun Shell Roll",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG32.5",
    streetPrice: 65,
    attachmentPointCost: 5,
    description: "Large modular shell roll sized for 36 shotgun shells.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:hand-grenade-loop",
    name: "Hand Grenade Loop",
    weight: 0,
    tags: ["container", "mlbe-pouch", "grenade-carriage"],
    barterValue: "GG18",
    streetPrice: 36,
    attachmentPointCost: 1,
    description: "Modular loop sized for 1 grenade.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:launcher-grenade-loop",
    name: "Launcher Grenade Loop",
    weight: 0,
    tags: ["container", "mlbe-pouch", "grenade-carriage"],
    barterValue: "GG9.5",
    streetPrice: 19,
    attachmentPointCost: 1,
    description: "Modular loop sized for 1 launcher grenade.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:canteen-carrier",
    name: "Canteen Carrier",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "canteen-carrier"],
    barterValue: "GG21",
    streetPrice: 42,
    attachmentPointCost: 2,
    containerVoucherRules: [createContainerRule("stowed:canteen", ["water-container"])],
    voucherLimits: { "stowed:canteen": 1 },
    description: "Modular pouch sized for 1 liter canteen.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:gas-mask-carrier",
    name: "Gas Mask Carrier",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "protective-equipment"],
    barterValue: "GG30",
    streetPrice: 60,
    attachmentPointCost: 6,
    itemVoucherRules: [createItemRule("stowed:protective-equipment", ["protective-equipment", "gas-mask"])],
    voucherLimits: { "stowed:protective-equipment": 1 },
    description: "Modular carrier sized for 1 gas mask.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:holster",
    name: "Holster",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "holster"],
    barterValue: "GG32.5",
    streetPrice: 65,
    attachmentPointCost: 4,
    itemVoucherRules: [{ key: "stowed:handgun", acceptedItemTags: ["handgun"] }],
    voucherLimits: { "stowed:handgun": 1 },
    description: "Modular holster sized for 1 handgun.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:hydration-bladder-carrier",
    name: "Hydration Bladder Carrier",
    weight: 0.3,
    tags: ["container", "mlbe-pouch", "hydration"],
    barterValue: "GG32.5",
    streetPrice: 65,
    attachmentPointCost: 8,
    containerVoucherRules: [createContainerRule("stowed:hydration", ["hydration"])],
    voucherLimits: { "stowed:hydration": 1 },
    description: "Modular carrier sized for a 3 liter hydration bladder.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:map-pouch",
    name: "Map Pouch",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "map-pouch"],
    barterValue: "GG16",
    streetPrice: 32,
    attachmentPointCost: 6,
    description: "Flat modular pouch sized for papers or objects up to about 15 x 30 cm.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:medical-pouch",
    name: "Medical Pouch",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "medical"],
    barterValue: "GG25",
    streetPrice: 50,
    attachmentPointCost: 4,
    itemVoucherRules: [createItemRule("stowed:medical", ["medical", "ifak"])],
    voucherLimits: { "stowed:medical": 1 },
    description: "Modular medical pouch sized for 1 IFAK.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:nvg-carrier-padded",
    name: "NVG Carrier, Padded",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "optics"],
    barterValue: "GG15",
    streetPrice: 30,
    attachmentPointCost: 4,
    itemVoucherRules: [createItemRule("stowed:nvg", ["nvgs"])],
    voucherLimits: { "stowed:nvg": 1 },
    description: "Padded modular pouch sized for 1 set of NVGs.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:radio-pouch",
    name: "Radio Pouch",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "radio-pouch"],
    barterValue: "GG18.5",
    streetPrice: 37,
    attachmentPointCost: 2,
    itemVoucherRules: [createItemRule("stowed:radio", ["radio"])],
    voucherLimits: { "stowed:radio": 1 },
    description: "Modular pouch sized for 1 tactical radio.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:utility-pouch",
    name: "Utility Pouch",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "utility-pouch"],
    barterValue: "GG22",
    streetPrice: 44,
    attachmentPointCost: 4,
    description: "General-purpose modular pouch with roughly 12 x 18 x 8 cm of internal space.",
    defaultMode: "bag",
  }),
];

export const SURVIVAL_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:survival:canteen-1l",
    name: "Canteen, 1 Liter",
    weight: 1.3,
    capacityWeight: 1,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG1",
    streetPrice: 10,
    description: "Water canteen that holds 1 liter of liquid; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:flask-0-25l",
    name: "Flask, 0.25 Liter",
    weight: 0.3,
    capacityWeight: 0.25,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG1",
    streetPrice: 10,
    description: "Small liquid flask; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-1-5l",
    name: "Hydration Bladder, 1.5 Liters",
    weight: 1.6,
    capacityWeight: 1.5,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG2",
    streetPrice: 20,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-2l",
    name: "Hydration Bladder, 2 Liters",
    weight: 2.1,
    capacityWeight: 2,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG2.5",
    streetPrice: 25,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-3l",
    name: "Hydration Bladder, 3 Liters",
    weight: 3.2,
    capacityWeight: 3,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG3",
    streetPrice: 30,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-6l",
    name: "Hydration Bladder, 6 Liters",
    weight: 6.3,
    capacityWeight: 6,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG3.6",
    streetPrice: 36,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-10l",
    name: "Hydration Bladder, 10 Liters",
    weight: 10.3,
    capacityWeight: 10,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG4",
    streetPrice: 40,
    description: "Large hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:water-bottle-0-5l",
    name: "Water Bottle, 0.5 Liter",
    weight: 0.6,
    capacityWeight: 0.5,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG0.6",
    streetPrice: 6,
    description: "Water bottle; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:water-bottle-1l",
    name: "Water Bottle, 1 Liter",
    weight: 1.2,
    capacityWeight: 1,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG0.9",
    streetPrice: 9,
    description: "Water bottle; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:waterskin-1-5l",
    name: "Waterskin, 1.5 Liter",
    weight: 1.8,
    capacityWeight: 1.5,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG1.5",
    streetPrice: 15,
    description: "Traditional waterskin; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:waterskin-5l",
    name: "Waterskin, 5 Liter",
    weight: 6,
    capacityWeight: 5,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG2",
    streetPrice: 20,
    description: "Large waterskin; listed weight includes full contents.",
    defaultMode: "bag",
  }),
];

export const LIQUID_STORAGE_CONTAINERS: ContainerDefinition[] = [
  defineContainer({ id: "container:storage:bulk-tank-750l", name: "Bulk Tank, 750 Liters", weight: 100, capacityWeight: 750, tags: ["container", "storage", "liquid-storage"], barterValue: "GG20", streetPrice: 400, description: "Field storage tank for up to 750 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:bulk-tank-1000l", name: "Bulk Tank, 1,000 Liters", weight: 130, capacityWeight: 1000, tags: ["container", "storage", "liquid-storage"], barterValue: "GG30", streetPrice: 600, description: "Field storage tank for up to 1,000 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:bulk-tank-2000l", name: "Bulk Tank, 2,000 Liters", weight: 250, capacityWeight: 2000, tags: ["container", "storage", "liquid-storage"], barterValue: "GG37.5", streetPrice: 750, description: "Field storage tank for up to 2,000 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:bulk-tank-4000l", name: "Bulk Tank, 4,000 Liters", weight: 520, capacityWeight: 4000, tags: ["container", "storage", "liquid-storage"], barterValue: "GG60", streetPrice: 1200, description: "Field storage tank for up to 4,000 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:drum-metal-200l", name: "Drum, Metal, 200 Liters", weight: 17, capacityWeight: 200, tags: ["container", "storage", "liquid-storage", "drum"], barterValue: "GG10", streetPrice: 45, description: "Standard steel 200-liter drum.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:drum-plastic-200l", name: "Drum, Plastic, 200 Liters", weight: 10, capacityWeight: 200, tags: ["container", "storage", "liquid-storage", "drum"], barterValue: "GG15", streetPrice: 65, description: "Plastic 200-liter drum.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:folding-bladder-20l", name: "Folding Bladder, 20 Liters", weight: 0.3, capacityWeight: 20, tags: ["container", "storage", "liquid-storage", "bladder"], barterValue: "GG1", streetPrice: 9, description: "Flexible clear plastic liquid bladder.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:fuel-bladder-300l", name: "Fuel Bladder, 300 Liters", weight: 70, capacityWeight: 300, tags: ["container", "storage", "liquid-storage", "fuel"], barterValue: "GG20", streetPrice: 700, description: "Reinforced field-rated fuel bladder.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:fuel-bladder-1100l", name: "Fuel Bladder, 1,100 Liters", weight: 250, capacityWeight: 1100, tags: ["container", "storage", "liquid-storage", "fuel"], barterValue: "GG30", streetPrice: 1000, description: "Large reinforced field-rated fuel bladder.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:jerry-can-20l", name: "Jerry Can, 20 Liters", weight: 2, capacityWeight: 20, tags: ["container", "storage", "liquid-storage", "fuel"], barterValue: "GG5", streetPrice: 25, description: "Rectangular field fuel can.", defaultMode: "bag" }),
];

export const DRY_GOODS_STORAGE_CONTAINERS: ContainerDefinition[] = [
  defineContainer({ id: "container:storage:ammo-can", name: "Ammo Can", weight: 3, tags: ["container", "storage", "dry-goods"], barterValue: "GG0.8", streetPrice: 8, description: "Steel hinged-lid ammunition can; a common example holds roughly 800 rounds of 5.56x45mm ammunition.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:cargo-pallet", name: "Cargo Pallet", weight: 20, tags: ["container", "storage", "dry-goods"], barterValue: "GG0.75", streetPrice: 15, description: "One-meter square cargo pallet framework for up to roughly 2 tons of freight.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:handgun-case-hard", name: "Handgun Case, Hard", weight: 1, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG20", streetPrice: 40, description: "Rigid handgun case sized for Bulk 1 handguns plus accessories.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:handgun-case-soft", name: "Handgun Case, Soft", weight: 0.5, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG15", streetPrice: 30, description: "Soft handgun case sized for Bulk 1 handguns plus accessories.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:long-gun-case-hard", name: "Long Gun Case, Hard", weight: 4, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG40", streetPrice: 80, description: "Rigid long-gun case sized for a single weapon plus magazines, optics, and tools.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:long-gun-case-mlbe", name: "Long Gun Case, MLBE", weight: 1.7, tags: ["container", "storage", "dry-goods", "gun-case", "mlbe"], barterValue: "GG50", streetPrice: 100, voucherLimits: { "mlbe:ap": 12 }, description: "Long gun case built on an MLBE-compatible exterior with 12 attachment points.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:long-gun-case-soft", name: "Long Gun Case, Soft", weight: 1.5, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG32.5", streetPrice: 65, description: "Soft long-gun case sized for a single weapon plus accessories.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:portable-refrigerator", name: "Portable Refrigerator", weight: 18, tags: ["container", "storage", "dry-goods", "refrigerated"], barterValue: "GG950", streetPrice: 1900, description: "15-liter medical or organ transport refrigerator with integrated handle and latch.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:shipping-container-6m", name: "Shipping Container, 6 m", weight: 2200, capacityWeight: 15000, tags: ["container", "storage", "dry-goods", "shipping-container"], barterValue: "GG50", streetPrice: 2000, description: "Standard 6-meter intermodal steel container.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:shipping-container-12m", name: "Shipping Container, 12 m", weight: 3700, capacityWeight: 30000, tags: ["container", "storage", "dry-goods", "shipping-container"], barterValue: "GG75", streetPrice: 3000, description: "Standard 12-meter intermodal steel container.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:shipping-container-16m", name: "Shipping Container, 16 m", weight: 4700, capacityWeight: 40000, tags: ["container", "storage", "dry-goods", "shipping-container"], barterValue: "GG90", streetPrice: 3500, description: "Standard 16-meter intermodal steel container.", defaultMode: "bin" }),
];

export const CONTAINER_CATALOG: ContainerDefinition[] = [
  ...PACK_CONTAINERS,
  ...FIXED_LOAD_BEARING_CONTAINERS,
  ...FIXED_LBE_COMPONENT_CONTAINERS,
  ...MODULAR_LOAD_BEARING_CONTAINERS,
  ...MODULAR_LOAD_BEARING_POUCHES,
  ...SURVIVAL_CONTAINERS,
  ...LIQUID_STORAGE_CONTAINERS,
  ...DRY_GOODS_STORAGE_CONTAINERS,
];