import { createItemDefinition } from "./inventory";
import type { ItemDefinition, ItemDamageProfile } from "./types";

const SOURCE_BOOK = "Twilight 2013 Core OEF PDF";

function source(page: number): string {
  return `Source: ${SOURCE_BOOK} p.${page}`;
}

function defineDemolitionItem(input: {
  id: string;
  name: string;
  weight: number;
  barterValue: string;
  streetPrice: number;
  page: number;
  tags: string[];
  traits: string[];
  damage?: ItemDamageProfile[];
  description: string;
}): ItemDefinition {
  return createItemDefinition({
    id: input.id,
    name: input.name,
    weight: input.weight,
    barterValue: input.barterValue,
    streetPrice: input.streetPrice,
    source: [source(input.page)],
    tags: input.tags,
    traits: input.traits,
    damage: input.damage,
    description: input.description,
  });
}

export interface DemolitionReferenceRule {
  id: string;
  name: string;
  source: string[];
  traits: string[];
  notes: string[];
}

export const DEMOLITION_CATALOG: ItemDefinition[] = [
  defineDemolitionItem({
    id: "demolition:mine:antipersonnel",
    name: "Antipersonnel Mine",
    weight: 1.6,
    barterValue: "GG55",
    streetPrice: 45,
    page: 268,
    tags: ["demolition", "mine", "anti-personnel"],
    traits: ["demolition:mine", "demolition:pressure-trigger:5kg"],
    damage: [{ damage: 8, blast: 4, frag: 6, area: { kind: "radius", meters: 2 } }],
    description: "Fragmentation mine. Triggered by 5 kg of direct pressure.",
  }),
  defineDemolitionItem({
    id: "demolition:mine:antitank-blast",
    name: "Antitank Mine, Blast",
    weight: 13,
    barterValue: "GG75",
    streetPrice: 60,
    page: 268,
    tags: ["demolition", "mine", "anti-vehicle"],
    traits: ["demolition:mine", "demolition:pressure-trigger:150kg", "demolition:blast-mine"],
    damage: [{ damage: 20, blast: 20, frag: 3, area: { kind: "radius", meters: 10 } }],
    description: "Blast antitank mine. Triggered by 150 kg of direct pressure.",
  }),
  defineDemolitionItem({
    id: "demolition:mine:antitank-shaped",
    name: "Antitank Mine, Shaped",
    weight: 8,
    barterValue: "GG95",
    streetPrice: 75,
    page: 268,
    tags: ["demolition", "mine", "anti-vehicle"],
    traits: ["demolition:mine", "demolition:pressure-trigger:150kg", "demolition:shaped-charge"],
    damage: [{ damage: 40, blast: 10, frag: 2, area: { kind: "radius", meters: 5 } }],
    description: "Shaped-charge antitank mine. Triggered by 150 kg of direct pressure.",
  }),
  defineDemolitionItem({
    id: "demolition:mine:bounding",
    name: "Bounding Mine",
    weight: 3.6,
    barterValue: "GG65",
    streetPrice: 50,
    page: 268,
    tags: ["demolition", "mine", "anti-personnel"],
    traits: ["demolition:mine", "demolition:pressure-trigger", "demolition:tripwire-compatible", "demolition:bounding"],
    damage: [{ damage: 5, blast: 5, frag: 7, area: { kind: "radius", meters: 15 } }],
    description: "Bounding antipersonnel mine. Jumps to chest height before detonation.",
  }),
  defineDemolitionItem({
    id: "demolition:mine:directional",
    name: "Directional Mine",
    weight: 1.6,
    barterValue: "GG185",
    streetPrice: 150,
    page: 268,
    tags: ["demolition", "mine", "directional"],
    traits: ["demolition:mine", "demolition:tripwire-compatible", "demolition:command-detonation-capable", "demolition:cone-fragmentation"],
    damage: [{ damage: 7, blast: 7, frag: 8, area: { kind: "cone", degrees: 60 }, notes: ["Includes normal secondary effects."] }],
    description: "Directional fragmentation mine.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:anfo-30l-sack",
    name: "ANFO, 30-liter Sack",
    weight: 25,
    barterValue: "GG70",
    streetPrice: 55,
    page: 268,
    tags: ["demolition", "explosive-substance", "bulk-explosive"],
    traits: ["demolition:dp:20", "demolition:humidity-sensitive", "demolition:requires-mixing"],
    description: "Industrial ammonium nitrate and fuel oil explosive. Loses 10% of its DP every 1d3 days once exposed to open air.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:black-powder-can",
    name: "Black Powder, 1 Can",
    weight: 1.8,
    barterValue: "GG55",
    streetPrice: 90,
    page: 268,
    tags: ["demolition", "explosive-substance"],
    traits: ["demolition:dp:9", "demolition:water-sensitive"],
    description: "Traditional potassium nitrate charcoal and sulfur powder. Becomes useless if immersed in water.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:det-cord-100m",
    name: "Detonating Cord, 100m Spool",
    weight: 3.2,
    barterValue: "GG125",
    streetPrice: 100,
    page: 268,
    tags: ["demolition", "explosive-substance", "detonator-feed"],
    traits: ["demolition:dp:0.13-per-meter", "demolition:waterproof"],
    description: "Waterproof explosive cord used for priming and linking demolition charges.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:dynamite-commercial-stick",
    name: "Dynamite, Commercial, 1 Stick",
    weight: 0.2,
    barterValue: "GG4",
    streetPrice: 3,
    page: 268,
    tags: ["demolition", "explosive-substance"],
    traits: ["demolition:dp:3", "demolition:shock-sensitive", "demolition:water-sensitive:1d6-hours"],
    description: "Older commercial dynamite. May detonate under severe shock and becomes useless after prolonged immersion.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:dynamite-military-stick",
    name: "Dynamite, Military, 1 Stick",
    weight: 0.2,
    barterValue: "GG7",
    streetPrice: 5,
    page: 268,
    tags: ["demolition", "explosive-substance"],
    traits: ["demolition:dp:2", "demolition:water-resistant:3d6+12-hours"],
    description: "Military demolition stick without nitroglycerin instability.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:plastic-explosive-block",
    name: "Plastic Explosive, Block",
    weight: 0.6,
    barterValue: "GG75",
    streetPrice: 60,
    page: 268,
    tags: ["demolition", "explosive-substance", "plastic-explosive"],
    traits: ["demolition:dp:6", "demolition:requires-blasting-cap-or-det-cord", "demolition:adhesive-backing"],
    description: "C4-like plastic explosive block that detonates only when subjected to heat and impact together.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:plastic-explosive-strip-15m",
    name: "Plastic Explosive, Strip, 15m Spool",
    weight: 11.3,
    barterValue: "GG1,500",
    streetPrice: 1200,
    page: 268,
    tags: ["demolition", "explosive-substance", "plastic-explosive"],
    traits: ["demolition:dp:7.5-per-meter", "demolition:requires-blasting-cap-or-det-cord", "demolition:adhesive-backing"],
    description: "Spool-packed strip explosive roughly 8 cm wide and 6 mm thick with one adhesive side.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:tnt-small-block",
    name: "TNT, Small Block",
    weight: 0.1,
    barterValue: "GG25",
    streetPrice: 20,
    page: 268,
    tags: ["demolition", "explosive-substance", "tnt"],
    traits: ["demolition:dp:1", "demolition:water-resistant"],
    description: "Small TNT demolition block.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:tnt-medium-block",
    name: "TNT, Medium Block",
    weight: 0.2,
    barterValue: "GG45",
    streetPrice: 35,
    page: 268,
    tags: ["demolition", "explosive-substance", "tnt"],
    traits: ["demolition:dp:2", "demolition:water-resistant"],
    description: "Medium TNT demolition block.",
  }),
  defineDemolitionItem({
    id: "demolition:explosive:tnt-large-block",
    name: "TNT, Large Block",
    weight: 0.5,
    barterValue: "GG80",
    streetPrice: 65,
    page: 268,
    tags: ["demolition", "explosive-substance", "tnt"],
    traits: ["demolition:dp:4", "demolition:water-resistant"],
    description: "Large TNT demolition block.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:blasting-cap-electric-20",
    name: "Blasting Cap, Electric (per 20)",
    weight: 0.1,
    barterValue: "GG2.5",
    streetPrice: 25,
    page: 268,
    tags: ["demolition", "detonation-system", "blasting-cap"],
    traits: ["demolition:detonator:electric", "demolition:rf-sensitive"],
    description: "Electric blasting caps for initiating demolition charges. Vulnerable to accidental RF-triggered detonation nearby.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:blasting-cap-pyrotechnic-20",
    name: "Blasting Cap, Pyrotechnic (per 20)",
    weight: 0.1,
    barterValue: "GG1.5",
    streetPrice: 15,
    page: 268,
    tags: ["demolition", "detonation-system", "blasting-cap"],
    traits: ["demolition:detonator:pyrotechnic", "demolition:ignites-from-incendiary"],
    description: "Flame-triggered blasting caps for fuses and pyrotechnic detonations.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:blasting-machine",
    name: "Blasting Machine",
    weight: 0.5,
    barterValue: "GG12.5",
    streetPrice: 250,
    page: 268,
    tags: ["demolition", "detonation-system", "blasting-machine"],
    traits: ["demolition:detonation-device", "demolition:reusable"],
    description: "Manual plunger or crank generator for firing electric caps down attached wire.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:fuse-instant-100m",
    name: "Fuse, Instant, 100m Spool",
    weight: 0.3,
    barterValue: "GG5",
    streetPrice: 100,
    page: 268,
    tags: ["demolition", "detonation-system", "fuse"],
    traits: ["demolition:fuse:instant"],
    description: "Fast-burning fuse rated at roughly 6 km per second.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:fuse-timed-100m",
    name: "Fuse, Timed, 100m Spool",
    weight: 0.3,
    barterValue: "GG5",
    streetPrice: 100,
    page: 268,
    tags: ["demolition", "detonation-system", "fuse"],
    traits: ["demolition:fuse:timed:1cm-per-second"],
    description: "Timed fuse burning at exactly 1 cm per second.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:igniter-pressure",
    name: "Igniter, Pressure",
    weight: 0,
    barterValue: "GG0.5",
    streetPrice: 25,
    page: 268,
    tags: ["demolition", "detonation-system", "igniter"],
    traits: ["demolition:igniter:pressure"],
    description: "Mechanical igniter with a configurable pressure trigger up to 250 kg in 5 kg steps.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:igniter-pressure-release",
    name: "Igniter, Pressure/Release",
    weight: 0,
    barterValue: "GG0.8",
    streetPrice: 40,
    page: 268,
    tags: ["demolition", "detonation-system", "igniter"],
    traits: ["demolition:igniter:pressure", "demolition:igniter:release"],
    description: "Pressure igniter that also triggers when weight is removed.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:igniter-pull",
    name: "Igniter, Pull",
    weight: 0,
    barterValue: "GG0.5",
    streetPrice: 25,
    page: 268,
    tags: ["demolition", "detonation-system", "igniter"],
    traits: ["demolition:igniter:pull"],
    description: "Mechanical igniter triggered by a single tripwire being pulled.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:igniter-pull-release",
    name: "Igniter, Pull/Release",
    weight: 0,
    barterValue: "GG0.8",
    streetPrice: 40,
    page: 268,
    tags: ["demolition", "detonation-system", "igniter"],
    traits: ["demolition:igniter:pull", "demolition:igniter:release", "demolition:igniter:tripwire:3"],
    description: "Igniter for up to three tripwires, triggered by a change in line tension.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:timer",
    name: "Timer",
    weight: 0,
    barterValue: "GG2.4",
    streetPrice: 30,
    page: 268,
    tags: ["demolition", "detonation-system", "timer"],
    traits: ["demolition:timer", "demolition:waterproof-once-set", "demolition:electric-output:10-caps"],
    description: "Digital demolition timer settable up to 48 hours, able to fire up to 10 electric caps.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:wire-electrical-100m",
    name: "Wire, Electrical, 100m Spool",
    weight: 5,
    barterValue: "GG0.06",
    streetPrice: 30,
    page: 268,
    tags: ["demolition", "detonation-system", "wire"],
    traits: ["demolition:wire:electric"],
    description: "Insulated firing wire for electric blasting caps.",
  }),
  defineDemolitionItem({
    id: "demolition:detonator:wire-trip-100m",
    name: "Wire, Trip, 100m Spool",
    weight: 0.4,
    barterValue: "GG0.04",
    streetPrice: 20,
    page: 268,
    tags: ["demolition", "detonation-system", "wire"],
    traits: ["demolition:wire:trip"],
    description: "Simple tripwire for pull and pull/release igniters.",
  }),
];

export const DEMOLITION_RULES: DemolitionReferenceRule[] = [
  {
    id: "demolition-rule:basic-charges",
    name: "Basic Charges",
    source: [source(269)],
    traits: ["demolition:charge:basic", "demolition:frag:4"],
    notes: [
      "Basic charge damage is 5 times the square root of total DP, rounded normally.",
      "Radius equals Damage in meters.",
      "Blast equals Damage.",
      "Fragmentation Density defaults to 4.",
    ],
  },
  {
    id: "demolition-rule:shaped-charges",
    name: "Shaped Charges",
    source: [source(270)],
    traits: ["demolition:charge:shaped", "demolition:damage-double", "demolition:radius-quarter", "demolition:blast-quarter", "demolition:frag-2"],
    notes: [
      "Converting a basic charge into a shaped charge doubles Damage.",
      "Radius and Blast are both divided by 4.",
      "Fragmentation Density becomes 2.",
      "Creating a shaped charge adds a -3 penalty to the Construction/Demolition check and doubles time per DP to 10 minutes.",
    ],
  },
  {
    id: "demolition-rule:fragmentation-charges",
    name: "Fragmentation Charges",
    source: [source(269)],
    traits: ["demolition:charge:fragmentation"],
    notes: [
      "Converting a regular charge into a fragmentation charge halves Damage and Blast.",
      "Radius remains unchanged.",
      "Every 0.5 kg of shrapnel per DP raises Frag by 1, to a maximum of 10.",
    ],
  },
  {
    id: "demolition-rule:building-bombs",
    name: "Building and Emplacing Charges",
    source: [source(269)],
    traits: ["demolition:crafting:construction-demolition"],
    notes: [
      "Creating a charge uses Construction/Demolition (CDN) with a cumulative -1 per full 10 DP used.",
      "Creation takes 5 minutes per DP for a standard charge or 10 minutes per DP for a shaped or fragmentation charge.",
      "Emplacing a charge uses Construction/Demolition (COG) with a cumulative -1 per full 10 DP used.",
      "If the character built the charge himself, emplacement gains a bonus equal to the creation margin of success.",
      "Emplacement takes 1 minute or 1 operational action per 10 DP or fraction thereof.",
    ],
  },
];