import { createItemDefinition } from "./inventory";
import type { ItemDefinition, ItemDefinitionInit } from "./types";

function withTags(tags: string[] | undefined, extraTags: string[]): string[] | undefined {
	const mergedTags = [...(tags ?? []), ...extraTags];
	return mergedTags.length > 0
		? [...new Set(mergedTags)]
		: undefined;
}

function defineElectronicItem(input: ItemDefinitionInit & { powered?: boolean }): ItemDefinition {
	const { powered, ...item } = input;
	return createItemDefinition({
		...item,
		tags: withTags(item.tags, powered ? ["powered"] : []),
	});
}

function defineBatteryDevice(
	input: ItemDefinitionInit & {
		batteryCount: number;
		batterySize: string;
		runtimeHours: number;
	},
): ItemDefinition {
	return defineElectronicItem({
		...input,
			powered: true,
		power: {
			kind: "battery",
			batteryCount: input.batteryCount,
			batterySize: input.batterySize,
			runtimeHours: input.runtimeHours,
		},
	});
}

function defineRechargeableDevice(
	input: ItemDefinitionInit & {
		runtimeHours: number;
		rechargeHoursPerHourUsed?: number;
	},
): ItemDefinition {
	return defineElectronicItem({
		...input,
			powered: true,
		power: {
			kind: "rechargeable",
			runtimeHours: input.runtimeHours,
			rechargeHoursPerHourUsed: input.rechargeHoursPerHourUsed ?? 0.5,
		},
	});
}

function defineAcPoweredDevice(
	input: ItemDefinitionInit & {
		kilowatts: number;
	},
): ItemDefinition {
	return defineElectronicItem({
		...input,
			powered: true,
		power: {
			kind: "ac",
			kilowatts: input.kilowatts,
		},
	});
}

export const ILLUMINATION_ITEMS: ItemDefinition[] = [
	defineElectronicItem({
		id: "illumination:candle",
		name: "Candle",
		weight: 0.1,
		tags: ["illumination", "light-source", "flame"],
		barterValue: "GG0.01",
		streetPrice: 1,
		duration: "8 hours",
		description: "Typical candle with about an 8-hour burn time.",
	}),
	defineElectronicItem({
		id: "illumination:chem-light-standard",
		name: "Chemlight, Standard",
		weight: 0,
		tags: ["illumination", "light-source", "chemlight"],
		barterValue: "GG0.3",
		streetPrice: 1.25,
		duration: "Several hours",
		description: "Cold-light chemical stick. Produces steady light for several hours before fading.",
	}),
	defineElectronicItem({
		id: "illumination:chem-light-high-intensity",
		name: "Chemlight, High-Intensity",
		weight: 0,
		tags: ["illumination", "light-source", "chemlight"],
		barterValue: "GG0.6",
		streetPrice: 2.5,
		duration: "Short duration",
		description: "High-intensity chemlight with brighter but shorter duration output.",
	}),
	defineElectronicItem({
		id: "illumination:chem-light-ir",
		name: "Chemlight, IR",
		weight: 0,
		tags: ["illumination", "light-source", "chemlight", "infrared"],
		barterValue: "GG2.4",
		streetPrice: 5,
		duration: "Several hours",
		description: "Infrared chemlight visible only to night-vision optics.",
	}),
	defineBatteryDevice({
		id: "illumination:flashlight-micro",
		name: "Flashlight, Micro",
		weight: 0,
		tags: ["illumination", "light-source", "flashlight"],
		barterValue: "GG2",
		streetPrice: 20,
		powerRequirement: "1 micro/40 hrs",
		batteryCount: 1,
		batterySize: "micro",
		runtimeHours: 40,
		description: "Keychain-sized battery flashlight for maps, locks, and close work.",
	}),
	defineBatteryDevice({
		id: "illumination:flashlight-hand",
		name: "Flashlight, Hand",
		weight: 0.1,
		tags: ["illumination", "light-source", "flashlight"],
		barterValue: "GG3",
		streetPrice: 30,
		powerRequirement: "2 sm/8 hrs",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 8,
		description: "Pocket flashlight that provides useful illumination at Personal and Gunfighting range.",
	}),
	defineBatteryDevice({
		id: "illumination:flashlight-tactical",
		name: "Flashlight, Tactical",
		weight: 0.1,
		tags: ["illumination", "light-source", "flashlight", "tactical"],
		barterValue: "GG12",
		streetPrice: 120,
		powerRequirement: "2 sm/30 min",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 0.5,
		description: "Compact high-output tactical flashlight with duty-light intensity.",
	}),
	defineBatteryDevice({
		id: "illumination:flashlight-duty",
		name: "Flashlight, Duty",
		weight: 1,
		tags: ["illumination", "light-source", "flashlight", "duty"],
		barterValue: "GG8",
		streetPrice: 80,
		powerRequirement: "3 med/6 hrs",
		batteryCount: 3,
		batterySize: "med",
		runtimeHours: 6,
		description: "Large flashlight that provides adequate illumination through CQB range.",
	}),
	defineBatteryDevice({
		id: "illumination:headlamp",
		name: "Headlamp",
		weight: 0.1,
		tags: ["illumination", "light-source", "headlamp", "hands-free"],
		barterValue: "GG8",
		streetPrice: 40,
		powerRequirement: "2 sm/4 hrs",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 4,
		description: "Hands-free LED headlamp on a flexible head strap.",
	}),
	defineBatteryDevice({
		id: "illumination:lamp-battery",
		name: "Lamp, Battery",
		weight: 1,
		tags: ["illumination", "light-source", "lamp"],
		barterValue: "GG3",
		streetPrice: 25,
		powerRequirement: "4 med/20 hrs",
		batteryCount: 4,
		batterySize: "med",
		runtimeHours: 20,
		description: "Portable omnidirectional battery lamp.",
	}),
	defineElectronicItem({
		id: "illumination:lamp-oil",
		name: "Lamp, Oil",
		weight: 1,
		tags: ["illumination", "light-source", "lamp", "oil"],
		barterValue: "GG2",
		streetPrice: 40,
		duration: "30 hours",
		powerRequirement: "0.1 L/30 hr",
		description: "Portable oil-burning lamp with an internal fuel reservoir.",
	}),
	defineBatteryDevice({
		id: "illumination:searchlight-semi-portable",
		name: "Searchlight, Semi-Portable",
		weight: 1.4,
		tags: ["illumination", "light-source", "searchlight"],
		barterValue: "GG8.75",
		streetPrice: 75,
		powerRequirement: "1 lg/1 hr",
		batteryCount: 1,
		batterySize: "lg",
		runtimeHours: 1,
		description: "Painfully bright handheld searchlight that can also run from a car accessory socket.",
	}),
];

export const MAGNIFICATION_ITEMS: ItemDefinition[] = [
	defineElectronicItem({
		id: "vision:binoculars-standard-mag-2",
		name: "Binoculars, Standard",
		weight: 1,
		tags: ["vision-enhancement", "magnification", "binoculars"],
		traits: ["Mag-2"],
		barterValue: "GG8",
		streetPrice: 80,
	}),
	defineElectronicItem({
		id: "vision:binoculars-standard-mag-3",
		name: "Binoculars, Standard",
		weight: 1.2,
		tags: ["vision-enhancement", "magnification", "binoculars"],
		traits: ["Mag-3"],
		barterValue: "GG20",
		streetPrice: 200,
	}),
	defineElectronicItem({
		id: "vision:binoculars-standard-mag-4",
		name: "Binoculars, Standard",
		weight: 1.4,
		tags: ["vision-enhancement", "magnification", "binoculars"],
		traits: ["Mag-4"],
		barterValue: "GG40",
		streetPrice: 400,
	}),
	defineElectronicItem({
		id: "vision:binoculars-compact-mag-1",
		name: "Binoculars, Compact",
		weight: 0.2,
		tags: ["vision-enhancement", "magnification", "binoculars", "compact"],
		traits: ["Mag-1"],
		barterValue: "GG6",
		streetPrice: 60,
	}),
	defineElectronicItem({
		id: "vision:binoculars-compact-mag-2",
		name: "Binoculars, Compact",
		weight: 0.3,
		tags: ["vision-enhancement", "magnification", "binoculars", "compact"],
		traits: ["Mag-2"],
		barterValue: "GG16",
		streetPrice: 160,
	}),
	defineBatteryDevice({
		id: "vision:laser-designator",
		name: "Laser Designator",
		weight: 16,
		tags: ["vision-enhancement", "magnification", "laser-designator", "targeting"],
		barterValue: "GG7,500",
		streetPrice: 30000,
		powerRequirement: "1 lg spec/5 hrs",
		batteryCount: 1,
		batterySize: "lg spec",
		runtimeHours: 5,
		traits: ["Mag-3"],
		description: "Multi-function targeting device for guiding laser-homing munitions.",
		notes: ["Combines a Mag-3 spotting scope with additional ranging, laser, and GPS functions."],
	}),
	defineElectronicItem({
		id: "vision:spotting-scope-mag-5",
		name: "Spotting Scope",
		weight: 5,
		tags: ["vision-enhancement", "magnification", "spotting-scope"],
		traits: ["Mag-5"],
		barterValue: "GG100",
		streetPrice: 1000,
	}),
	defineElectronicItem({
		id: "vision:telescope-astronomical-mag-5",
		name: "Telescope, Astronomical",
		weight: 9,
		tags: ["vision-enhancement", "magnification", "telescope"],
		traits: ["Mag-5"],
		barterValue: "GG15",
		streetPrice: 750,
	}),
	defineElectronicItem({
		id: "vision:telescope-nautical-mag-2",
		name: "Telescope, Nautical",
		weight: 1,
		tags: ["vision-enhancement", "magnification", "telescope"],
		traits: ["Mag-2"],
		barterValue: "GG3.25",
		streetPrice: 65,
	}),
];

export const NIGHT_VISION_ITEMS: ItemDefinition[] = [
	defineBatteryDevice({
		id: "vision:night-vision-binocs-mag-1",
		name: "Night Vision Binocs",
		weight: 1.2,
		tags: ["vision-enhancement", "night-vision", "binoculars"],
		traits: ["Mag-1"],
		barterValue: "GG200",
		streetPrice: 800,
		powerRequirement: "4 sm/40 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 40,
		description: "Night-vision binoculars with low magnification.",
	}),
	defineBatteryDevice({
		id: "vision:night-vision-binocs-mag-2",
		name: "Night Vision Binocs",
		weight: 1.4,
		tags: ["vision-enhancement", "night-vision", "binoculars"],
		traits: ["Mag-2"],
		barterValue: "GG300",
		streetPrice: 1200,
		powerRequirement: "4 sm/40 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 40,
		description: "Night-vision binoculars with moderate magnification.",
	}),
	defineBatteryDevice({
		id: "vision:night-vision-viewer",
		name: "Night Vision Viewer",
		weight: 1.5,
		tags: ["vision-enhancement", "night-vision", "viewer"],
		barterValue: "GG100",
		streetPrice: 400,
		powerRequirement: "4 sm/40 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 40,
		description: "Non-magnifying handheld IR image viewer.",
	}),
	defineBatteryDevice({
		id: "vision:nvgs-binocular",
		name: "NVGs, Binocular",
		weight: 0.7,
		tags: ["vision-enhancement", "night-vision", "nvgs", "binocular"],
		barterValue: "GG450",
		streetPrice: 4500,
		powerRequirement: "4 sm/40 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 40,
		description: "Helmet-mounted binocular night-vision goggles.",
		notes: ["Restrict field of vision but give the wearer full advantage of night-vision optics except reflex sights."],
	}),
	defineBatteryDevice({
		id: "vision:nvgs-monocular",
		name: "NVGs, Monocular",
		weight: 0.4,
		tags: ["vision-enhancement", "night-vision", "nvgs", "monocular"],
		barterValue: "GG360",
		streetPrice: 3600,
		powerRequirement: "2 sm/40 hrs",
		batteryCount: 2,
		batterySize: "sm",
		runtimeHours: 40,
		description: "Monocular helmet-mounted NVGs with a narrower field penalty than binocular units.",
	}),
	defineBatteryDevice({
		id: "vision:nvgs-panoramic",
		name: "NVGs, Panoramic",
		weight: 0.8,
		tags: ["vision-enhancement", "night-vision", "nvgs", "panoramic"],
		barterValue: "GG900",
		streetPrice: 12000,
		powerRequirement: "4 sm/40 hrs",
		batteryCount: 4,
		batterySize: "sm",
		runtimeHours: 40,
		description: "Rare panoramic night-vision goggles with a wider field of vision.",
	}),
];

export const THERMAL_IMAGING_ITEMS: ItemDefinition[] = [
	defineRechargeableDevice({
		id: "vision:thermal-imager",
		name: "Thermal Imager",
		weight: 2,
		tags: ["vision-enhancement", "thermal-imaging", "thermal-imager"],
		barterValue: "GG560",
		streetPrice: 2800,
		powerRequirement: "charge/6 hrs",
		runtimeHours: 6,
		description: "Portable thermal imager usable for observation and search.",
		notes: ["Detects human-sized heat sources out to Sniping range.", "Treats all lighting conditions as adequate light."],
	}),
	defineRechargeableDevice({
		id: "vision:thermal-imager-mag-1",
		name: "Thermal Imager",
		weight: 2.1,
		tags: ["vision-enhancement", "thermal-imaging", "thermal-imager"],
		traits: ["Mag-1"],
		barterValue: "GG850",
		streetPrice: 3400,
		powerRequirement: "charge/6 hrs",
		runtimeHours: 6,
		description: "Thermal imager with low electronic magnification.",
	}),
	defineRechargeableDevice({
		id: "vision:thermal-imager-mag-2",
		name: "Thermal Imager",
		weight: 2.1,
		tags: ["vision-enhancement", "thermal-imaging", "thermal-imager"],
		traits: ["Mag-2"],
		barterValue: "GG1,100",
		streetPrice: 4400,
		powerRequirement: "charge/6 hrs",
		runtimeHours: 6,
		description: "Thermal imager with moderate electronic magnification.",
	}),
];

export const POWERED_TOOLS: ItemDefinition[] = [
	defineElectronicItem({
		id: "tool:air-compressor",
		name: "Air Compressor",
		weight: 39,
		tags: ["tool", "powered-tool", "compressor"],
		barterValue: "GG800",
		streetPrice: 3200,
		powered: true,
		powerRequirement: "see text",
	}),
	defineAcPoweredDevice({
		id: "tool:aircraft-tools",
		name: "Aircraft Tools",
		weight: 75,
		tags: ["tool", "powered-tool", "aircraft-tools"],
		barterValue: "GG625",
		streetPrice: 2500,
		powerRequirement: "0.3 kW",
		kilowatts: 0.3,
	}),
	defineAcPoweredDevice({
		id: "tool:aircraft-tools-model-specific",
		name: "Aircraft Tools, Model-Specific",
		weight: 20,
		tags: ["tool", "powered-tool", "aircraft-tools"],
		barterValue: "GG200",
		streetPrice: 20000,
		powerRequirement: "0.5 kW",
		kilowatts: 0.5,
	}),
	defineAcPoweredDevice({
		id: "tool:basic-power-tools",
		name: "Basic Power Tools",
		weight: 15,
		tags: ["tool", "powered-tool", "workshop"],
		barterValue: "GG150",
		streetPrice: 1200,
		powerRequirement: "0.5 kW",
		kilowatts: 0.5,
	}),
	defineAcPoweredDevice({
		id: "tool:cement-mixer-portable",
		name: "Cement Mixer, Portable",
		weight: 70,
		tags: ["tool", "powered-tool", "construction"],
		barterValue: "GG85",
		streetPrice: 680,
		powerRequirement: "0.6 kW",
		kilowatts: 0.6,
	}),
	defineAcPoweredDevice({
		id: "tool:chainsaw-electric",
		name: "Chainsaw, Electric",
		weight: 3.3,
		tags: ["tool", "powered-tool", "chainsaw"],
		barterValue: "GG25",
		streetPrice: 100,
		powerRequirement: "2.2 kW",
		kilowatts: 2.2,
	}),
	defineElectronicItem({
		id: "tool:chainsaw-gasoline",
		name: "Chainsaw, Gasoline",
		weight: 4.5,
		tags: ["tool", "powered-tool", "chainsaw", "gasoline"],
		barterValue: "GG50",
		streetPrice: 200,
		powered: true,
		powerRequirement: "see text",
	}),
	defineAcPoweredDevice({
		id: "tool:machine-shop-portable",
		name: "Machine Shop, Portable",
		weight: 2.5,
		tags: ["tool", "powered-tool", "machine-shop"],
		barterValue: "GG625",
		streetPrice: 5000,
		powerRequirement: "1 kW",
		kilowatts: 1,
	}),
	defineElectronicItem({
		id: "tool:rescue-saw",
		name: "Rescue Saw",
		weight: 11,
		tags: ["tool", "powered-tool", "rescue-saw"],
		barterValue: "GG350",
		streetPrice: 1400,
		powered: true,
		powerRequirement: "see text",
	}),
	defineAcPoweredDevice({
		id: "tool:vehicle-tools-model-specific",
		name: "Vehicle Tools, Model-Specific",
		weight: 10,
		tags: ["tool", "powered-tool", "vehicle-tools"],
		barterValue: "GG100",
		streetPrice: 10000,
		powerRequirement: "0.2 kW",
		kilowatts: 0.2,
	}),
];

export const ELECTRONICS_CATALOG: ItemDefinition[] = [
	...ILLUMINATION_ITEMS,
	...MAGNIFICATION_ITEMS,
	...NIGHT_VISION_ITEMS,
	...THERMAL_IMAGING_ITEMS,
	...POWERED_TOOLS,
];
