import type { ItemDamageProfile } from "./types";

const SOURCE_BOOK = "Twilight 2013 Core OEF PDF";

function source(page: number): string {
  return `Source: ${SOURCE_BOOK} p.${page}`;
}

function sources(...pages: number[]): string[] {
  return pages.map(source);
}

function directDamage(damage: number): ItemDamageProfile[] {
  return [{ damage }];
}

function explosiveDamage(damage: number, radiusMeters: number, blast: number, frag: number): ItemDamageProfile[] {
  return [{ damage, blast, frag, area: { kind: "radius", meters: radiusMeters } }];
}

export interface LightSupportWeaponAmmunition {
  id: string;
  name: string;
  source: string[];
  damage?: ItemDamageProfile[];
  damageText?: string;
  effects?: string[];
  weightText: string;
  barterValue: string;
  streetPrice: number;
  traits?: string[];
  notes?: string[];
}

export interface LightSupportWeaponSystem {
  id: string;
  name: string;
  category:
    | "shoulder-fired-grenade-launcher"
    | "underbarrel-grenade-launcher"
    | "automatic-grenade-launcher"
    | "disposable-rocket-launcher"
    | "reusable-rocket-launcher"
    | "guided-missile-launcher"
    | "mortar";
  source: string[];
  caliber?: string;
  capacity: string;
  range: string;
  rateOfFire: string;
  speed: string;
  recoil?: number | string;
  bulk: number;
  weightText: string;
  barterValue: string;
  streetPrice: number;
  description: string;
  traits?: string[];
  notes?: string[];
  ammoOptions?: LightSupportWeaponAmmunition[];
}

export interface LightSupportWeaponReferenceRule {
  id: string;
  name: string;
  source: string[];
  traits: string[];
  notes: string[];
}

export const LIGHT_SUPPORT_WEAPONS: LightSupportWeaponSystem[] = [
  {
    id: "ordnance:launcher:shoulder-fired-generic:40x46mm",
    name: "Shoulder-fired Launcher (Generic)",
    category: "shoulder-fired-grenade-launcher",
    source: sources(264),
    caliber: "40x46mm",
    capacity: "1 (single-shot)",
    range: "M/O",
    rateOfFire: "S",
    speed: "3/5/7",
    bulk: 3,
    weightText: "2.7 kg",
    barterValue: "GG1,000",
    streetPrice: 2000,
    description: "Generic large break-action shoulder launcher in the M79 class.",
    traits: ["ordnance:grenade-launcher", "ordnance:single-shot"],
    ammoOptions: [
      {
        id: "ordnance-ammo:40x46mm:chem-smoke",
        name: "40x46mm Chem (Smoke)",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 5 m"],
        weightText: "0.2 kg per grenade",
        barterValue: "GG10",
        streetPrice: 20,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:smoke"],
      },
      {
        id: "ordnance-ammo:40x46mm:chem-tear-gas",
        name: "40x46mm Chem (Tear Gas)",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 5 m"],
        weightText: "0.2 kg per grenade",
        barterValue: "GG15",
        streetPrice: 30,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:tear-gas"],
      },
      {
        id: "ordnance-ammo:40x46mm:he",
        name: "40x46mm HE",
        source: sources(265),
        damage: explosiveDamage(8, 5, 8, 4),
        weightText: "0.2 kg per grenade",
        barterValue: "GG15",
        streetPrice: 30,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"],
      },
      {
        id: "ordnance-ammo:40x46mm:hedp",
        name: "40x46mm HEDP",
        source: sources(265),
        damage: explosiveDamage(15, 5, 8, 4),
        weightText: "0.2 kg per grenade",
        barterValue: "GG20",
        streetPrice: 40,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:dual-purpose"],
      },
      {
        id: "ordnance-ammo:40x46mm:illum",
        name: "40x46mm Illum",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 100 m", "1 minute"],
        weightText: "0.2 kg per grenade",
        barterValue: "GG10",
        streetPrice: 20,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:illumination"],
      },
      {
        id: "ordnance-ammo:40x46mm:stun",
        name: "40x46mm Stun",
        source: sources(265),
        damage: directDamage(3),
        weightText: "0.2 kg per grenade",
        barterValue: "GG15",
        streetPrice: 25,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:stun"],
      },
    ],
  },
  {
    id: "ordnance:launcher:tactical-generic:37mm",
    name: "Tactical Launcher (Generic)",
    category: "shoulder-fired-grenade-launcher",
    source: sources(264),
    caliber: "37mm",
    capacity: "1 (single-shot)",
    range: "T/O",
    rateOfFire: "S",
    speed: "3/5/7",
    bulk: 3,
    weightText: "2.7 kg",
    barterValue: "GG125",
    streetPrice: 500,
    description: "Police-pattern 37mm launcher limited to less-lethal and utility munitions.",
    traits: ["ordnance:grenade-launcher", "ordnance:single-shot", "ordnance:less-lethal-only"],
    ammoOptions: [
      {
        id: "ordnance-ammo:37mm:chem-smoke",
        name: "37mm Chem (Smoke)",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 5 m"],
        weightText: "0.2 kg per grenade",
        barterValue: "GG10",
        streetPrice: 20,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:smoke"],
      },
      {
        id: "ordnance-ammo:37mm:chem-tear-gas",
        name: "37mm Chem (Tear Gas)",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 5 m"],
        weightText: "0.2 kg per grenade",
        barterValue: "GG15",
        streetPrice: 30,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:tear-gas"],
      },
      {
        id: "ordnance-ammo:37mm:stun",
        name: "37mm Stun",
        source: sources(265),
        damage: directDamage(3),
        weightText: "0.2 kg per grenade",
        barterValue: "GG15",
        streetPrice: 25,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:stun"],
      },
    ],
  },
  {
    id: "ordnance:launcher:m320-unmounted:40x46mm",
    name: "M320 (Unmounted)",
    category: "shoulder-fired-grenade-launcher",
    source: sources(264),
    caliber: "40x46mm",
    capacity: "1 (single-shot)",
    range: "M/O",
    rateOfFire: "S",
    speed: "3/5/7",
    bulk: 3,
    weightText: "1.5 kg",
    barterValue: "GG1,750",
    streetPrice: 3500,
    description: "Stock-fitted M320 configured as a standalone launcher rather than an underbarrel mount.",
    traits: ["ordnance:grenade-launcher", "ordnance:single-shot"],
    ammoOptions: [
      { id: "ordnance-ammo:40x46mm:chem-smoke", name: "40x46mm Chem (Smoke)", source: sources(265), damageText: "-", effects: ["Radius 5 m"], weightText: "0.2 kg per grenade", barterValue: "GG10", streetPrice: 20, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:smoke"] },
      { id: "ordnance-ammo:40x46mm:chem-tear-gas", name: "40x46mm Chem (Tear Gas)", source: sources(265), damageText: "-", effects: ["Radius 5 m"], weightText: "0.2 kg per grenade", barterValue: "GG15", streetPrice: 30, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:tear-gas"] },
      { id: "ordnance-ammo:40x46mm:he", name: "40x46mm HE", source: sources(265), damage: explosiveDamage(8, 5, 8, 4), weightText: "0.2 kg per grenade", barterValue: "GG15", streetPrice: 30, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"] },
      { id: "ordnance-ammo:40x46mm:hedp", name: "40x46mm HEDP", source: sources(265), damage: explosiveDamage(15, 5, 8, 4), weightText: "0.2 kg per grenade", barterValue: "GG20", streetPrice: 40, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:dual-purpose"] },
      { id: "ordnance-ammo:40x46mm:illum", name: "40x46mm Illum", source: sources(265), damageText: "-", effects: ["Radius 100 m", "1 minute"], weightText: "0.2 kg per grenade", barterValue: "GG10", streetPrice: 20, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:illumination"] },
      { id: "ordnance-ammo:40x46mm:stun", name: "40x46mm Stun", source: sources(265), damage: directDamage(3), weightText: "0.2 kg per grenade", barterValue: "GG15", streetPrice: 25, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:stun"] },
    ],
  },
  {
    id: "ordnance:launcher:ag36-m320:40x46mm",
    name: "AG36/M320",
    category: "underbarrel-grenade-launcher",
    source: sources(264),
    caliber: "40x46mm",
    capacity: "1 (single-shot)",
    range: "M/O",
    rateOfFire: "S",
    speed: "1 + rifle",
    bulk: 2,
    weightText: "1.5 kg",
    barterValue: "GG1,750",
    streetPrice: 3500,
    description: "German-pattern underbarrel launcher family used by multiple NATO countries.",
    traits: ["ordnance:grenade-launcher", "ordnance:underbarrel", "ordnance:ubgl-speed-plus-host-1"],
  },
  {
    id: "ordnance:launcher:gp-30:40mm-russian",
    name: "GP-30",
    category: "underbarrel-grenade-launcher",
    source: sources(264),
    caliber: "40mm Russian",
    capacity: "1 (single-shot)",
    range: "T/O",
    rateOfFire: "S",
    speed: "1 + rifle",
    bulk: 2,
    weightText: "1.3 kg",
    barterValue: "GG1,500",
    streetPrice: 3000,
    description: "Russian underbarrel launcher compatible with AK-pattern rifles.",
    traits: ["ordnance:grenade-launcher", "ordnance:underbarrel", "ordnance:ubgl-speed-plus-host-1"],
    ammoOptions: [
      {
        id: "ordnance-ammo:40mm-russian:chem-smoke",
        name: "40mm Russian Chem (Smoke)",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 5 m"],
        weightText: "0.3 kg per grenade",
        barterValue: "GG10",
        streetPrice: 20,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:smoke"],
      },
      {
        id: "ordnance-ammo:40mm-russian:chem-tear-gas",
        name: "40mm Russian Chem (Tear Gas)",
        source: sources(265),
        damageText: "-",
        effects: ["Radius 5 m"],
        weightText: "0.3 kg per grenade",
        barterValue: "GG15",
        streetPrice: 30,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:tear-gas"],
      },
      {
        id: "ordnance-ammo:40mm-russian:he",
        name: "40mm Russian HE",
        source: sources(265),
        damage: explosiveDamage(4, 7, 2, 7),
        weightText: "0.3 kg per grenade",
        barterValue: "GG15",
        streetPrice: 30,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"],
      },
      {
        id: "ordnance-ammo:40mm-russian:stun",
        name: "40mm Russian Stun",
        source: sources(265),
        damage: directDamage(4),
        weightText: "0.3 kg per grenade",
        barterValue: "GG15",
        streetPrice: 25,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:stun"],
      },
    ],
  },
  {
    id: "ordnance:launcher:m203:40x46mm",
    name: "M203",
    category: "underbarrel-grenade-launcher",
    source: sources(264),
    caliber: "40x46mm",
    capacity: "1 (single-shot)",
    range: "M/O",
    rateOfFire: "S",
    speed: "1 + rifle",
    bulk: 2,
    weightText: "1.4 kg",
    barterValue: "GG225",
    streetPrice: 600,
    description: "Older American underbarrel launcher whose loading cycle is slower than later designs.",
    traits: ["ordnance:grenade-launcher", "ordnance:underbarrel", "ordnance:ubgl-speed-plus-host-1", "ordnance:reload:6-ticks"],
  },
  {
    id: "ordnance:agl:ags-17:30mm",
    name: "AGS-17",
    category: "automatic-grenade-launcher",
    source: sources(264),
    caliber: "30mm",
    capacity: "30-round belt",
    range: "M/Ex",
    rateOfFire: "S/B3",
    speed: "6/9/14",
    recoil: 17,
    bulk: 6,
    weightText: "18 kg",
    barterValue: "GG4,500",
    streetPrice: 9000,
    description: "Earlier Soviet automatic grenade launcher intended for tripod or vehicle mounting.",
    traits: ["ordnance:automatic-grenade-launcher", "ordnance:crew-served", "ordnance:requires-emplacement"],
    ammoOptions: [
      {
        id: "ordnance-ammo:30mm:he",
        name: "30mm HE",
        source: sources(265),
        damage: explosiveDamage(8, 6, 8, 5),
        weightText: "0.4 kg per grenade",
        barterValue: "GG15",
        streetPrice: 30,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"],
      },
    ],
  },
  {
    id: "ordnance:agl:ags-30:30mm",
    name: "AGS-30",
    category: "automatic-grenade-launcher",
    source: sources(264),
    caliber: "30mm",
    capacity: "30-round belt",
    range: "M/Ex",
    rateOfFire: "S/B3",
    speed: "6/9/14",
    recoil: 18,
    bulk: 6,
    weightText: "16 kg",
    barterValue: "GG7,000",
    streetPrice: 14000,
    description: "Lighter successor to the AGS-17 with its own dedicated tripod.",
    traits: ["ordnance:automatic-grenade-launcher", "ordnance:crew-served", "ordnance:requires-emplacement"],
    ammoOptions: [{ id: "ordnance-ammo:30mm:he", name: "30mm HE", source: sources(265), damage: explosiveDamage(8, 6, 8, 5), weightText: "0.4 kg per grenade", barterValue: "GG15", streetPrice: 30, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"] }],
  },
  {
    id: "ordnance:agl:mk-19:40x53mm-hv",
    name: "Mk. 19",
    category: "automatic-grenade-launcher",
    source: sources(264),
    caliber: "40x53mm HV",
    capacity: "48-round belt",
    range: "M/Ex",
    rateOfFire: "S/B3",
    speed: "7/11/16",
    recoil: 15,
    bulk: 7,
    weightText: "35 kg",
    barterValue: "GG8,000",
    streetPrice: 16000,
    description: "Heavy American automatic grenade launcher used from fixed positions and vehicle mounts.",
    traits: ["ordnance:automatic-grenade-launcher", "ordnance:crew-served", "ordnance:requires-emplacement"],
    ammoOptions: [
      {
        id: "ordnance-ammo:40x53mm-hv:he",
        name: "40x53mm HV HE",
        source: sources(265),
        damage: explosiveDamage(8, 5, 8, 4),
        weightText: "0.4 kg per grenade",
        barterValue: "GG20",
        streetPrice: 40,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"],
      },
      {
        id: "ordnance-ammo:40x53mm-hv:hedp",
        name: "40x53mm HV HEDP",
        source: sources(265),
        damage: explosiveDamage(15, 5, 8, 4),
        weightText: "0.4 kg per grenade",
        barterValue: "GG25",
        streetPrice: 50,
        traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:dual-purpose"],
      },
    ],
  },
  {
    id: "ordnance:agl:mk-47:40x53mm-hv",
    name: "Mk. 47",
    category: "automatic-grenade-launcher",
    source: sources(264),
    caliber: "40x53mm HV",
    capacity: "48-round belt",
    range: "M/Ex",
    rateOfFire: "S/B2",
    speed: "6/9/14",
    recoil: 21,
    bulk: 6,
    weightText: "18 kg",
    barterValue: "GG12,000",
    streetPrice: 24000,
    description: "Lighter American successor to the Mk. 19.",
    traits: ["ordnance:automatic-grenade-launcher", "ordnance:crew-served", "ordnance:requires-emplacement"],
    ammoOptions: [
      { id: "ordnance-ammo:40x53mm-hv:he", name: "40x53mm HV HE", source: sources(265), damage: explosiveDamage(8, 5, 8, 4), weightText: "0.4 kg per grenade", barterValue: "GG20", streetPrice: 40, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:explosive"] },
      { id: "ordnance-ammo:40x53mm-hv:hedp", name: "40x53mm HV HEDP", source: sources(265), damage: explosiveDamage(15, 5, 8, 4), weightText: "0.4 kg per grenade", barterValue: "GG25", streetPrice: 50, traits: ["ordnance:grenade", "ordnance:not-hand-thrown", "ordnance:dual-purpose"] },
    ],
  },
  {
    id: "ordnance:rocket:at4",
    name: "AT4",
    category: "disposable-rocket-launcher",
    source: sources(264),
    caliber: "84mm",
    capacity: "1 prepackaged rocket",
    range: "T/O",
    rateOfFire: "S",
    speed: "4/6/9",
    bulk: 4,
    weightText: "6.7 kg",
    barterValue: "GG190 to GG310",
    streetPrice: 1500,
    description: "Disposable Swedish light support launcher used by NATO and partner forces.",
    traits: ["ordnance:rocket-launcher", "ordnance:disposable", "ordnance:single-shot"],
    ammoOptions: [
      { id: "ordnance-ammo:at4:he", name: "AT4 (HE)", source: sources(264), damage: explosiveDamage(18, 18, 18, 3), weightText: "Included in launcher", barterValue: "GG190", streetPrice: 1500, traits: ["ordnance:rocket", "ordnance:disposable"] },
      { id: "ordnance-ammo:at4:heat", name: "AT4 (HEAT)", source: sources(264), damage: explosiveDamage(70, 9, 9, 1), weightText: "Included in launcher", barterValue: "GG190", streetPrice: 1500, traits: ["ordnance:rocket", "ordnance:disposable", "ordnance:heat"] },
      { id: "ordnance-ammo:at4:heat-improved", name: "AT4 (HEAT, Improved)", source: sources(264), damage: explosiveDamage(90, 9, 9, 1), weightText: "Included in launcher", barterValue: "GG310", streetPrice: 2500, traits: ["ordnance:rocket", "ordnance:disposable", "ordnance:heat"] },
    ],
  },
  {
    id: "ordnance:rocket:m72-law",
    name: "M72 LAW",
    category: "disposable-rocket-launcher",
    source: sources(264),
    caliber: "66mm",
    capacity: "1 prepackaged rocket",
    range: "T/O",
    rateOfFire: "S",
    speed: "3/5/7",
    bulk: 3,
    weightText: "2.5 kg",
    barterValue: "GG110",
    streetPrice: 900,
    description: "Legacy American disposable antitank rocket launcher.",
    traits: ["ordnance:rocket-launcher", "ordnance:disposable", "ordnance:single-shot"],
    ammoOptions: [
      { id: "ordnance-ammo:m72-law:heat", name: "M72 LAW (HEAT)", source: sources(264), damage: explosiveDamage(55, 7, 7, 1), weightText: "Included in launcher", barterValue: "GG110", streetPrice: 900, traits: ["ordnance:rocket", "ordnance:disposable", "ordnance:heat"] },
    ],
  },
  {
    id: "ordnance:rocket:rpg-18",
    name: "RPG-18",
    category: "disposable-rocket-launcher",
    source: sources(264),
    caliber: "64mm",
    capacity: "1 prepackaged rocket",
    range: "T/O",
    rateOfFire: "S",
    speed: "3/5/7",
    bulk: 3,
    weightText: "2.6 kg",
    barterValue: "GG100",
    streetPrice: 800,
    description: "Disposable Soviet launcher derived closely from the M72 concept.",
    traits: ["ordnance:rocket-launcher", "ordnance:disposable", "ordnance:single-shot"],
    ammoOptions: [{ id: "ordnance-ammo:rpg-18:heat", name: "RPG-18 (HEAT)", source: sources(264), damage: explosiveDamage(60, 7, 7, 1), weightText: "Included in launcher", barterValue: "GG100", streetPrice: 800, traits: ["ordnance:rocket", "ordnance:disposable", "ordnance:heat"] }],
  },
  {
    id: "ordnance:rocket:rpg-22",
    name: "RPG-22",
    category: "disposable-rocket-launcher",
    source: sources(264),
    caliber: "72.5mm",
    capacity: "1 prepackaged rocket",
    range: "T/O",
    rateOfFire: "S",
    speed: "3/5/7",
    bulk: 3,
    weightText: "2.8 kg",
    barterValue: "GG125",
    streetPrice: 1000,
    description: "Scaled-up Soviet disposable launcher with improved anti-armor performance.",
    traits: ["ordnance:rocket-launcher", "ordnance:disposable", "ordnance:single-shot"],
    ammoOptions: [{ id: "ordnance-ammo:rpg-22:heat", name: "RPG-22 (HEAT)", source: sources(264), damage: explosiveDamage(65, 7, 7, 1), weightText: "Included in launcher", barterValue: "GG125", streetPrice: 1000, traits: ["ordnance:rocket", "ordnance:disposable", "ordnance:heat"] }],
  },
  {
    id: "ordnance:rocket:carl-gustav",
    name: "Carl Gustav",
    category: "reusable-rocket-launcher",
    source: sources(264, 265),
    caliber: "84mm",
    capacity: "1 (single-shot)",
    range: "T/O",
    rateOfFire: "S",
    speed: "4/7/10",
    bulk: 4,
    weightText: "8.5 kg",
    barterValue: "GG1,350",
    streetPrice: 5400,
    description: "Long-lived Swedish reusable launcher with an integral Mag-1 optic.",
    traits: ["ordnance:rocket-launcher", "ordnance:reusable", "vision:mag-1"],
    ammoOptions: [
      { id: "ordnance-ammo:carl-gustav:he", name: "Carl Gustav HE", source: sources(265), damage: explosiveDamage(20, 20, 20, 3), weightText: "3.1 kg per rocket", barterValue: "GG80", streetPrice: 800, traits: ["ordnance:rocket", "ordnance:explosive"] },
      { id: "ordnance-ammo:carl-gustav:heat", name: "Carl Gustav HEAT", source: sources(265), damage: explosiveDamage(80, 5, 10, 1), weightText: "4 kg per rocket", barterValue: "GG150", streetPrice: 1500, traits: ["ordnance:rocket", "ordnance:heat"] },
      { id: "ordnance-ammo:carl-gustav:hedp", name: "Carl Gustav HEDP", source: sources(265), damage: explosiveDamage(25, 20, 20, 2), weightText: "3.3 kg per rocket", barterValue: "GG120", streetPrice: 1200, traits: ["ordnance:rocket", "ordnance:dual-purpose"] },
      { id: "ordnance-ammo:carl-gustav:chem-smoke", name: "Carl Gustav Chem (Smoke)", source: sources(265), damageText: "N/A", effects: ["Radius 20 m"], weightText: "3.1 kg per rocket", barterValue: "GG60", streetPrice: 600, traits: ["ordnance:rocket", "ordnance:smoke"] },
      { id: "ordnance-ammo:carl-gustav:illum", name: "Carl Gustav Illum", source: sources(265), damageText: "N/A", effects: ["Radius 400 m", "1 minute"], weightText: "3.1 kg per rocket", barterValue: "GG75", streetPrice: 750, traits: ["ordnance:rocket", "ordnance:illumination"] },
    ],
  },
  {
    id: "ordnance:rocket:rpg-7",
    name: "RPG-7",
    category: "reusable-rocket-launcher",
    source: sources(264, 265),
    caliber: "40mm launch tube",
    capacity: "1 (single-shot)",
    range: "CQB/O",
    rateOfFire: "S",
    speed: "4/6/9",
    bulk: 4,
    weightText: "7 kg",
    barterValue: "GG150",
    streetPrice: 600,
    description: "Iconic Soviet reusable antitank launcher used worldwide.",
    traits: ["ordnance:rocket-launcher", "ordnance:reusable"],
    ammoOptions: [
      { id: "ordnance-ammo:rpg-7:frag", name: "RPG-7 Frag", source: sources(265), damage: explosiveDamage(14, 15, 4, 6), weightText: "2 kg per rocket", barterValue: "GG30", streetPrice: 300, traits: ["ordnance:rocket", "ordnance:explosive"] },
      { id: "ordnance-ammo:rpg-7:heat", name: "RPG-7 HEAT", source: sources(265), damage: explosiveDamage(55, 4, 7, 2), weightText: "2.6 kg per rocket", barterValue: "GG30", streetPrice: 300, traits: ["ordnance:rocket", "ordnance:heat"] },
      { id: "ordnance-ammo:rpg-7:heat-enhanced", name: "RPG-7 HEAT, Enhanced", source: sources(265), damage: explosiveDamage(110, 4, 10, 1), weightText: "4.5 kg per rocket", barterValue: "GG75", streetPrice: 750, traits: ["ordnance:rocket", "ordnance:heat", "ordnance:tandem-charge"] },
    ],
  },
  {
    id: "ordnance:rocket:rpg-29",
    name: "RPG-29",
    category: "reusable-rocket-launcher",
    source: sources(264, 265),
    caliber: "105mm",
    capacity: "1 (single-shot)",
    range: "T/O",
    rateOfFire: "S",
    speed: "5/8/11",
    bulk: 5,
    weightText: "12.1 kg",
    barterValue: "GG900",
    streetPrice: 3600,
    description: "Heavy Russian reusable launcher firing tandem-charge anti-armor rockets.",
    traits: ["ordnance:rocket-launcher", "ordnance:reusable"],
    ammoOptions: [
      { id: "ordnance-ammo:rpg-29:heat", name: "RPG-29 HEAT", source: sources(265), damage: explosiveDamage(135, 6, 13, 1), weightText: "6.7 kg per rocket", barterValue: "GG110", streetPrice: 1100, traits: ["ordnance:rocket", "ordnance:heat", "ordnance:tandem-charge"] },
    ],
  },
  {
    id: "ordnance:atgm:at-7-at-13",
    name: "AT-7/AT-13",
    category: "guided-missile-launcher",
    source: sources(264, 265, 266),
    caliber: "Per missile",
    capacity: "1 (single-shot)",
    range: "Per ammunition type",
    rateOfFire: "S",
    speed: "7/11/16",
    bulk: 7,
    weightText: "10.2 kg launcher with tripod",
    barterValue: "GG15,000",
    streetPrice: 120000,
    description: "Wire-guided Soviet launcher compatible with AT-7 and AT-13 missiles.",
    traits: ["ordnance:guided-missile-launcher", "ordnance:wire-guided", "ordnance:tripod-included"],
    notes: ["AT-7 missiles use range M/S. AT-13 missiles use range O/Ex."],
    ammoOptions: [
      { id: "ordnance-ammo:at-7:heat", name: "AT-7 (HEAT)", source: sources(265), damage: explosiveDamage(75, 7, 8, 2), weightText: "6.3 kg per missile", barterValue: "GG750", streetPrice: 6000, traits: ["ordnance:missile", "ordnance:wire-guided", "ordnance:heat"], notes: ["Use range M/S when firing this missile."] },
      { id: "ordnance-ammo:at-13:heat", name: "AT-13 (HEAT)", source: sources(265), damage: explosiveDamage(165, 20, 20, 3), weightText: "13.8 kg per missile", barterValue: "GG1,900", streetPrice: 15000, traits: ["ordnance:missile", "ordnance:wire-guided", "ordnance:heat"], notes: ["Use range O/Ex when firing this missile."] },
    ],
  },
  {
    id: "ordnance:atgm:at-14",
    name: "AT-14",
    category: "guided-missile-launcher",
    source: sources(264, 265, 266),
    caliber: "Per missile",
    capacity: "1 (single-shot)",
    range: "O/Ex",
    rateOfFire: "S",
    speed: "8/12/18",
    bulk: 8,
    weightText: "37 kg launcher system; infantry set also uses 11 kg designator and a heavy tripod",
    barterValue: "GG25,000",
    streetPrice: 200000,
    description: "Heavy laser-homing ATGM system replacing earlier Soviet infantry designs.",
    traits: ["ordnance:guided-missile-launcher", "ordnance:laser-homing"],
    ammoOptions: [
      { id: "ordnance-ammo:at-14:heat", name: "AT-14 (HEAT)", source: sources(265), damage: explosiveDamage(185, 24, 24, 3), weightText: "27 kg per missile", barterValue: "GG2,500", streetPrice: 20000, traits: ["ordnance:missile", "ordnance:laser-homing", "ordnance:heat"] },
    ],
  },
  {
    id: "ordnance:atgm:milan",
    name: "MILAN",
    category: "guided-missile-launcher",
    source: sources(264, 266),
    caliber: "Per missile",
    capacity: "1 (single-shot)",
    range: "O/Ex",
    rateOfFire: "S",
    speed: "7/11/16",
    bulk: 7,
    weightText: "16.4 kg launcher with tripod",
    barterValue: "GG19,000",
    streetPrice: 150000,
    description: "European wire-guided ATGM launcher exported worldwide.",
    traits: ["ordnance:guided-missile-launcher", "ordnance:wire-guided", "ordnance:tripod-included"],
    ammoOptions: [
      { id: "ordnance-ammo:milan-2:heat", name: "MILAN-2 (HEAT)", source: sources(265), damage: explosiveDamage(140, 18, 18, 3), weightText: "6.7 kg per missile", barterValue: "GG1,300", streetPrice: 10000, traits: ["ordnance:missile", "ordnance:wire-guided", "ordnance:heat"] },
      { id: "ordnance-ammo:milan-3:heat", name: "MILAN-3 (HEAT)", source: sources(265), damage: explosiveDamage(165, 20, 20, 3), weightText: "7.2 kg per missile", barterValue: "GG1,900", streetPrice: 15000, traits: ["ordnance:missile", "ordnance:wire-guided", "ordnance:heat"] },
    ],
  },
  {
    id: "ordnance:atgm:tow",
    name: "TOW",
    category: "guided-missile-launcher",
    source: sources(264, 266),
    caliber: "Per missile",
    capacity: "1 (single-shot)",
    range: "O/Ex",
    rateOfFire: "S",
    speed: "8/12/18",
    bulk: 8,
    weightText: "73 kg launcher system; requires heavy tripod or vehicle mount",
    barterValue: "GG28,000",
    streetPrice: 225000,
    description: "American wire-guided BGM-71 launcher family used by infantry and vehicle mounts.",
    traits: ["ordnance:guided-missile-launcher", "ordnance:wire-guided"],
    ammoOptions: [
      { id: "ordnance-ammo:tow-2a:heat", name: "TOW 2A (HEAT)", source: sources(265), damage: explosiveDamage(165, 20, 20, 3), weightText: "22.6 kg per missile", barterValue: "GG1,900", streetPrice: 15000, traits: ["ordnance:missile", "ordnance:wire-guided", "ordnance:heat"] },
      { id: "ordnance-ammo:tow-2b:heat", name: "TOW 2B (HEAT)", source: sources(265, 266), damage: explosiveDamage(130, 16, 16, 3), weightText: "22.6 kg per missile", barterValue: "GG2,200", streetPrice: 17000, traits: ["ordnance:missile", "ordnance:wire-guided", "ordnance:heat", "ordnance:top-attack"], notes: ["On a success with margin 5+, roll 1d6: 1-4 hull rear, 5-6 turret rear."] },
    ],
  },
  {
    id: "ordnance:mortar:60mm",
    name: "60mm Mortar",
    category: "mortar",
    source: sources(264, 266),
    caliber: "60mm",
    capacity: "Muzzle-loaded",
    range: "IFR 3.5 km",
    rateOfFire: "S*",
    speed: "Operational",
    bulk: 6,
    weightText: "21 kg",
    barterValue: "GG3,000",
    streetPrice: 12000,
    description: "Light NATO-pattern mortar man-portable by a 3-person crew.",
    traits: ["ordnance:mortar", "ordnance:indirect-fire-only", "ordnance:crew-served"],
    notes: ["A normal 3-person crew may fire up to 6 rounds per operational action."],
    ammoOptions: [
      { id: "ordnance-ammo:60mm-mortar:he", name: "60mm Mortar HE", source: sources(266), damage: explosiveDamage(9, 10, 9, 7), weightText: "1.7 kg per shell", barterValue: "GG50", streetPrice: 500, traits: ["ordnance:mortar-shell", "ordnance:explosive"] },
      { id: "ordnance-ammo:60mm-mortar:illum", name: "60mm Mortar Illum", source: sources(266), damageText: "N/A", effects: ["Radius 400 m", "1 minute"], weightText: "1.7 kg per shell", barterValue: "GG60", streetPrice: 600, traits: ["ordnance:mortar-shell", "ordnance:illumination"] },
      { id: "ordnance-ammo:60mm-mortar:wp", name: "60mm Mortar WP", source: sources(266), damage: explosiveDamage(4, 6, 4, 6), weightText: "1.7 kg per shell", barterValue: "GG75", streetPrice: 750, traits: ["ordnance:mortar-shell", "ordnance:white-phosphorus"] },
    ],
  },
  {
    id: "ordnance:mortar:81mm",
    name: "81mm Mortar",
    category: "mortar",
    source: sources(264, 266),
    caliber: "81mm",
    capacity: "Muzzle-loaded",
    range: "IFR 5.5 km",
    rateOfFire: "S*",
    speed: "Operational",
    bulk: 7,
    weightText: "42.2 kg",
    barterValue: "GG4,250",
    streetPrice: 17000,
    description: "Medium NATO mortar usually served by a 5-person crew.",
    traits: ["ordnance:mortar", "ordnance:indirect-fire-only", "ordnance:crew-served"],
    notes: ["Maximum rate of fire is 3 rounds per operational action with a full 5-person crew."],
    ammoOptions: [
      { id: "ordnance-ammo:81mm-mortar:he", name: "81mm Mortar HE", source: sources(266), damage: explosiveDamage(14, 14, 14, 7), weightText: "4 kg per shell", barterValue: "GG60", streetPrice: 600, traits: ["ordnance:mortar-shell", "ordnance:explosive"] },
      { id: "ordnance-ammo:81mm-mortar:illum", name: "81mm Mortar Illum", source: sources(266), damageText: "N/A", effects: ["Radius 1 km", "1 minute"], weightText: "4 kg per shell", barterValue: "GG75", streetPrice: 750, traits: ["ordnance:mortar-shell", "ordnance:illumination"] },
      { id: "ordnance-ammo:81mm-mortar:wp", name: "81mm Mortar WP", source: sources(266), damage: explosiveDamage(4, 10, 4, 6), weightText: "4.7 kg per shell", barterValue: "GG90", streetPrice: 900, traits: ["ordnance:mortar-shell", "ordnance:white-phosphorus"] },
    ],
  },
  {
    id: "ordnance:mortar:82mm",
    name: "82mm Mortar",
    category: "mortar",
    source: sources(264, 266),
    caliber: "82mm",
    capacity: "Muzzle-loaded",
    range: "IFR 3 km",
    rateOfFire: "S*",
    speed: "Operational",
    bulk: 7,
    weightText: "56 kg",
    barterValue: "GG3,500",
    streetPrice: 14000,
    description: "Legacy Soviet mortar still common in reserve stocks and insurgent use.",
    traits: ["ordnance:mortar", "ordnance:indirect-fire-only", "ordnance:crew-served"],
    notes: ["Maximum rate of fire is 3 rounds per operational action with a full 5-person crew."],
    ammoOptions: [
      { id: "ordnance-ammo:82mm-mortar:he", name: "82mm Mortar HE", source: sources(266), damage: explosiveDamage(14, 14, 14, 7), weightText: "4 kg per shell", barterValue: "GG60", streetPrice: 600, traits: ["ordnance:mortar-shell", "ordnance:explosive"] },
      { id: "ordnance-ammo:82mm-mortar:illum", name: "82mm Mortar Illum", source: sources(266), damageText: "N/A", effects: ["Radius 1 km", "1 minute"], weightText: "4 kg per shell", barterValue: "GG75", streetPrice: 750, traits: ["ordnance:mortar-shell", "ordnance:illumination"] },
      { id: "ordnance-ammo:82mm-mortar:wp", name: "82mm Mortar WP", source: sources(266), damage: explosiveDamage(4, 10, 4, 6), weightText: "4.7 kg per shell", barterValue: "GG90", streetPrice: 900, traits: ["ordnance:mortar-shell", "ordnance:white-phosphorus"] },
    ],
  },
  {
    id: "ordnance:mortar:120mm",
    name: "120mm Mortar",
    category: "mortar",
    source: sources(264, 266),
    caliber: "120mm",
    capacity: "Muzzle-loaded",
    range: "IFR 7.5 km",
    rateOfFire: "S*",
    speed: "Operational",
    bulk: 9,
    weightText: "145 kg",
    barterValue: "GG5,500",
    streetPrice: 22000,
    description: "Heavy mortar normally towed or vehicle-mounted but dismountable for fixed firing positions.",
    traits: ["ordnance:mortar", "ordnance:indirect-fire-only", "ordnance:crew-served"],
    notes: ["Maximum rate of fire is 2 rounds per operational action with a full 5-person crew."],
    ammoOptions: [
      { id: "ordnance-ammo:120mm-mortar:he", name: "120mm Mortar HE", source: sources(266), damage: explosiveDamage(28, 22, 28, 8), weightText: "13.7 kg per shell", barterValue: "GG90", streetPrice: 900, traits: ["ordnance:mortar-shell", "ordnance:explosive"] },
      { id: "ordnance-ammo:120mm-mortar:illum", name: "120mm Mortar Illum", source: sources(266), damageText: "N/A", effects: ["Radius 1.5 km", "1 minute"], weightText: "13.7 kg per shell", barterValue: "GG120", streetPrice: 1200, traits: ["ordnance:mortar-shell", "ordnance:illumination"] },
      { id: "ordnance-ammo:120mm-mortar:wp", name: "120mm Mortar WP", source: sources(266), damage: explosiveDamage(5, 18, 5, 7), weightText: "13.7 kg per shell", barterValue: "GG140", streetPrice: 1400, traits: ["ordnance:mortar-shell", "ordnance:white-phosphorus"] },
    ],
  },
];

export const LIGHT_SUPPORT_WEAPONS_BY_ID = Object.fromEntries(
  LIGHT_SUPPORT_WEAPONS.map((entry) => [entry.id, entry]),
) as Record<string, LightSupportWeaponSystem>;

export const LIGHT_SUPPORT_WEAPONS_RULES: LightSupportWeaponReferenceRule[] = [
  {
    id: "ordnance-rule:launcher-grenades",
    name: "Launcher Grenade Handling",
    source: sources(264),
    traits: [
      "ordnance:not-hand-thrown",
      "ordnance:minimum-arming-distance:tight",
    ],
    notes: [
      "Hand grenades are not valid ammunition for grenade launchers.",
      "Launcher grenades cannot be armed by hand and thrown.",
      "Launcher grenades will not detonate against targets closer than Tight range.",
    ],
  },
  {
    id: "ordnance-rule:underbarrel-launchers",
    name: "Underbarrel Launcher Host Modifiers",
    source: sources(264),
    traits: [
      "ordnance:ubgl-bulk-plus-1-to-host",
      "ordnance:ubgl-recoil-minus-2-to-host",
      "ordnance:ubgl-speed-plus-host-1",
    ],
    notes: [
      "Mounting an underbarrel grenade launcher increases the rifle's Bulk by 1.",
      "Mounting an underbarrel grenade launcher reduces the rifle's Recoil by 2.",
      "The launcher's Speed is always 1 plus the host rifle's Speed.",
    ],
  },
  {
    id: "ordnance-rule:command-guidance",
    name: "Command Guidance",
    source: sources(266),
    traits: [
      "ordnance:guided-missile:command-guided",
      "ordnance:guided-missile:guide-action:1-tick",
      "ordnance:guided-missile:travels-1-range-band-per-tick",
    ],
    notes: [
      "A command-guided missile requires a character to maintain guidance from launch until impact.",
      "Guiding a missile uses a dedicated 1-tick Guide action and the guide may take no other actions during flight.",
      "Do not make the attack check until the missile reaches the target. If guidance is interrupted first, the attack automatically fails.",
    ],
  },
  {
    id: "ordnance-rule:mortar-disassembly",
    name: "Mortar Disassembly",
    source: sources(266),
    traits: ["ordnance:mortar:disassembly:1-operational-action-per-5kg"],
    notes: [
      "Disassembly or reassembly takes one operational action per 5 kg of total mortar weight.",
      "60mm mortar parts: baseplate 6.5 kg, bipod 6.9 kg, sight 1.1 kg, tube 6.5 kg.",
      "81mm mortar parts: baseplate 13.1 kg, bipod 12.2 kg, sight 1.1 kg, tube 15.8 kg.",
      "82mm mortar parts: baseplate 15 kg, bipod 22 kg, tube 19 kg.",
      "120mm mortar parts: baseplate 61.7 kg, bipod 31.8 kg, sight 1.1 kg, tube 50 kg.",
    ],
  },
];