"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SHELTER_ITEMS = void 0;
const inventory_1 = require("../inventory");
const SRC = "Source: Twilight 2013 Core OEF PDF p.224";
exports.SHELTER_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:bedroll",
        name: "Bedroll",
        weight: 4,
        tags: ["survival", "shelter", "sleeping"],
        barterValue: "GG0.25",
        streetPrice: 25,
        traits: ["shelter:capacity:1", "weather-rated:mild"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:bivouac-bag",
        name: "Bivouac Bag",
        weight: 0.3,
        tags: ["survival", "shelter", "sleeping"],
        barterValue: "GG45",
        streetPrice: 180,
        traits: ["shelter:capacity:1", "hot-weather-sleep"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:camp-bed",
        name: "Camp Bed",
        weight: 5.2,
        tags: ["survival", "shelter", "camp-furniture"],
        barterValue: "GG3.75",
        streetPrice: 75,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:camp-chair",
        name: "Camp Chair",
        weight: 3.1,
        tags: ["survival", "shelter", "camp-furniture"],
        barterValue: "GG1",
        streetPrice: 20,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:camp-stool",
        name: "Camp Stool",
        weight: 0.7,
        tags: ["survival", "shelter", "camp-furniture"],
        barterValue: "GG1",
        streetPrice: 20,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:camp-table",
        name: "Camp Table",
        weight: 4.5,
        tags: ["survival", "shelter", "camp-furniture"],
        barterValue: "GG2.75",
        streetPrice: 55,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:emergency-blanket",
        name: "Emergency Blanket",
        weight: 0.3,
        tags: ["survival", "shelter", "emergency"],
        barterValue: "GG1.2",
        streetPrice: 12,
        traits: ["improvised-shelter"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:emergency-blanket-one-use",
        name: "Emergency Blanket, One-Use",
        weight: 0,
        tags: ["survival", "shelter", "emergency"],
        barterValue: "GG0.2",
        streetPrice: 4,
        traits: ["improvised-shelter", "single-use"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:hammock",
        name: "Hammock",
        weight: 0.4,
        tags: ["survival", "shelter", "sleeping"],
        barterValue: "GG2",
        streetPrice: 40,
        traits: ["shelter:capacity:1", "hot-weather-sleep"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:shelter-half",
        name: "Shelter Half",
        weight: 1.3,
        tags: ["survival", "shelter"],
        barterValue: "GG10",
        streetPrice: 40,
        traits: ["shelter:capacity:1"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:sleeping-bag-5-season",
        name: "Sleeping Bag, 5-Season",
        weight: 2.1,
        tags: ["survival", "shelter", "sleeping"],
        barterValue: "GG40",
        streetPrice: 160,
        traits: ["shelter:capacity:1", "weather-rated:cold"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:sleeping-bag-temperate",
        name: "Sleeping Bag, Temperate",
        weight: 1,
        tags: ["survival", "shelter", "sleeping"],
        barterValue: "GG15",
        streetPrice: 60,
        traits: ["shelter:capacity:1", "weather-rated:mild"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-civilian-1man",
        name: "Tent, Civilian, 1-Man",
        weight: 1.9,
        tags: ["survival", "shelter", "tent", "tent-civilian"],
        barterValue: "GG100",
        streetPrice: 160,
        traits: ["shelter:capacity:1"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-civilian-2man",
        name: "Tent, Civilian, 2-Man",
        weight: 2.2,
        tags: ["survival", "shelter", "tent", "tent-civilian"],
        barterValue: "GG87.5",
        streetPrice: 140,
        traits: ["shelter:capacity:2"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-civilian-3man",
        name: "Tent, Civilian, 3-Man",
        weight: 6.9,
        tags: ["survival", "shelter", "tent", "tent-civilian"],
        barterValue: "GG75",
        streetPrice: 120,
        traits: ["shelter:capacity:3"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-civilian-4man",
        name: "Tent, Civilian, 4-Man",
        weight: 10,
        tags: ["survival", "shelter", "tent", "tent-civilian"],
        barterValue: "GG130",
        streetPrice: 210,
        traits: ["shelter:capacity:4"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-civilian-6man",
        name: "Tent, Civilian, 6-Man",
        weight: 19,
        tags: ["survival", "shelter", "tent", "tent-civilian"],
        barterValue: "GG295",
        streetPrice: 470,
        traits: ["shelter:capacity:6"],
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-military-small",
        name: "Tent, Military, Small",
        weight: 60,
        tags: ["survival", "shelter", "tent", "tent-military"],
        barterValue: "GG700",
        streetPrice: 1400,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "survival:shelter:tent-military-large",
        name: "Tent, Military, Large",
        weight: 110,
        tags: ["survival", "shelter", "tent", "tent-military"],
        barterValue: "GG950",
        streetPrice: 1900,
        traits: ["linkable-tent"],
        source: [SRC],
    }),
];
