"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HAND_TOOLS = void 0;
const inventory_1 = require("../inventory");
const SRC = "Source: Twilight 2013 Core OEF PDF p.232";
exports.HAND_TOOLS = [
    (0, inventory_1.createItemDefinition)({
        id: "tool:basic-hand-tools",
        name: "Basic Hand Tools",
        weight: 20,
        tags: ["tool", "hand-tool"],
        barterValue: "GG20",
        streetPrice: 400,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:bolt-cutters",
        name: "Bolt Cutters",
        weight: 2.5,
        tags: ["tool", "hand-tool"],
        barterValue: "GG2.5",
        streetPrice: 50,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:construction-tools",
        name: "Construction Tools",
        weight: 40,
        tags: ["tool", "hand-tool", "construction"],
        barterValue: "GG50",
        streetPrice: 400,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:crowbar",
        name: "Crowbar",
        weight: 2.4,
        tags: ["tool", "hand-tool", "prying"],
        barterValue: "GG0.2",
        streetPrice: 20,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:electricians-tools",
        name: "Electrician's Tools",
        weight: 10,
        tags: ["tool", "hand-tool", "electrical"],
        barterValue: "GG125",
        streetPrice: 500,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:electronics-tools",
        name: "Electronics Tools",
        weight: 2,
        tags: ["tool", "hand-tool", "electronics"],
        barterValue: "GG50",
        streetPrice: 200,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:mechanics-tools",
        name: "Mechanic's Tools",
        weight: 30,
        tags: ["tool", "hand-tool", "mechanic"],
        barterValue: "GG250",
        streetPrice: 1000,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:multitool",
        name: "Multitool",
        weight: 0.3,
        tags: ["tool", "hand-tool", "multitool"],
        barterValue: "GG6",
        streetPrice: 60,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:prybar",
        name: "Prybar",
        weight: 0.2,
        tags: ["tool", "hand-tool", "prying"],
        barterValue: "GG0.15",
        streetPrice: 15,
        source: [SRC],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "tool:swiss-army-knife",
        name: "Swiss Army Knife",
        weight: 0.15,
        tags: ["tool", "hand-tool", "knife"],
        barterValue: "GG2.5",
        streetPrice: 25,
        source: [SRC],
    }),
];
