import { defineVehicle, fuel, groundSpeed, movementMode } from "./shared";

const drive = (
  road: number,
  crossCountry: number,
  combatRoad: number,
  combatCrossCountry: number,
  modeFuel?: ReturnType<typeof fuel>,
) => movementMode("drive", "Drive", "ground", {
  travelSpeed: groundSpeed(road, crossCountry),
  combatSpeed: groundSpeed(combatRoad, combatCrossCountry),
  fuel: modeFuel,
});

const towed = (notes?: string[], traits?: string[]) =>
  movementMode("towed", "Towed", "towed", { notes, traits });

export const CIVILIAN_GROUND_VEHICLES = [
  defineVehicle({
    id: "vehicle:civilian:light-pickup",
    name: "Light Pickup",
    barterValue: "GG1,750",
    streetPrice: 14000,
    sourcePages: [284],
    tags: ["civilian", "ground", "pickup"],
    description: "A small utility truck whose bed cargo remains exposed and targetable.",
    vehicle: {
      configuration: "standard",
      suspension: "or",
      crew: { crew: 1, passengers: 2 },
      cargoKg: 500,
      cargoText: "500 kg in bed; exposed cargo may be targeted independently.",
      towingCapacityKg: 2000,
      weightKg: 1500,
      maintenanceHours: 4,
      movementModes: [drive(48, 8, 133, 22, fuel(["G"], 60, 4.6))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      systems: { sensors: "Headlights." },
      traits: ["vehicle:soft-skinned"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:heavy-pickup",
    name: "Heavy Pickup",
    barterValue: "GG2,750",
    streetPrice: 22000,
    sourcePages: [284],
    tags: ["civilian", "ground", "pickup"],
    description: "A larger pickup, represented here by a king-cab model with a second seat row.",
    vehicle: {
      configuration: "standard",
      suspension: "or",
      crew: { crew: 1, passengers: 4 },
      crewText: "King-cab model; standard cab is 1+2.",
      cargoKg: 750,
      cargoText: "750 kg; standard-cab model carries 1,000 kg.",
      towingCapacityKg: 4500,
      weightKg: 1900,
      maintenanceHours: 4,
      movementModes: [drive(48, 8, 133, 22, fuel(["G", "D"], 70, 9))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      systems: {
        sensors: "Headlights.",
        aux: "Self-recovery winch (3-ton limit, not suitable for towing).",
      },
      equipment: { selfRecoveryWinch: true },
      traits: ["vehicle:soft-skinned", "vehicle:winch:3-ton"],
      notes: ["Diesel version fuel consumption is 8 L/hr."],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:van",
    name: "Van",
    barterValue: "GG4,000",
    streetPrice: 32000,
    sourcePages: [284],
    tags: ["civilian", "ground", "van"],
    description: "A large cargo or passenger van built around a simple box-body chassis.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 1, passengers: 1 },
      crewText: "Cargo model: 1+1. Passenger model: 1+9.",
      cargoKg: 1500,
      cargoText: "Cargo model: 1.5 tons. Passenger model: 300 kg.",
      weightKg: 3500,
      maintenanceHours: 8,
      movementModes: [drive(53, 8, 147, 22, fuel(["G", "D"], 80, 11))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 2 } },
      systems: {
        sensors: "Headlights.",
        aux: "Civilian hydraulic tailgate lift (750 kg capacity).",
      },
      traits: ["vehicle:soft-skinned"],
      notes: ["Diesel version fuel consumption is 10 L/hr."],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:truck-2-5-ton",
    name: "Truck, 2.5-ton",
    barterValue: "GG4,000",
    streetPrice: 30000,
    sourcePages: [284],
    tags: ["civilian", "ground", "commercial-truck"],
    description: "A city delivery truck and the baseline chassis for many military cargo trucks.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 1, passengers: 2 },
      cargoKg: 2500,
      towingCapacityKg: 6000,
      weightKg: 6500,
      maintenanceHours: 8,
      movementModes: [drive(30, 5, 83, 14, fuel(["D"], 190, 24))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      systems: {
        sensors: "Headlights.",
        aux: "Civilian hydraulic tailgate lift (750 kg capacity).",
      },
      traits: ["vehicle:soft-skinned", "vehicle:truck-variant-compatible"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:truck-5-ton",
    name: "Truck, 5-ton",
    barterValue: "GG5,000",
    streetPrice: 40000,
    sourcePages: [285],
    tags: ["civilian", "ground", "commercial-truck"],
    description: "A heavier cargo truck available in civilian and military trims.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 1, passengers: 2 },
      cargoKg: 5000,
      towingCapacityKg: 11000,
      weightKg: 9000,
      maintenanceHours: 8,
      movementModes: [drive(30, 7, 83, 19, fuel(["D"], 240, 30))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      systems: {
        sensors: "Headlights.",
        aux: "Civilian hydraulic tailgate lift (1-ton capacity).",
      },
      traits: ["vehicle:soft-skinned", "vehicle:truck-variant-compatible"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:truck-10-ton",
    name: "Truck, 10-ton",
    barterValue: "GG7,500",
    streetPrice: 60000,
    sourcePages: [285],
    tags: ["civilian", "ground", "commercial-truck"],
    description: "A very heavy commercial cargo truck; the listed chassis already has off-road suspension.",
    vehicle: {
      configuration: "standard",
      suspension: "or",
      crew: { crew: 1, passengers: 2 },
      cargoKg: 10000,
      towingCapacityKg: 11000,
      weightKg: 19000,
      maintenanceHours: 8,
      movementModes: [drive(30, 7, 83, 19, fuel(["D"], 480, 60))],
      armor: { HF: { rating: 2 }, HS: { rating: 2 }, HR: { rating: 1 }, Susp: { rating: 4 } },
      systems: {
        sensors: "Headlights.",
        aux: "Cargo-handling crane (3-ton load limit).",
      },
      traits: ["vehicle:soft-skinned", "vehicle:truck-variant-compatible"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:bus-coach",
    name: "Bus, Coach",
    barterValue: "GG4,200",
    streetPrice: 420000,
    sourcePages: [285],
    tags: ["civilian", "ground", "bus"],
    description: "A standard long-distance coach built for intercity road transport.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 1, passengers: 45 },
      cargoKg: 3000,
      weightKg: 13500,
      maintenanceHours: 8,
      movementModes: [drive(43, 2, 120, 14, fuel(["D"], 480, 38))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      systems: {
        sensors: "Headlights.",
        aux: "Chemical toilet.",
      },
      traits: ["vehicle:soft-skinned"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:motor-home",
    name: "Motor Home",
    barterValue: "GG8,000",
    streetPrice: 70000,
    sourcePages: [285],
    tags: ["civilian", "ground", "motor-home"],
    description: "A medium family motor home built on a minibus chassis.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 1, passengers: 4 },
      cargoKg: 500,
      weightKg: 4000,
      maintenanceHours: 6,
      movementModes: [drive(35, 4, 97, 12, fuel(["D"], 100, 8))],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      systems: {
        sensors: "Civilian mapping GPS, headlights.",
        aux: "Diesel generator (1.25 kW, 2 L/hr); living quarters for 6 (chemical toilet, kitchenette, shower, water heater).",
      },
      traits: ["vehicle:soft-skinned", "vehicle:generator:1-25kw"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:semi-tractor",
    name: "Semi-Tractor",
    barterValue: "GG7,000",
    streetPrice: 125000,
    sourcePages: [286],
    tags: ["civilian", "ground", "semi-tractor"],
    description: "A long-haul sleeper tractor forming the backbone of heavy commercial road freight.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 1, passengers: 2 },
      cargoKg: 250,
      towingCapacityKg: 41000,
      weightKg: 11000,
      maintenanceHours: 12,
      movementModes: [drive(43, 4, 120, 11, fuel(["D"], 950, 17))],
      armor: { HF: { rating: 2 }, HS: { rating: 2 }, HR: { rating: 1 }, Susp: { rating: 4 } },
      systems: {
        comm: "Vehicular CB radio.",
        sensors: "Civilian mapping GPS, headlights.",
        aux: "Sleeping quarters for 2 (bunks and very small appliances).",
      },
      traits: ["vehicle:soft-skinned", "vehicle:semi-tractor"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:cargo-trailer-light",
    name: "Cargo Trailer, Light",
    barterValue: "GG250",
    streetPrice: 2500,
    sourcePages: [287],
    tags: ["civilian", "ground", "trailer"],
    description: "A light cargo trailer sized for towing behind pickups and SUVs.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 0 },
      cargoKg: 1000,
      weightKg: 200,
      maintenanceHours: 1,
      movementModes: [towed(["Uses the towing vehicle's speeds."], ["vehicle:trailer:cargo", "vehicle:trailer:fuel-consumption-doubles-when-towed"])],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 2 } },
      traits: ["vehicle:soft-skinned", "vehicle:towed"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:cargo-trailer-medium",
    name: "Cargo Trailer, Medium",
    barterValue: "GG400",
    streetPrice: 4000,
    sourcePages: [287],
    tags: ["civilian", "ground", "trailer"],
    description: "A medium cargo trailer intended for commercial truck towing.",
    vehicle: {
      configuration: "standard",
      suspension: "or",
      crew: { crew: 0 },
      cargoKg: 2500,
      weightKg: 600,
      maintenanceHours: 2,
      movementModes: [towed(["Uses the towing vehicle's speeds."], ["vehicle:trailer:cargo", "vehicle:trailer:fuel-consumption-doubles-when-towed"])],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 3 } },
      traits: ["vehicle:soft-skinned", "vehicle:towed"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:cargo-trailer-heavy",
    name: "Cargo Trailer, Heavy",
    barterValue: "GG800",
    streetPrice: 8000,
    sourcePages: [287],
    tags: ["civilian", "ground", "trailer"],
    description: "A heavy cargo trailer sized for large commercial vehicles.",
    vehicle: {
      configuration: "standard",
      suspension: "or",
      crew: { crew: 0 },
      cargoKg: 5000,
      weightKg: 1000,
      maintenanceHours: 2,
      movementModes: [towed(["Uses the towing vehicle's speeds."], ["vehicle:trailer:cargo", "vehicle:trailer:fuel-consumption-doubles-when-towed"])],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 4 } },
      traits: ["vehicle:soft-skinned", "vehicle:towed"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:semi-trailer-flatbed",
    name: "Semi Trailer, Flatbed",
    barterValue: "GG200",
    streetPrice: 20000,
    sourcePages: [287],
    tags: ["civilian", "ground", "semi-trailer"],
    description: "A heavy flatbed trailer meant to be pulled by a semi-tractor.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 0 },
      cargoKg: 35000,
      weightKg: 6000,
      maintenanceHours: 2,
      movementModes: [towed(["Tow fuel economy is already factored into the towing semi-tractor."], ["vehicle:semi-trailer"])],
      armor: { Susp: { rating: 4 } },
      traits: ["vehicle:towed"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:semi-trailer-tank",
    name: "Semi Trailer, Tank",
    barterValue: "GG500",
    streetPrice: 50000,
    sourcePages: [287],
    tags: ["civilian", "ground", "semi-trailer", "tanker"],
    description: "A heavy liquid tanker trailer for road freight.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 0 },
      cargoText: "27,000 liters.",
      weightKg: 7000,
      maintenanceHours: 4,
      movementModes: [towed(["Tow fuel economy is already factored into the towing semi-tractor."], ["vehicle:semi-trailer", "vehicle:tanker"])],
      armor: { HF: { rating: 2 }, HS: { rating: 2 }, HR: { rating: 2 }, Susp: { rating: 4 } },
      traits: ["vehicle:towed"],
    },
  }),
  defineVehicle({
    id: "vehicle:civilian:semi-trailer-van",
    name: "Semi Trailer, Van",
    barterValue: "GG300",
    streetPrice: 30000,
    sourcePages: [287],
    tags: ["civilian", "ground", "semi-trailer"],
    description: "An enclosed heavy trailer for dry cargo transport.",
    vehicle: {
      configuration: "standard",
      suspension: "std",
      crew: { crew: 0 },
      cargoKg: 30000,
      weightKg: 5000,
      maintenanceHours: 3,
      movementModes: [towed(["Tow fuel economy is already factored into the towing semi-tractor."], ["vehicle:semi-trailer"])],
      armor: { HF: { rating: 1 }, HS: { rating: 1 }, HR: { rating: 1 }, Susp: { rating: 4 } },
      traits: ["vehicle:towed"],
    },
  }),
];