import type { CombatActionDefinition, OperationalCombatActionKey } from '../catalogShared';
import { COMBAT_RULES_SOURCE } from '../catalogShared';

export const PAUSE_MOVEMENT_MULTIPLIER = 10;

export const OPERATIONAL_COMBAT_ACTIONS: Record<OperationalCombatActionKey, CombatActionDefinition> = {
	communicateComplex: {
		key: 'communicateComplex',
		name: 'Communicate (Complex)',
		cadence: 'operational',
		category: 'communication',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Negotiate, issue substantial orders, or make a focused radio call during a pause.',
		tags: ['speech', 'teamwork'],
		source: COMBAT_RULES_SOURCE,
	},
	donOrDoffClothing: {
		key: 'donOrDoffClothing',
		name: 'Don/Doff Clothing',
		cadence: 'operational',
		category: 'equipment',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Put on or remove one major clothing or gear grouping with care rather than panic.',
		tags: ['equipment', 'encumbrance'],
		source: COMBAT_RULES_SOURCE,
	},
	fieldRepair: {
		key: 'fieldRepair',
		name: 'Field Repair',
		cadence: 'operational',
		category: 'repair',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Apply emergency repair work to restore disabled gear or vehicle systems temporarily.',
		tags: ['repair', 'equipment'],
		source: COMBAT_RULES_SOURCE,
	},
	keepWatch: {
		key: 'keepWatch',
		name: 'Keep Watch',
		cadence: 'operational',
		category: 'observation',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Hold position and watch the enemy during the lull.',
		tags: ['awareness', 'overwatch'],
		source: COMBAT_RULES_SOURCE,
	},
	renderAid: {
		key: 'renderAid',
		name: 'Render Aid',
		cadence: 'operational',
		category: 'medical',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Attempt emergency medical stabilization or resuscitation.',
		tags: ['medical', 'support'],
		source: COMBAT_RULES_SOURCE,
	},
	resetWeapons: {
		key: 'resetWeapons',
		name: 'Reset Weapons',
		cadence: 'operational',
		category: 'equipment',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Fully reload and normalize personal weapons during a pause.',
		tags: ['weapon', 'ammo'],
		source: COMBAT_RULES_SOURCE,
	},
	setHastyAmbush: {
		key: 'setHastyAmbush',
		name: 'Set Hasty Ambush',
		cadence: 'operational',
		category: 'tactics',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Set up a concealed immediate plan to gain initiative in the next exchange.',
		tags: ['tactics', 'initiative'],
		source: COMBAT_RULES_SOURCE,
	},
	useEquipment: {
		key: 'useEquipment',
		name: 'Use Equipment',
		cadence: 'operational',
		category: 'equipment',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Handle a short technical task such as lockpicking, hot-wiring, or setting charges.',
		tags: ['equipment', 'task'],
		source: COMBAT_RULES_SOURCE,
	},
	withdraw: {
		key: 'withdraw',
		name: 'Withdraw',
		cadence: 'operational',
		category: 'movement',
		defaultCost: 0,
		costLabel: 'entire pause',
		summary: 'Attempt to break contact and leave the fight cleanly.',
		tags: ['movement', 'escape'],
		source: COMBAT_RULES_SOURCE,
	},
	pauseMovement: {
		key: 'pauseMovement',
		name: 'Pause Movement',
		cadence: 'free',
		category: 'movement',
		defaultCost: 0,
		costLabel: 'free during pause',
		summary: 'Move up to ten tactical move distances before the operational action begins.',
		tags: ['movement', 'pause'],
		source: COMBAT_RULES_SOURCE,
	},
};