import type {
	Stance,
	TacticalMovementRate,
} from '../../types';
import type { CombatActionDefinition, TacticalCombatActionKey } from '../catalogShared';
import { COMBAT_RULES_SOURCE } from '../catalogShared';

export const MOVE_TACTICAL_TICK_COST = 5;

export const STANCE_EFFECTS: Record<Stance, string[]> = {
	standing: ['Default stance.', 'No movement restriction.', 'Standard target profile.'],
	kneeling: [
		'Ranged attacks against the character suffer -1.',
		'Close combat attacks against the character gain +1.',
		'Movement is limited to walk or stagger.',
		'Movement penalties to actions are doubled.',
		'Gain +1 Muscle for resisting recoil.',
	],
	sitting: [
		'The character may not move.',
		'If not in a vehicle or mounted, the character counts as a stationary target.',
		'Gain +2 Muscle for resisting recoil.',
	],
	prone: [
		'Effective visual range against the character increases by one range band.',
		'Close combat attacks against the character gain +2.',
		'Movement is limited to crawl.',
		'Ranged attacks to side or rear have doubled tick cost.',
		'Double Muscle for resisting recoil.',
	],
};

export const TACTICAL_MOVEMENT_EFFECTS: Record<TacticalMovementRate, string[]> = {
	sprint: [
		'Requires unencumbered status and no leg injury.',
		'Fine motor control actions suffer -5.',
		'Ranged attacks against the mover suffer -3.',
	],
	run: [
		'Requires no leg injury worse than slight and no more than light encumbrance.',
		'Fine motor control actions suffer -3.',
		'Ranged attacks against the mover suffer -2.',
	],
	trot: [
		'Requires no leg injury worse than slight and no more than moderate encumbrance.',
		'Fine motor control actions suffer -2.',
		'Ranged attacks against the mover suffer -1.',
	],
	walk: ['Used when moderately injured or heavily encumbered.', 'Fine motor control actions suffer -1.'],
	stagger: ['Used when seriously injured, kneeling, or overloaded.', 'Fine motor control actions suffer -1.'],
	crawl: ['Used when prone or unable to stand safely.', 'Fine motor control actions suffer -4.'],
};

export const TACTICAL_COMBAT_ACTIONS: Record<TacticalCombatActionKey, CombatActionDefinition> = {
	activateEquipment: {
		key: 'activateEquipment',
		name: 'Activate/Deactivate Equipment',
		cadence: 'tactical',
		category: 'equipment',
		defaultCost: 1,
		costLabel: '1 tick',
		summary: 'Toggle simple on/off equipment in the middle of an exchange.',
		tags: ['equipment', 'toggle'],
		source: COMBAT_RULES_SOURCE,
	},
	assess: {
		key: 'assess',
		name: 'Assess',
		cadence: 'tactical',
		category: 'observation',
		defaultCost: 1,
		costLabel: '1 to 6 ticks',
		summary: 'Pause to consciously observe the battlefield and gather detail.',
		detail: 'The acting character may voluntarily spend up to 5 extra ticks for a cumulative bonus.',
		tags: ['awareness', 'observation'],
		source: COMBAT_RULES_SOURCE,
	},
	attack: {
		key: 'attack',
		name: 'Attack',
		cadence: 'tactical',
		category: 'attack',
		defaultCost: 0,
		costLabel: 'weapon speed',
		summary: 'Make a ranged or close combat attack using the selected weapon profile.',
		detail: 'Detailed attack resolution starts in the next subsection and is intentionally left to attack-specific rules.',
		tags: ['combat', 'weapon'],
		source: COMBAT_RULES_SOURCE,
	},
	block: {
		key: 'block',
		name: 'Block',
		cadence: 'tactical',
		category: 'defense',
		defaultCost: 1,
		costLabel: '1 tick + blind strike speed',
		summary: 'Deflect a close combat attack with a weapon or guard.',
		tags: ['close-combat', 'defense'],
		source: COMBAT_RULES_SOURCE,
	},
	changeStance: {
		key: 'changeStance',
		name: 'Change Stance',
		cadence: 'tactical',
		category: 'posture',
		defaultCost: 2,
		costLabel: '2 ticks lower, 4 ticks higher',
		summary: 'Shift between standing, kneeling, sitting, and prone stances.',
		tags: ['stance', 'movement'],
		source: COMBAT_RULES_SOURCE,
	},
	communicateSimple: {
		key: 'communicateSimple',
		name: 'Communicate (Simple)',
		cadence: 'tactical',
		category: 'communication',
		defaultCost: 1,
		costLabel: '1, 3, or 5 ticks',
		summary: 'Deliver a short command or warning while rounds are flying.',
		detail: 'Using a device control such as a radio transmit button adds 1 tick.',
		tags: ['speech', 'teamwork'],
		source: COMBAT_RULES_SOURCE,
	},
	ditchItem: {
		key: 'ditchItem',
		name: 'Ditch Item',
		cadence: 'tactical',
		category: 'equipment',
		defaultCost: 0,
		costLabel: '0 ticks or situational',
		summary: 'Drop or violently shed gear to free hands or remove danger.',
		detail: 'Connected gear uses half the normal ready time, while clothing or rigs may consume the rest of the exchange.',
		tags: ['equipment', 'encumbrance'],
		source: COMBAT_RULES_SOURCE,
	},
	move: {
		key: 'move',
		name: 'Move',
		cadence: 'tactical',
		category: 'movement',
		defaultCost: MOVE_TACTICAL_TICK_COST,
		costLabel: '5 ticks',
		summary: 'Cover tactical distance, reposition, mount, or dismount during an exchange.',
		detail: 'A move can be paired with one additional tactical action costing 5 ticks or less.',
		tags: ['movement', 'positioning'],
		source: COMBAT_RULES_SOURCE,
	},
	readyOrStowItem: {
		key: 'readyOrStowItem',
		name: 'Ready/Stow Item',
		cadence: 'tactical',
		category: 'equipment',
		defaultCost: 1,
		costLabel: 'item bulk, minimum 1',
		summary: 'Bring gear into hand or put it away so it can be used later.',
		detail: 'Secured storage, deep containers, and one-handed handling increase cost.',
		tags: ['equipment', 'inventory'],
		source: COMBAT_RULES_SOURCE,
	},
	reload: {
		key: 'reload',
		name: 'Reload',
		cadence: 'tactical',
		category: 'equipment',
		defaultCost: 1,
		costLabel: 'weapon bulk, minimum 1',
		summary: 'Replenish ammunition during an exchange.',
		detail: 'Internal magazines load 3 rounds per action, while support weapons use slower special handling.',
		tags: ['weapon', 'ammo'],
		source: COMBAT_RULES_SOURCE,
	},
	wait: {
		key: 'wait',
		name: 'Wait',
		cadence: 'tactical',
		category: 'timing',
		defaultCost: 3,
		costLabel: 'based on OODA',
		summary: 'Delay briefly instead of acting immediately on the current tick.',
		tags: ['timing', 'initiative'],
		source: COMBAT_RULES_SOURCE,
	},
};