import { createItemDefinition } from "../inventory";
import type { ItemDefinition } from "../types";

const SRC = "Source: Twilight 2013 Core OEF PDF p.224";

export const FIRE_AND_COOKING_ITEMS: ItemDefinition[] = [
	createItemDefinition({
		id: "survival:barbecue-grill",
		name: "Barbecue Grill",
		weight: 35,
		tags: ["survival", "cooking", "fire"],
		barterValue: "GG3.5",
		streetPrice: 140,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:cigarette-lighter-disposable",
		name: "Cigarette Lighter, Disposable",
		weight: 0,
		tags: ["survival", "fire", "lighter"],
		barterValue: "G0.05",
		streetPrice: 1,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:cigarette-lighter-refillable",
		name: "Cigarette Lighter, Refillable",
		weight: 0.1,
		tags: ["survival", "fire", "lighter"],
		barterValue: "GG2.5",
		streetPrice: 20,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:field-kitchen",
		name: "Field Kitchen",
		weight: 1000,
		tags: ["survival", "cooking", "field-kitchen"],
		barterValue: "GG325",
		streetPrice: 1300,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:flint-and-steel",
		name: "Flint and Steel",
		weight: 0,
		tags: ["survival", "fire", "flint-and-steel"],
		barterValue: "GG1.25",
		streetPrice: 5,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:matches",
		name: "Matches, Box of 200",
		weight: 0,
		tags: ["survival", "fire", "matches"],
		barterValue: "GG0.08",
		streetPrice: 2,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:stove-backpacking",
		name: "Stove, Backpacking",
		weight: 0.4,
		tags: ["survival", "cooking", "stove"],
		barterValue: "GG32.5",
		streetPrice: 130,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:stove-camp",
		name: "Stove, Camp",
		weight: 1.2,
		tags: ["survival", "cooking", "stove"],
		barterValue: "GG1.5",
		streetPrice: 30,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:stove-hexamine",
		name: "Stove, Hexamine",
		weight: 0.5,
		tags: ["survival", "cooking", "stove"],
		barterValue: "GG0.4",
		streetPrice: 8,
		source: [SRC],
	}),
	createItemDefinition({
		id: "survival:mess-kit",
		name: "Mess Kit",
		weight: 0.2,
		tags: ["survival", "cooking", "mess-kit"],
		barterValue: "GG2.5",
		streetPrice: 40,
		source: [SRC],
	}),
];
