import type { ContainerDefinition } from "../types";
import { createContainerRule, createItemRule, defineAttachmentContainer, defineContainer } from "./helpers";

export const MODULAR_LOAD_BEARING_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:mlbe:fighting-load-carrier",
    name: "Fighting Load Carrier",
    weight: 1,
    tags: ["container", "load-bearing-equipment", "mlbe"],
    barterValue: "GG100",
    streetPrice: 200,
    voucherCost: { "worn:torso": 1 },
    voucherLimits: { "mlbe:ap": 46 },
    description: "Modular load-bearing vest with 30 front and 16 rear attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-patrol",
    name: "Pack, Patrol",
    weight: 1.5,
    tags: ["container", "load-bearing-equipment", "mlbe", "pack"],
    barterValue: "GG100",
    streetPrice: 200,
    voucherCost: { "worn:back": 1 },
    voucherLimits: { "mlbe:ap": 17 },
    description: "Small modular patrol pack with 17 external attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-field",
    name: "Pack, Field",
    weight: 2,
    tags: ["container", "load-bearing-equipment", "mlbe", "pack"],
    barterValue: "GG87.5",
    streetPrice: 175,
    voucherCost: { "worn:back": 1 },
    voucherLimits: { "mlbe:ap": 24 },
    description: "Field pack with 24 attachment points and volume comparable to a 3-day pack.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-medic",
    name: "Pack, Medic",
    weight: 2,
    tags: ["container", "load-bearing-equipment", "mlbe", "pack", "medical"],
    barterValue: "GG100",
    streetPrice: 200,
    voucherCost: { "worn:back": 1 },
    voucherLimits: { "mlbe:ap": 24 },
    description: "Field-pack-derived medical pack with additional internal organization and 24 attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:pack-frame",
    name: "Pack Frame",
    weight: 1,
    tags: ["container", "load-bearing-equipment", "mlbe", "frame"],
    barterValue: "GG32.5",
    streetPrice: 65,
    voucherCost: { "worn:back": 1 },
    description: "Frame sized to accept compatible patrol, field, or medic packs as a modular frame-pack setup.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:thigh-carrier",
    name: "Thigh Carrier",
    weight: 0.2,
    tags: ["container", "load-bearing-equipment", "mlbe", "thigh-rig"],
    barterValue: "GG32.5",
    streetPrice: 65,
    voucherCost: { "worn:legs": 1 },
    voucherLimits: { "mlbe:ap": 4 },
    description: "Drop-leg platform with 4 attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:mlbe:thigh-holster",
    name: "Thigh Holster",
    weight: 0.2,
    tags: ["container", "load-bearing-equipment", "mlbe", "holster"],
    barterValue: "GG32.5",
    streetPrice: 65,
    voucherCost: { "worn:legs": 1 },
    itemVoucherRules: [
      { key: "stowed:handgun", acceptedItemTags: ["handgun"] },
      { key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] },
    ],
    voucherLimits: { "stowed:handgun": 1, "stowed:magazine": 1 },
    description: "Drop-leg holster sized for 1 handgun with an extra pocket for one spare magazine.",
    defaultMode: "bag",
  }),
];

export const MODULAR_LOAD_BEARING_POUCHES: ContainerDefinition[] = [
  defineAttachmentContainer({
    id: "container:mlbe:belted-ammo-small",
    name: "Belted Ammo, Small",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG43.5",
    streetPrice: 87,
    attachmentPointCost: 3,
    description: "Modular pouch sized for 100 rounds of belted ammunition.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:belted-ammo-large",
    name: "Belted Ammo, Large",
    weight: 0.3,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG60",
    streetPrice: 120,
    attachmentPointCost: 6,
    description: "Modular pouch sized for 200 rounds of belted ammunition.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-handgun",
    name: "Magazine, Handgun",
    weight: 0,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG12.5",
    streetPrice: 25,
    attachmentPointCost: 1,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 1 },
    description: "Single modular magazine pouch for 1 handgun magazine.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-single",
    name: "Magazine, Rifle, Single",
    weight: 0,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG13.5",
    streetPrice: 27,
    attachmentPointCost: 2,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 1 },
    description: "Single modular magazine pouch for 1 rifle magazine.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-double",
    name: "Magazine, Rifle, Double",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG18",
    streetPrice: 36,
    attachmentPointCost: 2,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 2 },
    description: "Double modular magazine pouch for 2 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-quad",
    name: "Magazine, Rifle, Quad",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG20",
    streetPrice: 40,
    attachmentPointCost: 3,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 4 },
    description: "Quad modular magazine placard for 4 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:magazine-rifle-six",
    name: "Magazine, Rifle, Six",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "magazine-carrier"],
    barterValue: "GG27.5",
    streetPrice: 55,
    attachmentPointCost: 4,
    itemVoucherRules: [{ key: "stowed:magazine", acceptedItemTags: ["spare-magazine"] }],
    voucherLimits: { "stowed:magazine": 6 },
    description: "Large modular magazine placard for 6 rifle magazines.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:rifle-cartridge-loops",
    name: "Rifle Cartridge Loops",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG15",
    streetPrice: 30,
    attachmentPointCost: 3,
    description: "Modular ammunition panel sized for 20 rifle rounds.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:shotgun-shell-loops",
    name: "Shotgun Shell Loops",
    weight: 0,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG14",
    streetPrice: 28,
    attachmentPointCost: 3,
    description: "Modular shell panel sized for 12 shotgun shells.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:shotgun-shell-roll",
    name: "Shotgun Shell Roll",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "ammo-storage"],
    barterValue: "GG32.5",
    streetPrice: 65,
    attachmentPointCost: 5,
    description: "Large modular shell roll sized for 36 shotgun shells.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:hand-grenade-loop",
    name: "Hand Grenade Loop",
    weight: 0,
    tags: ["container", "mlbe-pouch", "grenade-carriage"],
    barterValue: "GG18",
    streetPrice: 36,
    attachmentPointCost: 1,
    description: "Modular loop sized for 1 grenade.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:launcher-grenade-loop",
    name: "Launcher Grenade Loop",
    weight: 0,
    tags: ["container", "mlbe-pouch", "grenade-carriage"],
    barterValue: "GG9.5",
    streetPrice: 19,
    attachmentPointCost: 1,
    description: "Modular loop sized for 1 launcher grenade.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:canteen-carrier",
    name: "Canteen Carrier",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "canteen-carrier"],
    barterValue: "GG21",
    streetPrice: 42,
    attachmentPointCost: 2,
    containerVoucherRules: [createContainerRule("stowed:canteen", ["water-container"])],
    voucherLimits: { "stowed:canteen": 1 },
    description: "Modular pouch sized for 1 liter canteen.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:gas-mask-carrier",
    name: "Gas Mask Carrier",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "protective-equipment"],
    barterValue: "GG30",
    streetPrice: 60,
    attachmentPointCost: 6,
    itemVoucherRules: [createItemRule("stowed:protective-equipment", ["protective-equipment", "gas-mask"])],
    voucherLimits: { "stowed:protective-equipment": 1 },
    description: "Modular carrier sized for 1 gas mask.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:holster",
    name: "Holster",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "holster"],
    barterValue: "GG32.5",
    streetPrice: 65,
    attachmentPointCost: 4,
    itemVoucherRules: [{ key: "stowed:handgun", acceptedItemTags: ["handgun"] }],
    voucherLimits: { "stowed:handgun": 1 },
    description: "Modular holster sized for 1 handgun.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:hydration-bladder-carrier",
    name: "Hydration Bladder Carrier",
    weight: 0.3,
    tags: ["container", "mlbe-pouch", "hydration"],
    barterValue: "GG32.5",
    streetPrice: 65,
    attachmentPointCost: 8,
    containerVoucherRules: [createContainerRule("stowed:hydration", ["hydration"])],
    voucherLimits: { "stowed:hydration": 1 },
    description: "Modular carrier sized for a 3 liter hydration bladder.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:map-pouch",
    name: "Map Pouch",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "map-pouch"],
    barterValue: "GG16",
    streetPrice: 32,
    attachmentPointCost: 6,
    description: "Flat modular pouch sized for papers or objects up to about 15 x 30 cm.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:medical-pouch",
    name: "Medical Pouch",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "medical"],
    barterValue: "GG25",
    streetPrice: 50,
    attachmentPointCost: 4,
    itemVoucherRules: [createItemRule("stowed:medical", ["medical", "ifak"])],
    voucherLimits: { "stowed:medical": 1 },
    description: "Modular medical pouch sized for 1 IFAK.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:nvg-carrier-padded",
    name: "NVG Carrier, Padded",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "optics"],
    barterValue: "GG15",
    streetPrice: 30,
    attachmentPointCost: 4,
    itemVoucherRules: [createItemRule("stowed:nvg", ["nvgs"])],
    voucherLimits: { "stowed:nvg": 1 },
    description: "Padded modular pouch sized for 1 set of NVGs.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:radio-pouch",
    name: "Radio Pouch",
    weight: 0.1,
    tags: ["container", "mlbe-pouch", "radio-pouch"],
    barterValue: "GG18.5",
    streetPrice: 37,
    attachmentPointCost: 2,
    itemVoucherRules: [createItemRule("stowed:radio", ["radio"])],
    voucherLimits: { "stowed:radio": 1 },
    description: "Modular pouch sized for 1 tactical radio.",
    defaultMode: "bag",
  }),
  defineAttachmentContainer({
    id: "container:mlbe:utility-pouch",
    name: "Utility Pouch",
    weight: 0.2,
    tags: ["container", "mlbe-pouch", "utility-pouch"],
    barterValue: "GG22",
    streetPrice: 44,
    attachmentPointCost: 4,
    description: "General-purpose modular pouch with roughly 12 x 18 x 8 cm of internal space.",
    defaultMode: "bag",
  }),
];