import type { ContainerDefinition } from "../types";
import { defineContainer } from "./helpers";

export const PACK_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:pack:frame-civilian",
    name: "Frame Pack, Civilian",
    weight: 2.7,
    capacityWeight: 80,
    tags: ["container", "pack", "frame-pack"],
    barterValue: "GG8.75",
    streetPrice: 175,
    voucherCost: { "worn:back": 1 },
    description: "80-liter civilian frame backpack with a lightweight frame and accessory attachment points.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:frame-high-capacity",
    name: "Frame Pack, High-Capacity",
    weight: 4,
    capacityWeight: 125,
    tags: ["container", "pack", "frame-pack"],
    barterValue: "GG15",
    streetPrice: 300,
    voucherCost: { "worn:back": 1 },
    description: "Large expedition frame pack with about 125 liters of capacity.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:frame-military",
    name: "Frame Pack, Military",
    weight: 3,
    tags: ["container", "pack", "frame-pack", "military"],
    barterValue: "GG5",
    streetPrice: 100,
    voucherCost: { "worn:back": 1 },
    description: "Rugged military frame pack with subdued colors and field-oriented construction.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:rucksack-civilian",
    name: "Rucksack, Civilian",
    weight: 1.3,
    capacityWeight: 40,
    tags: ["container", "pack", "rucksack"],
    barterValue: "GG2.5",
    streetPrice: 50,
    voucherCost: { "worn:back": 1 },
    description: "Simple 40-liter backpack with basic ergonomic support.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:pack:waist-pack",
    name: "Waist Pack",
    weight: 0.2,
    tags: ["container", "pack", "waist-pack"],
    barterValue: "GG0.5",
    streetPrice: 20,
    voucherCost: { "worn:waist": 1 },
    description: "Small zippered pouch with an integral belt for waist carry.",
    defaultMode: "bag",
  }),
];