import type { ContainerDefinition } from "../types";
import { defineContainer } from "./helpers";

export const LIQUID_STORAGE_CONTAINERS: ContainerDefinition[] = [
  defineContainer({ id: "container:storage:bulk-tank-750l", name: "Bulk Tank, 750 Liters", weight: 100, capacityWeight: 750, tags: ["container", "storage", "liquid-storage"], barterValue: "GG20", streetPrice: 400, description: "Field storage tank for up to 750 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:bulk-tank-1000l", name: "Bulk Tank, 1,000 Liters", weight: 130, capacityWeight: 1000, tags: ["container", "storage", "liquid-storage"], barterValue: "GG30", streetPrice: 600, description: "Field storage tank for up to 1,000 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:bulk-tank-2000l", name: "Bulk Tank, 2,000 Liters", weight: 250, capacityWeight: 2000, tags: ["container", "storage", "liquid-storage"], barterValue: "GG37.5", streetPrice: 750, description: "Field storage tank for up to 2,000 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:bulk-tank-4000l", name: "Bulk Tank, 4,000 Liters", weight: 520, capacityWeight: 4000, tags: ["container", "storage", "liquid-storage"], barterValue: "GG60", streetPrice: 1200, description: "Field storage tank for up to 4,000 liters of liquid.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:drum-metal-200l", name: "Drum, Metal, 200 Liters", weight: 17, capacityWeight: 200, tags: ["container", "storage", "liquid-storage", "drum"], barterValue: "GG10", streetPrice: 45, description: "Standard steel 200-liter drum.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:drum-plastic-200l", name: "Drum, Plastic, 200 Liters", weight: 10, capacityWeight: 200, tags: ["container", "storage", "liquid-storage", "drum"], barterValue: "GG15", streetPrice: 65, description: "Plastic 200-liter drum.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:folding-bladder-20l", name: "Folding Bladder, 20 Liters", weight: 0.3, capacityWeight: 20, tags: ["container", "storage", "liquid-storage", "bladder"], barterValue: "GG1", streetPrice: 9, description: "Flexible clear plastic liquid bladder.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:fuel-bladder-300l", name: "Fuel Bladder, 300 Liters", weight: 70, capacityWeight: 300, tags: ["container", "storage", "liquid-storage", "fuel"], barterValue: "GG20", streetPrice: 700, description: "Reinforced field-rated fuel bladder.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:fuel-bladder-1100l", name: "Fuel Bladder, 1,100 Liters", weight: 250, capacityWeight: 1100, tags: ["container", "storage", "liquid-storage", "fuel"], barterValue: "GG30", streetPrice: 1000, description: "Large reinforced field-rated fuel bladder.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:jerry-can-20l", name: "Jerry Can, 20 Liters", weight: 2, capacityWeight: 20, tags: ["container", "storage", "liquid-storage", "fuel"], barterValue: "GG5", streetPrice: 25, description: "Rectangular field fuel can.", defaultMode: "bag" }),
];

export const DRY_GOODS_STORAGE_CONTAINERS: ContainerDefinition[] = [
  defineContainer({ id: "container:storage:ammo-can", name: "Ammo Can", weight: 3, tags: ["container", "storage", "dry-goods"], barterValue: "GG0.8", streetPrice: 8, description: "Steel hinged-lid ammunition can; a common example holds roughly 800 rounds of 5.56x45mm ammunition.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:cargo-pallet", name: "Cargo Pallet", weight: 20, tags: ["container", "storage", "dry-goods"], barterValue: "GG0.75", streetPrice: 15, description: "One-meter square cargo pallet framework for up to roughly 2 tons of freight.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:handgun-case-hard", name: "Handgun Case, Hard", weight: 1, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG20", streetPrice: 40, description: "Rigid handgun case sized for Bulk 1 handguns plus accessories.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:handgun-case-soft", name: "Handgun Case, Soft", weight: 0.5, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG15", streetPrice: 30, description: "Soft handgun case sized for Bulk 1 handguns plus accessories.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:long-gun-case-hard", name: "Long Gun Case, Hard", weight: 4, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG40", streetPrice: 80, description: "Rigid long-gun case sized for a single weapon plus magazines, optics, and tools.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:long-gun-case-mlbe", name: "Long Gun Case, MLBE", weight: 1.7, tags: ["container", "storage", "dry-goods", "gun-case", "mlbe"], barterValue: "GG50", streetPrice: 100, voucherLimits: { "mlbe:ap": 12 }, description: "Long gun case built on an MLBE-compatible exterior with 12 attachment points.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:long-gun-case-soft", name: "Long Gun Case, Soft", weight: 1.5, tags: ["container", "storage", "dry-goods", "gun-case"], barterValue: "GG32.5", streetPrice: 65, description: "Soft long-gun case sized for a single weapon plus accessories.", defaultMode: "bag" }),
  defineContainer({ id: "container:storage:portable-refrigerator", name: "Portable Refrigerator", weight: 18, tags: ["container", "storage", "dry-goods", "refrigerated"], barterValue: "GG950", streetPrice: 1900, description: "15-liter medical or organ transport refrigerator with integrated handle and latch.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:shipping-container-6m", name: "Shipping Container, 6 m", weight: 2200, capacityWeight: 15000, tags: ["container", "storage", "dry-goods", "shipping-container"], barterValue: "GG50", streetPrice: 2000, description: "Standard 6-meter intermodal steel container.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:shipping-container-12m", name: "Shipping Container, 12 m", weight: 3700, capacityWeight: 30000, tags: ["container", "storage", "dry-goods", "shipping-container"], barterValue: "GG75", streetPrice: 3000, description: "Standard 12-meter intermodal steel container.", defaultMode: "bin" }),
  defineContainer({ id: "container:storage:shipping-container-16m", name: "Shipping Container, 16 m", weight: 4700, capacityWeight: 40000, tags: ["container", "storage", "dry-goods", "shipping-container"], barterValue: "GG90", streetPrice: 3500, description: "Standard 16-meter intermodal steel container.", defaultMode: "bin" }),
];