import type { ContainerDefinition } from "../types";
import { defineContainer } from "./helpers";

export const SURVIVAL_CONTAINERS: ContainerDefinition[] = [
  defineContainer({
    id: "container:survival:canteen-1l",
    name: "Canteen, 1 Liter",
    weight: 1.3,
    capacityWeight: 1,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG1",
    streetPrice: 10,
    description: "Water canteen that holds 1 liter of liquid; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:flask-0-25l",
    name: "Flask, 0.25 Liter",
    weight: 0.3,
    capacityWeight: 0.25,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG1",
    streetPrice: 10,
    description: "Small liquid flask; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-1-5l",
    name: "Hydration Bladder, 1.5 Liters",
    weight: 1.6,
    capacityWeight: 1.5,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG2",
    streetPrice: 20,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-2l",
    name: "Hydration Bladder, 2 Liters",
    weight: 2.1,
    capacityWeight: 2,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG2.5",
    streetPrice: 25,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-3l",
    name: "Hydration Bladder, 3 Liters",
    weight: 3.2,
    capacityWeight: 3,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG3",
    streetPrice: 30,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-6l",
    name: "Hydration Bladder, 6 Liters",
    weight: 6.3,
    capacityWeight: 6,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG3.6",
    streetPrice: 36,
    description: "Soft hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:hydration-bladder-10l",
    name: "Hydration Bladder, 10 Liters",
    weight: 10.3,
    capacityWeight: 10,
    tags: ["container", "survival-container", "hydration"],
    barterValue: "GG4",
    streetPrice: 40,
    description: "Large hydration bladder; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:water-bottle-0-5l",
    name: "Water Bottle, 0.5 Liter",
    weight: 0.6,
    capacityWeight: 0.5,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG0.6",
    streetPrice: 6,
    description: "Water bottle; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:water-bottle-1l",
    name: "Water Bottle, 1 Liter",
    weight: 1.2,
    capacityWeight: 1,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG0.9",
    streetPrice: 9,
    description: "Water bottle; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:waterskin-1-5l",
    name: "Waterskin, 1.5 Liter",
    weight: 1.8,
    capacityWeight: 1.5,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG1.5",
    streetPrice: 15,
    description: "Traditional waterskin; listed weight includes full contents.",
    defaultMode: "bag",
  }),
  defineContainer({
    id: "container:survival:waterskin-5l",
    name: "Waterskin, 5 Liter",
    weight: 6,
    capacityWeight: 5,
    tags: ["container", "survival-container", "water-container"],
    barterValue: "GG2",
    streetPrice: 20,
    description: "Large waterskin; listed weight includes full contents.",
    defaultMode: "bag",
  }),
];