"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CONSUMABLES_CATALOG = exports.RELOADING_SUPPLIES = exports.PHOTOGRAPHIC_SUPPLIES = exports.BUILDING_MATERIAL = exports.MISC_CONSUMABLES = exports.PARTS_ITEMS = exports.BATTERY_CHARGERS = exports.BATTERY_ITEMS = exports.GASEOUS_FUEL = exports.SOLID_FUEL = exports.LIQUID_FUEL = exports.WATER_ITEMS = exports.ALCOHOL_ITEMS = exports.SUPPLEMENT_ITEMS = exports.FOOD_ITEMS = void 0;
const inventory_1 = require("./inventory");
const SRC_250 = "Source: Twilight 2013 Core OEF PDF p.250";
const SRC_251 = "Source: Twilight 2013 Core OEF PDF p.251";
const SRC_246 = "Source: Twilight 2013 Core OEF PDF p.246";
// ── Food ──────────────────────────────────────────────────────────────────────
exports.FOOD_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-camping",
        name: "Camping Food (per meal)",
        weight: 0.5,
        tags: ["consumable", "food", "meal"],
        traits: ["nutrition:calories:500", "nutrition:unit:meal"],
        barterValue: "GG20",
        streetPrice: 20,
        source: [SRC_250],
        description: "Dehydrated backpacker food; preparation requires 1 L water. Can be eaten unprepared at risk of digestive ailments. Shelf life 1–2 years.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-fresh",
        name: "Fresh Food (per meal)",
        weight: 1.8,
        tags: ["consumable", "food", "meal"],
        traits: ["nutrition:calories:700", "nutrition:unit:meal"],
        barterValue: "GG1.8",
        streetPrice: 12,
        source: [SRC_250],
        description: "Freshly gathered or lightly preserved farm food. Most common fare in self-sufficient communities. Shelf life ~1 year.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-military-ration",
        name: "Military Ration (per meal)",
        weight: 1,
        tags: ["consumable", "food", "meal", "military"],
        traits: ["nutrition:calories:1250", "nutrition:unit:meal"],
        barterValue: "GG16",
        streetPrice: 14,
        source: [SRC_250],
        description: "Pre-packaged field ration with chemical heater. Minimum 3-year shelf life, up to 10 years if cool-stored.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-packaged",
        name: "Packaged Food (per meal)",
        weight: 2.8,
        tags: ["consumable", "food", "meal"],
        traits: ["nutrition:calories:600", "nutrition:unit:meal"],
        barterValue: "GG4",
        streetPrice: 8,
        source: [SRC_250],
        description: "Commercial canned or boxed food. Shelf life 1–3 years.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-wild-balanced",
        name: "Wild Food, Balanced (per meal)",
        weight: 3.6,
        tags: ["consumable", "food", "meal", "foraged"],
        traits: ["nutrition:calories:400", "nutrition:unit:meal"],
        barterValue: "GG1.2",
        streetPrice: 0,
        source: [SRC_250],
        description: "Mix of roots, nuts, berries, and fresh meat. Sustainable indefinitely.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-wild-forage-heavy",
        name: "Wild Food, Forage-Heavy (per meal)",
        weight: 4.8,
        tags: ["consumable", "food", "meal", "foraged"],
        traits: ["nutrition:calories:400", "nutrition:unit:meal"],
        barterValue: "GG0.9",
        streetPrice: 0,
        source: [SRC_250],
        description: "Mostly wild plants with minimal animal protein. Long-term consumption risks dietary deficiencies.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:food-wild-meat-heavy",
        name: "Wild Food, Meat-Heavy (per meal)",
        weight: 2.4,
        tags: ["consumable", "food", "meal", "foraged"],
        traits: ["nutrition:calories:400", "nutrition:unit:meal"],
        barterValue: "GG0.9",
        streetPrice: 0,
        source: [SRC_250],
        description: "Mostly fresh meat. Long-term consumption risks medical complications.",
    }),
];
exports.SUPPLEMENT_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:supplement-coffee",
        name: "Coffee, 50 Servings",
        weight: 0.1,
        tags: ["consumable", "supplement", "stimulant"],
        barterValue: "GG4",
        streetPrice: 8,
        source: [SRC_250],
        description: "Preferred stimulant of North America and most of Europe. Weight/price given before preparation.",
        traits: ["stimulant-coffee"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:supplement-energy-bar",
        name: "Energy Bar",
        weight: 0.1,
        tags: ["consumable", "supplement"],
        traits: ["nutrition:calories:300", "nutrition:unit:item"],
        barterValue: "GG1",
        streetPrice: 1,
        source: [SRC_250],
        description: "Commercial quick-energy product. ~1-year shelf life.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:supplement-salt",
        name: "Salt (per kg)",
        weight: 1,
        tags: ["consumable", "supplement", "preservation"],
        barterValue: "GG10",
        streetPrice: 5,
        source: [SRC_250],
        description: "Food preservation staple; widely in demand post-Collapse.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:supplement-survival-ration",
        name: "Survival Ration (per day)",
        weight: 0.1,
        tags: ["consumable", "supplement", "emergency-food"],
        traits: ["nutrition:calories:800", "nutrition:unit:day"],
        barterValue: "GG2.5",
        streetPrice: 2,
        source: [SRC_250],
        description: "Compressed food bars. Chalk-like taste and texture. 5-year shelf life.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:supplement-tea",
        name: "Tea, 50 Servings",
        weight: 0.1,
        tags: ["consumable", "supplement", "stimulant"],
        barterValue: "GG5",
        streetPrice: 10,
        source: [SRC_250],
        description: "Stimulant of choice for most of Asia, Africa, and South America. Weight/price before preparation.",
        traits: ["stimulant-tea"],
    }),
];
exports.ALCOHOL_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:alcohol-beer",
        name: "Beer, 350 mL Bottle, New",
        weight: 0.4,
        tags: ["consumable", "alcohol", "recreational"],
        barterValue: "GG0.5",
        streetPrice: 0,
        source: [SRC_250],
        description: "New-production beer in 350 mL bottle. Street price is not listed in the source table.",
        traits: ["alcohol-dose"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:alcohol-spirits",
        name: "Spirits, 1-Liter Bottle, Prewar",
        weight: 1.2,
        tags: ["consumable", "alcohol", "recreational", "flammable"],
        barterValue: "GG7.5",
        streetPrice: 10,
        source: [SRC_250],
        description: "Prewar distilled spirits in 1 L bottle. Can be used in Molotov cocktails.",
        traits: ["alcohol-dose", "molotov-compatible"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:alcohol-wine",
        name: "Wine, 750 mL Bottle, Prewar",
        weight: 1,
        tags: ["consumable", "alcohol", "recreational"],
        barterValue: "GG4",
        streetPrice: 10,
        source: [SRC_250],
        description: "Prewar wine in 750 mL bottle.",
        traits: ["alcohol-dose"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:alcohol-beer-prewar",
        name: "Beer, 350 mL Bottle, Prewar",
        weight: 0.4,
        tags: ["consumable", "alcohol", "recreational"],
        barterValue: "GG0.1",
        streetPrice: 2,
        source: [SRC_250],
        description: "Prewar beer in 350 mL bottle.",
        traits: ["alcohol-dose"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:alcohol-spirits-new",
        name: "Spirits, 1-Liter Bottle, New",
        weight: 1.2,
        tags: ["consumable", "alcohol", "recreational", "flammable"],
        barterValue: "GG5",
        streetPrice: 0,
        source: [SRC_250],
        description: "New-production distilled spirits in 1 L bottle. Street price is not listed in the source table.",
        traits: ["alcohol-dose", "molotov-compatible"],
    }),
];
//placeholder values
exports.WATER_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:water",
        name: "Water (per L)",
        weight: 1,
        tags: ["consumable", "water", "drinkable"],
        barterValue: "0",
        streetPrice: 0,
        source: [SRC_250],
        description: "Essential for survival. One liter per dose.",
    }),
];
// ── Fuel ──────────────────────────────────────────────────────────────────────
exports.LIQUID_FUEL = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-aviation",
        name: "Aviation Fuel (per L)",
        weight: 0.8,
        tags: ["consumable", "fuel", "liquid-fuel", "aviation"],
        barterValue: "GG1.5",
        streetPrice: 6,
        source: [SRC_246],
        description: "High-quality fossil fuel for aviation engines. Includes avgas, jet fuel, and aviation kerosene.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-biodiesel",
        name: "Biodiesel (per L)",
        weight: 0.87,
        tags: ["consumable", "fuel", "liquid-fuel", "renewable"],
        barterValue: "GG0.5",
        streetPrice: 2,
        source: [SRC_246],
        description: "Organic substitute for diesel fuel.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-diesel",
        name: "Diesel (per L)",
        weight: 0.85,
        tags: ["consumable", "fuel", "liquid-fuel"],
        barterValue: "GG0.75",
        streetPrice: 3,
        source: [SRC_246],
        description: "Heavier fossil fuel requiring heat and compression to ignite.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-ethanol",
        name: "Ethanol (per L)",
        weight: 0.79,
        tags: ["consumable", "fuel", "liquid-fuel", "renewable"],
        barterValue: "GG0.5",
        streetPrice: 2,
        source: [SRC_246],
        description: "Alcohol fuel distilled from grains or fruit. Not safe to drink.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-gasoline",
        name: "Gasoline (per L)",
        weight: 0.75,
        tags: ["consumable", "fuel", "liquid-fuel"],
        barterValue: "GG1",
        streetPrice: 4,
        source: [SRC_246],
        description: "Light, highly flammable fossil fuel.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-methanol",
        name: "Methanol (per L)",
        weight: 0.79,
        tags: ["consumable", "fuel", "liquid-fuel", "renewable", "poison"],
        barterValue: "GG0.4",
        streetPrice: 1.5,
        source: [SRC_246],
        description: "Lowest energy density of liquid fuels. Made from wood or vegetable matter. Toxic if consumed.",
    }),
];
exports.SOLID_FUEL = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-coal",
        name: "Coal (per kg)",
        weight: 1,
        tags: ["consumable", "fuel", "solid-fuel"],
        barterValue: "GG0.25",
        streetPrice: 1,
        source: [SRC_246],
        description: "Burns hotter and longer than wood. Less common due to mining difficulty.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-hexamine-tablets",
        name: "Hexamine Fuel Tablets (per pack of 12)",
        weight: 0.1,
        tags: ["consumable", "fuel", "solid-fuel", "camp-stove"],
        barterValue: "GG0.5",
        streetPrice: 2,
        source: [SRC_246],
        description: "Each tablet burns ~15 min; enough to cook one meal or boil 0.5 L water. Not for vehicles.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-wood",
        name: "Wood (per kg)",
        weight: 1,
        tags: ["consumable", "fuel", "solid-fuel"],
        barterValue: "GG0.05",
        streetPrice: 0.25,
        source: [SRC_246],
        description: "Most common solid fuel; easily gathered in forested areas.",
    }),
];
exports.GASEOUS_FUEL = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-acetylene-cylinder",
        name: "Acetylene Cylinder",
        weight: 6,
        tags: ["consumable", "fuel", "gaseous-fuel", "industrial"],
        barterValue: "GG20",
        streetPrice: 80,
        source: [SRC_246],
        description: "Highly flammable industrial gas for high-temperature cutting/burning. Must be stored upright. Provides 4 hours of use.",
        traits: ["flammable-hazardous", "transport-upright"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-bottled-gas-0.5l",
        name: "Bottled Gas, 0.5 L",
        weight: 0.4,
        tags: ["consumable", "fuel", "gaseous-fuel", "camp-stove"],
        barterValue: "GG2",
        streetPrice: 8,
        source: [SRC_246],
        description: "Small canister for camp stoves and lanterns. Incompatible with larger fittings.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-bottled-gas-2l",
        name: "Bottled Gas, 2 L",
        weight: 1.2,
        tags: ["consumable", "fuel", "gaseous-fuel", "camp-stove"],
        barterValue: "GG5",
        streetPrice: 20,
        source: [SRC_246],
        description: "Standard canister for camp stoves and lanterns. Incompatible with larger fittings.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-bottled-gas-17.6l",
        name: "Bottled Gas, 17.6 L",
        weight: 8,
        tags: ["consumable", "fuel", "gaseous-fuel"],
        barterValue: "GG15",
        streetPrice: 60,
        source: [SRC_246],
        description: "Typical barbecue-grill propane/butane cylinder.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-bottled-gas-25.4l",
        name: "Bottled Gas, 25.4 L",
        weight: 12,
        tags: ["consumable", "fuel", "gaseous-fuel", "industrial"],
        barterValue: "GG25",
        streetPrice: 100,
        source: [SRC_246],
        description: "Standard industrial gas cylinder (forklift size).",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:fuel-non-flammable-gas-cylinder",
        name: "Non-Flammable Gas Cylinder",
        weight: 6,
        tags: ["consumable", "industrial-gas", "gaseous-fuel"],
        barterValue: "GG10",
        streetPrice: 40,
        source: [SRC_246],
        description: "Oxygen, argon, CO₂ or similar industrial gases. Non-flammable but may explode if heated or punctured.",
        traits: ["pressure-explosion-hazard"],
    }),
];
// ── Batteries ────────────────────────────────────────────────────────────────
exports.BATTERY_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:battery-micro",
        name: "Battery, Micro",
        weight: 0,
        tags: ["consumable", "battery", "micro"],
        barterValue: "GG0.25",
        streetPrice: 1,
        source: [SRC_246],
        description: "Button-cell battery for wristwatches and hearing aids.",
        traits: ["battery-size:micro"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:battery-small",
        name: "Battery, Small",
        weight: 0.03,
        tags: ["consumable", "battery", "small"],
        barterValue: "GG0.5",
        streetPrice: 2,
        source: [SRC_246],
        description: "AAA and AA batteries for portable electronics and vision devices.",
        traits: ["battery-size:sm"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:battery-medium",
        name: "Battery, Medium",
        weight: 0.1,
        tags: ["consumable", "battery", "medium"],
        barterValue: "GG1",
        streetPrice: 4,
        source: [SRC_246],
        description: "C, D, and medium specialist batteries for comms equipment.",
        traits: ["battery-size:med"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:battery-large",
        name: "Battery, Large",
        weight: 0.5,
        tags: ["consumable", "battery", "large"],
        barterValue: "GG3",
        streetPrice: 12,
        source: [SRC_246],
        description: "Heavy lantern batteries and large specialist batteries.",
        traits: ["battery-size:lg"],
    }),
];
exports.BATTERY_CHARGERS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:battery-charger-solar",
        name: "Battery Charger, Solar",
        weight: 0.5,
        tags: ["consumable", "battery-charger", "solar"],
        barterValue: "GG25",
        streetPrice: 100,
        source: [SRC_246],
        description: "Solar charger; functions in any adequate or brighter light. Charges one battery at a time: sm 2 hrs, med 6 hrs, lg 18 hrs. Cannot charge specialist batteries.",
        traits: ["solar-powered", "battery-charger"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:battery-charger-standard",
        name: "Battery Charger, Standard",
        weight: 0.5,
        tags: ["consumable", "battery-charger"],
        barterValue: "GG10",
        streetPrice: 40,
        source: [SRC_246],
        description: "Plug-in charger; holds 4 sm/med or 1 lg battery. Requires 0.2 kW. Charge times: sm 1 hr, med 3 hrs, lg 6 hrs. Also accepts specialist batteries.",
        traits: ["ac-powered-0.2kw", "battery-charger"],
    }),
];
// ── Parts ─────────────────────────────────────────────────────────────────────
exports.PARTS_ITEMS = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:parts-electrical",
        name: "Electrical",
        weight: 1,
        tags: ["consumable", "parts", "electrical"],
        barterValue: "GG20",
        streetPrice: 100,
        source: [SRC_251],
        description: "Wiring, fuses, switches, relays, tape, insulation, and connectors for vehicular or structural electrical systems.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:parts-electronic",
        name: "Electronic",
        weight: 0.1,
        tags: ["consumable", "parts", "electronic"],
        barterValue: "GG25",
        streetPrice: 50,
        source: [SRC_251],
        description: "Transistors, resistors, diodes, solder, thermal paste, and compressed air for solid-state electronics repair.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:parts-maintenance-supplies",
        name: "Maintenance",
        weight: 2,
        tags: ["consumable", "parts", "maintenance"],
        barterValue: "GG8",
        streetPrice: 40,
        source: [SRC_251],
        description: "Lubricants, cleaning chemicals, and operating fluids for mechanical devices.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:parts-mechanical-small",
        name: "Mechanical, Small",
        weight: 0.1,
        tags: ["consumable", "parts", "mechanical"],
        barterValue: "GG5",
        streetPrice: 25,
        source: [SRC_251],
        description: "Springs, gears, pins, screws, bolts, O-rings, and small blanks for personal mechanical devices.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:parts-mechanical-medium",
        name: "Mechanical, Medium",
        weight: 5,
        tags: ["consumable", "parts", "mechanical"],
        barterValue: "GG100",
        streetPrice: 500,
        source: [SRC_251],
        description: "Replacement parts for consumer vehicles and similar machinery.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:parts-mechanical-large",
        name: "Mechanical, Large",
        weight: 15,
        tags: ["consumable", "parts", "mechanical"],
        barterValue: "GG300",
        streetPrice: 1500,
        source: [SRC_251],
        description: "Replacement parts for commercial and combat vehicles and similarly large systems.",
    }),
];
// ── Miscellaneous Consumables ─────────────────────────────────────────────────
exports.MISC_CONSUMABLES = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:misc-biodiesel-chemicals",
        name: "Biodiesel Production Chemicals, 1 Unit",
        weight: 0,
        tags: ["consumable", "chemical", "fuel-production"],
        barterValue: "GG0.25",
        streetPrice: 0.5,
        source: [SRC_251],
        description: "Acids and catalysts sufficient for refining 1 liter of biodiesel fuel.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:misc-hygiene-supplies",
        name: "Personal Hygiene Supplies, 1 Month",
        weight: 1.5,
        tags: ["consumable", "personal-care"],
        barterValue: "GG3",
        streetPrice: 30,
        source: [SRC_251],
        description: "Soap, shampoo, disposable razor blades, foot powder, toothpaste, and related personal-care supplies for one month.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:misc-seeds-food",
        name: "Seeds, Food Crop, 1 Hectare",
        weight: 125,
        tags: ["consumable", "agricultural"],
        barterValue: "GG20",
        streetPrice: 40,
        source: [SRC_251],
        description: "Material necessary for planting one hectare of food crop.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:misc-seeds-industrial",
        name: "Seeds, Industrial Crop, 1 Hectare",
        weight: 125,
        tags: ["consumable", "agricultural"],
        barterValue: "GG15",
        streetPrice: 30,
        source: [SRC_251],
        description: "Material necessary for planting one hectare of industrial crop such as fodder or ethanol feedstock.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:misc-welding-rod",
        name: "Welding Rod",
        weight: 0.1,
        tags: ["consumable", "welding"],
        barterValue: "GG1",
        streetPrice: 5,
        source: [SRC_251],
        description: "Electrode rod for arc welding. One rod supports 1d6x10 minutes of welding use.",
    }),
];
// ── Building Material ──────────────────────────────────────────────────────────
exports.BUILDING_MATERIAL = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:building-light",
        name: "Light, 1 Unit",
        weight: 500,
        tags: ["consumable", "building-material", "construction"],
        barterValue: "GG12.5",
        streetPrice: 250,
        source: [SRC_251],
        description: "Building material suitable for temporary shelters, interior work, and patch repairs.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:building-heavy",
        name: "Heavy, 1 Unit",
        weight: 1000,
        tags: ["consumable", "building-material", "construction"],
        barterValue: "GG100",
        streetPrice: 2000,
        source: [SRC_251],
        description: "Heavy building material for load-bearing structures and reinforcement.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:building-industrial",
        name: "Industrial, 1 Unit",
        weight: 5000,
        tags: ["consumable", "building-material", "construction"],
        barterValue: "GG250",
        streetPrice: 5000,
        source: [SRC_251],
        description: "Industrial-grade material for reinforced or damage-resistant construction.",
    }),
];
exports.PHOTOGRAPHIC_SUPPLIES = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:photo-film-black-white-36",
        name: "Camera Film, Black & White, 36 Shots",
        weight: 0.1,
        tags: ["consumable", "photography", "film"],
        barterValue: "GG2",
        streetPrice: 10,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:photo-film-color-36",
        name: "Camera Film, Color, 36 Shots",
        weight: 0.1,
        tags: ["consumable", "photography", "film"],
        barterValue: "GG2",
        streetPrice: 10,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:photo-film-infrared-36",
        name: "Camera Film, Infrared, 36 Shots",
        weight: 0.1,
        tags: ["consumable", "photography", "film", "infrared"],
        barterValue: "GG4",
        streetPrice: 20,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:photo-film-instant-10",
        name: "Camera Film, Instant, 10 Shots",
        weight: 0.1,
        tags: ["consumable", "photography", "film", "instant"],
        barterValue: "GG6.25",
        streetPrice: 25,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:photo-developing-chemicals-black-white",
        name: "Developing Chemicals, Black & White",
        weight: 4.2,
        tags: ["consumable", "photography", "developing"],
        barterValue: "GG75",
        streetPrice: 150,
        source: [SRC_251],
        description: "Supplies for developing up to 240 exposures of black-and-white or infrared film.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:photo-developing-chemicals-color",
        name: "Developing Chemicals, Color",
        weight: 4.2,
        tags: ["consumable", "photography", "developing"],
        barterValue: "GG100",
        streetPrice: 200,
        source: [SRC_251],
        description: "Supplies for developing up to 240 exposures of color film.",
    }),
];
exports.RELOADING_SUPPLIES = [
    (0, inventory_1.createItemDefinition)({
        id: "consumable:reloading-brass-100",
        name: "Brass, 100 Units",
        weight: 0.9,
        tags: ["consumable", "reloading", "ammunition"],
        barterValue: "GG2",
        streetPrice: 40,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:reloading-bullets-100",
        name: "Bullets, 100 Units",
        weight: 1.2,
        tags: ["consumable", "reloading", "ammunition"],
        barterValue: "GG15",
        streetPrice: 30,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:reloading-primers-100",
        name: "Primers, 100 Units",
        weight: 0.1,
        tags: ["consumable", "reloading", "ammunition"],
        barterValue: "GG6",
        streetPrice: 6,
        source: [SRC_251],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "consumable:reloading-smokeless-powder-2000",
        name: "Smokeless Powder, 2,000 Units",
        weight: 0.5,
        tags: ["consumable", "reloading", "ammunition", "powder"],
        barterValue: "GG25",
        streetPrice: 25,
        source: [SRC_251],
    }),
];
exports.CONSUMABLES_CATALOG = [
    ...exports.FOOD_ITEMS,
    ...exports.SUPPLEMENT_ITEMS,
    ...exports.ALCOHOL_ITEMS,
    ...exports.LIQUID_FUEL,
    ...exports.SOLID_FUEL,
    ...exports.GASEOUS_FUEL,
    ...exports.BATTERY_ITEMS,
    ...exports.BATTERY_CHARGERS,
    ...exports.PARTS_ITEMS,
    ...exports.MISC_CONSUMABLES,
    ...exports.BUILDING_MATERIAL,
    ...exports.PHOTOGRAPHIC_SUPPLIES,
    ...exports.RELOADING_SUPPLIES,
];
