"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GENERIC_LONGRIFLE = exports.RIFLE_SLING = exports.BACKPACK = exports.TRAUMA_PLATES = exports.HELMETS = exports.GENERIC_ARMOR = exports.BODY_ARMORS = exports.ARMOR_CATALOG = void 0;
var armorCatalog_1 = require("./armorCatalog");
Object.defineProperty(exports, "ARMOR_CATALOG", { enumerable: true, get: function () { return armorCatalog_1.ARMOR_CATALOG; } });
Object.defineProperty(exports, "BODY_ARMORS", { enumerable: true, get: function () { return armorCatalog_1.BODY_ARMORS; } });
Object.defineProperty(exports, "GENERIC_ARMOR", { enumerable: true, get: function () { return armorCatalog_1.GENERIC_ARMOR; } });
Object.defineProperty(exports, "HELMETS", { enumerable: true, get: function () { return armorCatalog_1.HELMETS; } });
Object.defineProperty(exports, "TRAUMA_PLATES", { enumerable: true, get: function () { return armorCatalog_1.TRAUMA_PLATES; } });
var genericCatalog_1 = require("./genericCatalog");
Object.defineProperty(exports, "BACKPACK", { enumerable: true, get: function () { return genericCatalog_1.BACKPACK; } });
Object.defineProperty(exports, "RIFLE_SLING", { enumerable: true, get: function () { return genericCatalog_1.RIFLE_SLING; } });
var rangedCatalog_1 = require("./rangedCatalog");
Object.defineProperty(exports, "GENERIC_LONGRIFLE", { enumerable: true, get: function () { return rangedCatalog_1.GENERIC_LONGRIFLE; } });
