import { ArmorDefinition, ArmorInstance, ContainerDefinition, ContainerInstance, ItemDefinition, ItemInstance, RangedWeaponDefinition } from "./types";
import type { ArmorDefinitionInit, ArmorInstanceInit, AmorphousEquipmentContainer, AmorphousEquipmentOptions, ContainerDefinitionInit, ContainerInstanceInit, HumanoidEquipmentContainer, HumanoidEquipmentOptions, InventoryContents, ItemDefinitionInit, ItemInstanceInit, InventoryLocation, InventoryState, QuadrupedEquipmentContainer, QuadrupedEquipmentOptions, StorageMode, VoucherDefinition, VoucherPool, VoucherUsage, RangedWeaponDefinitionInit } from "./types";
export { DEFAULT_AMORPHOUS_EQUIPMENT_VOUCHER_LIMITS, DEFAULT_AMORPHOUS_EQUIPMENT_VOUCHERS, DEFAULT_HUMANOID_EQUIPMENT_VOUCHER_LIMITS, DEFAULT_HUMANOID_EQUIPMENT_VOUCHERS, DEFAULT_QUADRUPED_EQUIPMENT_VOUCHER_LIMITS, DEFAULT_QUADRUPED_EQUIPMENT_VOUCHERS, } from "./equipmentLayouts";
export declare function createInventoryState(items?: ItemInstance[], containers?: ContainerInstance[]): InventoryState;
export declare function createContainerDefinition(input: ContainerDefinitionInit): ContainerDefinition;
export declare function createVoucherContainerDefinition(id: string, name: string, voucherLimits: VoucherPool, defaultMode?: StorageMode): ContainerDefinition;
export declare function createTypedVoucherContainerDefinition(id: string, name: string, voucherDefinitions: VoucherDefinition[], defaultMode?: StorageMode): ContainerDefinition;
export declare function createContainer(id: string, name: string, mode: StorageMode, location?: InventoryLocation): ContainerInstance;
export declare function createVoucherContainer(id: string, name: string, voucherLimits: VoucherPool, mode?: StorageMode, location?: InventoryLocation): ContainerInstance;
export declare function createTypedVoucherContainer(id: string, name: string, voucherDefinitions: VoucherDefinition[], mode?: StorageMode, location?: InventoryLocation): ContainerInstance;
export declare function createItemDefinition(input: ItemDefinitionInit): ItemDefinition;
export declare function createRangedWeaponDefinition(input: RangedWeaponDefinitionInit): RangedWeaponDefinition;
export declare function createArmorDefinition(input: ArmorDefinitionInit): ArmorDefinition;
export declare function createItem(input: ItemInstanceInit): ItemInstance;
export declare function createArmor(input: ArmorInstanceInit): ArmorInstance;
export declare function instantiateItem(definition: ItemDefinition, input?: {
    quantity?: number;
    location?: InventoryLocation;
    attachmentIds?: string[];
    attachedToItemId?: string;
    carryMode?: string;
}): ItemInstance;
export declare function instantiateContainer(definition: ContainerDefinition, input?: Omit<ContainerInstanceInit, keyof ContainerDefinitionInit>): ContainerInstance;
export declare function createHumanoidEquipmentContainer(options?: HumanoidEquipmentOptions): HumanoidEquipmentContainer;
export declare function createQuadrupedEquipmentContainer(options?: QuadrupedEquipmentOptions): QuadrupedEquipmentContainer;
export declare function createAmorphousEquipmentContainer(options?: AmorphousEquipmentOptions): AmorphousEquipmentContainer;
export declare function addContainer(state: InventoryState, container: ContainerInstance): InventoryState;
export declare function addItem(state: InventoryState, item: ItemInstance): InventoryState;
export declare function attachItem(state: InventoryState, hostItemId: string, attachmentItemId: string): InventoryState;
export declare function detachItem(state: InventoryState, attachmentItemId: string): InventoryState;
export declare function setItemCarryMode(state: InventoryState, itemId: string, carryMode: string): InventoryState;
export declare function addHumanoidEquipmentContainer(state: InventoryState, options?: HumanoidEquipmentOptions): InventoryState;
export declare function addQuadrupedEquipmentContainer(state: InventoryState, options?: QuadrupedEquipmentOptions): InventoryState;
export declare function addAmorphousEquipmentContainer(state: InventoryState, options?: AmorphousEquipmentOptions): InventoryState;
export declare function toggleContainerMode(state: InventoryState, containerId: string): InventoryState;
export declare function moveItem(state: InventoryState, itemId: string, destination: InventoryLocation): InventoryState;
export declare function moveContainer(state: InventoryState, containerId: string, destination: InventoryLocation): InventoryState;
export declare function getContents(state: InventoryState, location?: InventoryLocation): InventoryContents;
export declare function getContainerContents(state: InventoryState, containerId: string): InventoryContents;
export declare function getContainerVoucherUsage(state: InventoryState, containerId: string): VoucherUsage;
export declare function canMoveItemToContainer(state: InventoryState, itemId: string, containerId: string): boolean;
export declare function getEffectiveItemVoucherCost(state: InventoryState, itemId: string): VoucherPool;
export declare function getRootContents(state: InventoryState): InventoryContents;
//# sourceMappingURL=inventory.d.ts.map