"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MEDICAL_CATALOG = exports.AUTOINJECTORS = exports.PHARMACEUTICALS = exports.IV_SUPPLIES = exports.MEDICAL_CONSUMABLES = exports.MEDICAL_TOOL_SETS = exports.MEDICAL_TOOLS = exports.FIRST_AID_KITS = void 0;
const inventory_1 = require("./inventory");
const SRC_229 = "Source: Twilight 2013 Core OEF PDF p.229";
const SRC_230 = "Source: Twilight 2013 Core OEF PDF p.230";
// ---------------------------------------------------------------------------
// First Aid Kits
// ---------------------------------------------------------------------------
exports.FIRST_AID_KITS = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:kit:boo-boo",
        name: "Boo-Boo Kit",
        weight: 0.2,
        tags: ["medical", "first-aid-kit"],
        barterValue: "GG1",
        streetPrice: 20,
        traits: ["kit:contains:pain-reliever-mild:1"],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:kit:civilian-first-aid",
        name: "Civilian First Aid Kit",
        weight: 0.8,
        tags: ["medical", "first-aid-kit"],
        barterValue: "GG22.5",
        streetPrice: 90,
        traits: [
            "kit:contains:first-aid-supplies:2",
            "kit:contains:pain-reliever-mild:2",
            "kit:contains:antidiarrheal-pill:1",
        ],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:kit:field-medic",
        name: "Field Medic Kit",
        weight: 1.9,
        tags: ["medical", "first-aid-kit", "military-medical"],
        barterValue: "GG400",
        streetPrice: 300,
        traits: [
            "kit:contains:first-aid-supplies:4",
            "kit:contains:pain-reliever-strong-injected:8",
            "kit:contains:clotting-agent:4",
            "kit:contains:emt-shears:1",
        ],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:kit:ifak",
        name: "IFAK",
        weight: 0.6,
        tags: ["medical", "first-aid-kit", "military-medical"],
        barterValue: "GG55",
        streetPrice: 110,
        traits: [
            "kit:contains:first-aid-supplies:2",
            "kit:contains:pain-reliever-strong-injected:1",
            "kit:contains:clotting-agent:1",
        ],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:kit:site-first-aid",
        name: "Site First Aid Kit",
        weight: 2,
        tags: ["medical", "first-aid-kit"],
        barterValue: "GG50",
        streetPrice: 100,
        traits: [
            "kit:contains:first-aid-supplies:4",
            "kit:contains:emt-shears:1",
        ],
        source: [SRC_229],
    }),
];
// ---------------------------------------------------------------------------
// Specific Medical Tools
// ---------------------------------------------------------------------------
exports.MEDICAL_TOOLS = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:tool:aed",
        name: "AED",
        weight: 1.5,
        tags: ["medical", "medical-tool", "electronic"],
        barterValue: "GG2500",
        streetPrice: 2500,
        traits: ["medicine-skill:competent", "power:battery:lg-specialist:24h"],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:tool:body-bag",
        name: "Body Bag",
        weight: 2,
        tags: ["medical", "medical-tool"],
        barterValue: "GG1",
        streetPrice: 40,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:tool:emt-shears",
        name: "EMT Shears",
        weight: 0.2,
        tags: ["medical", "medical-tool"],
        barterValue: "GG0.5",
        streetPrice: 10,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:tool:litter-folding",
        name: "Litter, Folding",
        weight: 6,
        tags: ["medical", "medical-tool"],
        barterValue: "GG10",
        streetPrice: 400,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:tool:stethoscope",
        name: "Stethoscope",
        weight: 0.2,
        tags: ["medical", "medical-tool"],
        barterValue: "GG100",
        streetPrice: 100,
        source: [SRC_229],
    }),
];
// ---------------------------------------------------------------------------
// Medical Tool Sets
// ---------------------------------------------------------------------------
exports.MEDICAL_TOOL_SETS = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:toolset:gp",
        name: "GP Tools",
        weight: 5,
        tags: ["medical", "medical-toolset"],
        barterValue: "GG500",
        streetPrice: 1000,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:toolset:dental",
        name: "Dental Tools",
        weight: 1,
        tags: ["medical", "medical-toolset", "dental"],
        barterValue: "GG500",
        streetPrice: 500,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:toolset:surgical-basic",
        name: "Surgical Tools, Basic",
        weight: 1,
        tags: ["medical", "medical-toolset", "surgical"],
        barterValue: "GG250",
        streetPrice: 250,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:toolset:surgical-comprehensive",
        name: "Surgical Tools, Comprehensive",
        weight: 12,
        tags: ["medical", "medical-toolset", "surgical"],
        barterValue: "GG10000",
        streetPrice: 10000,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:toolset:surgical-disposable",
        name: "Surgical Tools, Disposable",
        weight: 0.8,
        tags: ["medical", "medical-toolset", "surgical"],
        barterValue: "GG50",
        streetPrice: 100,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:toolset:surgical-specialized",
        name: "Surgical Tools, Specialized",
        weight: 4,
        tags: ["medical", "medical-toolset", "surgical"],
        barterValue: "GG8000",
        streetPrice: 8000,
        source: [SRC_229],
    }),
];
// ---------------------------------------------------------------------------
// Basic Medical Consumables (per unit)
// ---------------------------------------------------------------------------
exports.MEDICAL_CONSUMABLES = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:burn-cream",
        name: "Burn Cream",
        weight: 0.1,
        tags: ["medical", "medical-consumable"],
        barterValue: "GG25",
        streetPrice: 25,
        traits: ["first-aid-bonus:burn:+2"],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:clotting-agent",
        name: "Clotting Agent",
        weight: 0.1,
        tags: ["medical", "medical-consumable"],
        barterValue: "GG60",
        streetPrice: 30,
        traits: ["first-aid-bonus:penetrating:+2", "stabilization-bonus:+1"],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:dental-supplies",
        name: "Dental Supplies",
        weight: 1.8,
        tags: ["medical", "medical-consumable", "dental"],
        barterValue: "GG200",
        streetPrice: 200,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:first-aid-supplies",
        name: "First Aid Supplies",
        weight: 0.2,
        tags: ["medical", "medical-consumable"],
        barterValue: "GG7.5",
        streetPrice: 30,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:hydration-salts",
        name: "Hydration Salts",
        weight: 0,
        tags: ["medical", "medical-consumable"],
        barterValue: "GG0.05",
        streetPrice: 1,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:surgical-supplies",
        name: "Surgical Supplies",
        weight: 1.8,
        tags: ["medical", "medical-consumable", "surgical"],
        barterValue: "GG200",
        streetPrice: 200,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:syringes-100",
        name: "Syringes, Disposable (100)",
        weight: 0.2,
        tags: ["medical", "medical-consumable"],
        barterValue: "GG12.5",
        streetPrice: 25,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:supply:blood-typing-chemicals",
        name: "Blood Typing Chemicals",
        weight: 0.1,
        tags: ["medical", "medical-consumable"],
        barterValue: "GG37.5",
        streetPrice: 75,
        source: [SRC_229],
    }),
];
// ---------------------------------------------------------------------------
// IV Supplies (per unit)
// ---------------------------------------------------------------------------
exports.IV_SUPPLIES = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:iv:blood-artificial",
        name: "Blood, Artificial (450 mL)",
        weight: 0.5,
        tags: ["medical", "iv-supply", "blood-product"],
        barterValue: "GG250",
        streetPrice: 500,
        traits: ["blood-compatible:universal"],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:iv:blood-whole",
        name: "Blood, Whole (450 mL)",
        weight: 0.5,
        tags: ["medical", "iv-supply", "blood-product"],
        barterValue: "GG2.5",
        streetPrice: 25,
        traits: ["requires-refrigeration", "blood-type:variable"],
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:iv:fluids-1l",
        name: "IV Fluids (1 Liter)",
        weight: 1,
        tags: ["medical", "iv-supply"],
        barterValue: "GG10",
        streetPrice: 20,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:iv:plasma-freeze-dried",
        name: "Plasma, Freeze-Dried (450 mL)",
        weight: 0.6,
        tags: ["medical", "iv-supply", "blood-product"],
        barterValue: "GG60",
        streetPrice: 30,
        source: [SRC_229],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:iv:plasma-liquid",
        name: "Plasma, Liquid (450 mL)",
        weight: 0.5,
        tags: ["medical", "iv-supply", "blood-product"],
        barterValue: "GG10",
        streetPrice: 25,
        traits: ["requires-refrigeration"],
        source: [SRC_229],
    }),
];
// ---------------------------------------------------------------------------
// Pharmaceuticals (per unit)
// ---------------------------------------------------------------------------
exports.PHARMACEUTICALS = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:anesthetic-local",
        name: "Anesthetic, Local",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "anesthetic"],
        barterValue: "GG1",
        streetPrice: 2,
        traits: ["pharma:form:injected"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:anesthetic-total-tank",
        name: "Anesthetic, Total (20-Unit Tank)",
        weight: 0.7,
        tags: ["medical", "pharmaceutical", "anesthetic"],
        barterValue: "GG80",
        streetPrice: 200,
        traits: ["pharma:form:gas"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:anesthetic-total-injected",
        name: "Anesthetic, Total",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "anesthetic"],
        barterValue: "GG20",
        streetPrice: 40,
        traits: ["pharma:form:injected"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antibiotic-broad-injected",
        name: "Antibiotic, Broad-Spectrum (Injected)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "antibiotic"],
        barterValue: "GG30",
        streetPrice: 30,
        traits: ["pharma:form:injected", "requires-refrigeration", "pharma:class:antibiotic-broad-spectrum"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antibiotic-broad-pill",
        name: "Antibiotic, Broad-Spectrum (Pill)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "antibiotic"],
        barterValue: "GG60",
        streetPrice: 60,
        traits: ["pharma:form:pill", "pharma:class:antibiotic-broad-spectrum"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antibiotic-gram-negative-injected",
        name: "Antibiotic, Gram-Negative (Injected)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "antibiotic"],
        barterValue: "GG30",
        streetPrice: 30,
        traits: ["pharma:form:injected", "requires-refrigeration", "pharma:class:antibiotic-gram-negative"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antibiotic-gram-negative-pill",
        name: "Antibiotic, Gram-Negative (Pill)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "antibiotic"],
        barterValue: "GG60",
        streetPrice: 60,
        traits: ["pharma:form:pill", "pharma:class:antibiotic-gram-negative"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antibiotic-gram-positive-injected",
        name: "Antibiotic, Gram-Positive (Injected)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "antibiotic"],
        barterValue: "GG30",
        streetPrice: 30,
        traits: ["pharma:form:injected", "requires-refrigeration", "pharma:class:antibiotic-gram-positive"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antibiotic-gram-positive-pill",
        name: "Antibiotic, Gram-Positive (Pill)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "antibiotic"],
        barterValue: "GG60",
        streetPrice: 60,
        traits: ["pharma:form:pill", "pharma:class:antibiotic-gram-positive"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antidepressant",
        name: "Antidepressant",
        weight: 0.1,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG8.75",
        streetPrice: 35,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antidiarrheal-liquid",
        name: "Antidiarrheal (Liquid)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG0.05",
        streetPrice: 1,
        traits: ["pharma:form:oral-liquid"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antidiarrheal-pill",
        name: "Antidiarrheal (Pill)",
        weight: 0.02,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG0.1",
        streetPrice: 1,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antihistamine",
        name: "Antihistamine",
        weight: 0.05,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG0.5",
        streetPrice: 10,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:atropine-2pamci",
        name: "Atropine/2-PAM-CI",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "nerve-agent-treatment"],
        barterValue: "GG2",
        streetPrice: 20,
        traits: ["pharma:form:injected"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:antivenin",
        name: "Antivenin, Specific",
        weight: 0.05,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG200",
        streetPrice: 200,
        traits: ["pharma:form:injected", "requires-refrigeration"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:birth-control",
        name: "Birth Control",
        weight: 0.3,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG18",
        streetPrice: 90,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:insulin",
        name: "Insulin",
        weight: 0.2,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG250",
        streetPrice: 200,
        traits: ["pharma:form:injected", "requires-refrigeration"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:maintenance-drugs",
        name: "Maintenance Drugs, Specific",
        weight: 0.1,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG500",
        streetPrice: 400,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:pain-reliever-mild",
        name: "Pain Reliever, Mild",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "pain-reliever"],
        barterValue: "GG0.01",
        streetPrice: 0.2,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:pain-reliever-strong-injected",
        name: "Pain Reliever, Strong (Injected)",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "pain-reliever"],
        barterValue: "GG0.5",
        streetPrice: 1,
        traits: ["pharma:form:injected", "requires-refrigeration"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:pain-reliever-strong-pill",
        name: "Pain Reliever, Strong (Pill)",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "pain-reliever"],
        barterValue: "GG1",
        streetPrice: 1,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:potassium-iodide",
        name: "Potassium Iodide",
        weight: 0.5,
        tags: ["medical", "pharmaceutical", "radiation-treatment"],
        barterValue: "GG100",
        streetPrice: 200,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:sedative-mild-liquid",
        name: "Sedative, Mild (Liquid)",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "sedative"],
        barterValue: "GG0.5",
        streetPrice: 10,
        traits: ["pharma:form:oral-liquid"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:sedative-mild-pill",
        name: "Sedative, Mild (Pill)",
        weight: 0.02,
        tags: ["medical", "pharmaceutical", "sedative"],
        barterValue: "GG1",
        streetPrice: 10,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:sedative-strong-injected",
        name: "Sedative, Strong (Injected)",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "sedative"],
        barterValue: "GG1",
        streetPrice: 5,
        traits: ["pharma:form:injected", "requires-refrigeration"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:sedative-strong-pill",
        name: "Sedative, Strong (Pill)",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "sedative"],
        barterValue: "GG2.5",
        streetPrice: 5,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:stimulant-mild",
        name: "Stimulant, Mild",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "stimulant"],
        barterValue: "GG0.25",
        streetPrice: 1,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:stimulant-strong",
        name: "Stimulant, Strong",
        weight: 0.01,
        tags: ["medical", "pharmaceutical", "stimulant"],
        barterValue: "GG1.25",
        streetPrice: 10,
        traits: ["pharma:form:injected"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:vaccine",
        name: "Vaccine, Specific",
        weight: 0.05,
        tags: ["medical", "pharmaceutical", "vaccine"],
        barterValue: "GG50",
        streetPrice: 50,
        traits: ["pharma:form:injected", "requires-refrigeration"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:pharma:vitamins",
        name: "Vitamins",
        weight: 0.2,
        tags: ["medical", "pharmaceutical"],
        barterValue: "GG2",
        streetPrice: 20,
        traits: ["pharma:form:pill"],
        source: [SRC_230],
    }),
];
// ---------------------------------------------------------------------------
// Autoinjectors
// ---------------------------------------------------------------------------
exports.AUTOINJECTORS = [
    (0, inventory_1.createItemDefinition)({
        id: "medical:autoinjector:atropine-2pamci",
        name: "Autoinjector, Atropine/2-PAM-CI",
        weight: 0.1,
        tags: ["medical", "pharmaceutical", "autoinjector", "nerve-agent-treatment"],
        barterValue: "GG5",
        streetPrice: 50,
        traits: ["pharma:form:injected", "autoinjector"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:autoinjector:pain-reliever-strong",
        name: "Autoinjector, Pain Reliever (Strong)",
        weight: 0.1,
        tags: ["medical", "pharmaceutical", "autoinjector", "pain-reliever"],
        barterValue: "GG6",
        streetPrice: 60,
        traits: ["pharma:form:injected", "autoinjector"],
        source: [SRC_230],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "medical:autoinjector:stimulant-strong",
        name: "Autoinjector, Stimulant (Strong)",
        weight: 0.1,
        tags: ["medical", "pharmaceutical", "autoinjector", "stimulant"],
        barterValue: "GG4",
        streetPrice: 40,
        traits: ["pharma:form:injected", "autoinjector"],
        source: [SRC_230],
    }),
];
// ---------------------------------------------------------------------------
// Aggregate
// ---------------------------------------------------------------------------
exports.MEDICAL_CATALOG = [
    ...exports.FIRST_AID_KITS,
    ...exports.MEDICAL_TOOLS,
    ...exports.MEDICAL_TOOL_SETS,
    ...exports.MEDICAL_CONSUMABLES,
    ...exports.IV_SUPPLIES,
    ...exports.PHARMACEUTICALS,
    ...exports.AUTOINJECTORS,
];
