"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MEDIA_CATALOG = exports.ELECTRONIC_MEDIA = exports.BOOKS = void 0;
const inventory_1 = require("./inventory");
const SRC_241 = "Source: Twilight 2013 Core OEF PDF p.241";
exports.BOOKS = [
    (0, inventory_1.createItemDefinition)({
        id: "media:book-novel-paperback",
        name: "Novel, Paperback",
        weight: 0.3,
        tags: ["media", "book", "entertainment"],
        barterValue: "GG0.25",
        streetPrice: 10,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:book-novel-hardcover",
        name: "Novel, Hardcover",
        weight: 1.2,
        tags: ["media", "book", "entertainment"],
        barterValue: "GG0.75",
        streetPrice: 30,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:book-reference-hardcover",
        name: "Reference Book, Hardcover",
        weight: 2,
        tags: ["media", "book", "reference"],
        barterValue: "GG12.5",
        streetPrice: 100,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:book-shop-manual-paperback",
        name: "Shop Manual, Paperback",
        weight: 0.5,
        tags: ["media", "book", "technical", "repair"],
        barterValue: "GG6.25",
        streetPrice: 50,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:book-textbook-novice",
        name: "Textbook, Novice",
        weight: 1.5,
        tags: ["media", "book", "education"],
        barterValue: "GG25",
        streetPrice: 100,
        source: [SRC_241],
        traits: ["skill-instruction:novice"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:book-textbook-competent",
        name: "Textbook, Competent",
        weight: 1.6,
        tags: ["media", "book", "education"],
        barterValue: "GG50",
        streetPrice: 200,
        source: [SRC_241],
        traits: ["skill-instruction:competent"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:book-textbook-professional",
        name: "Textbook, Professional",
        weight: 1.8,
        tags: ["media", "book", "education"],
        barterValue: "GG50",
        streetPrice: 200,
        source: [SRC_241],
        traits: ["skill-instruction:professional"],
    }),
];
exports.ELECTRONIC_MEDIA = [
    (0, inventory_1.createItemDefinition)({
        id: "media:disc-music-cd",
        name: "Music CD",
        weight: 0.1,
        tags: ["media", "disc", "audio", "entertainment"],
        barterValue: "GG0.15",
        streetPrice: 15,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:disc-shop-manual-cdrom",
        name: "Shop Manual, CD-ROM",
        weight: 0.3,
        tags: ["media", "disc", "technical", "repair"],
        barterValue: "GG6.25",
        streetPrice: 100,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:disc-textbook-cdrom-novice",
        name: "Textbook, CD-ROM, Novice",
        weight: 0.2,
        tags: ["media", "disc", "education"],
        barterValue: "GG30",
        streetPrice: 150,
        source: [SRC_241],
        traits: ["skill-instruction:novice"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:disc-textbook-cdrom-competent",
        name: "Textbook, CD-ROM, Competent",
        weight: 0.3,
        tags: ["media", "disc", "education"],
        barterValue: "GG60",
        streetPrice: 300,
        source: [SRC_241],
        traits: ["skill-instruction:competent"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:disc-textbook-cdrom-professional",
        name: "Textbook, CD-ROM, Professional",
        weight: 0.4,
        tags: ["media", "disc", "education"],
        barterValue: "GG60",
        streetPrice: 300,
        source: [SRC_241],
        traits: ["skill-instruction:professional"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:disc-video-dvd",
        name: "Video DVD",
        weight: 0.1,
        tags: ["media", "disc", "video", "entertainment"],
        barterValue: "GG0.25",
        streetPrice: 20,
        source: [SRC_241],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "media:cartridge-video-game-portable",
        name: "Video Game Cartridge, Portable",
        weight: 0,
        tags: ["media", "gaming", "entertainment"],
        barterValue: "GG0.1",
        streetPrice: 50,
        source: [SRC_241],
    }),
];
exports.MEDIA_CATALOG = [
    ...exports.BOOKS,
    ...exports.ELECTRONIC_MEDIA,
];
