"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PERSONAL_CATALOG = exports.MISC_GEAR = exports.TIMEPIECES = exports.PERSONAL_ACCESSORIES = void 0;
const inventory_1 = require("./inventory");
// Personal Accessories, Timepieces, and Miscellaneous Gear (Table 7x continued, p.243)
const SRC_243 = "Source: Twilight 2013 Core OEF PDF p.243";
exports.PERSONAL_ACCESSORIES = [
    (0, inventory_1.createItemDefinition)({
        id: "personal:contact-lenses",
        name: "Contact Lenses",
        weight: 0,
        tags: ["personal", "vision-correction", "consumable"],
        barterValue: "GG9",
        streetPrice: 90,
        source: [SRC_243],
        description: "Three-month supply of prescription contact lenses with cleaning solution and case.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:eyeglasses-prescription",
        name: "Eyeglasses, Prescription",
        weight: 0,
        tags: ["personal", "vision-correction"],
        barterValue: "GG15",
        streetPrice: 150,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:eyeglasses-reading",
        name: "Eyeglasses, Reading",
        weight: 0,
        tags: ["personal", "vision-correction"],
        barterValue: "GG0.25",
        streetPrice: 10,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:hearing-aid",
        name: "Hearing Aid",
        weight: 0,
        tags: ["personal", "hearing"],
        barterValue: "GG10",
        streetPrice: 100,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:sunglasses",
        name: "Sunglasses",
        weight: 0,
        tags: ["personal", "eye-protection"],
        barterValue: "GG2.5",
        streetPrice: 50,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:sunglasses-prescription",
        name: "Sunglasses, Prescription",
        weight: 0,
        tags: ["personal", "eye-protection", "vision-correction"],
        barterValue: "GG20",
        streetPrice: 200,
        source: [SRC_243],
    }),
];
exports.TIMEPIECES = [
    (0, inventory_1.createItemDefinition)({
        id: "personal:watch-pocket",
        name: "Pocket Watch",
        weight: 0.2,
        tags: ["personal", "timepiece"],
        barterValue: "GG4",
        streetPrice: 40,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:watch-stopwatch",
        name: "Stopwatch",
        weight: 0.2,
        tags: ["personal", "timepiece"],
        barterValue: "GG3.75",
        streetPrice: 30,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:watch-wristwatch-basic",
        name: "Wristwatch, Basic",
        weight: 0.1,
        tags: ["personal", "timepiece"],
        barterValue: "GG5",
        streetPrice: 100,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:watch-wristwatch-complex",
        name: "Wristwatch, Complex",
        weight: 0.2,
        tags: ["personal", "timepiece"],
        barterValue: "GG15",
        streetPrice: 300,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "personal:watch-wristwatch-gps",
        name: "Wristwatch, GPS",
        weight: 0.1,
        tags: ["personal", "timepiece", "gps"],
        barterValue: "GG150",
        streetPrice: 300,
        source: [SRC_243],
        traits: ["gps-civilian"],
    }),
];
exports.MISC_GEAR = [
    (0, inventory_1.createItemDefinition)({
        id: "gear:duct-tape",
        name: "Duct Tape, 50m Roll",
        weight: 0.2,
        tags: ["gear", "misc", "repair"],
        barterValue: "GG0.2",
        streetPrice: 5,
        source: [SRC_243],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:handcuffs",
        name: "Handcuffs",
        weight: 0.3,
        tags: ["gear", "restraint"],
        barterValue: "GG42.5",
        streetPrice: 85,
        source: [SRC_243],
        description: "Standard police-issue handcuffs with 2 keys.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:insect-repellent",
        name: "Insect Repellent",
        weight: 0.3,
        tags: ["gear", "consumable", "personal-care"],
        barterValue: "GG0.3",
        streetPrice: 12,
        source: [SRC_243],
        description: "Aerosol or stick formula effective against midges and mosquitoes for ~6 hours per use. Each can holds 25 applications.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:leg-irons",
        name: "Leg Irons",
        weight: 1.2,
        tags: ["gear", "restraint"],
        barterValue: "GG18",
        streetPrice: 72,
        source: [SRC_243],
        description: "Restraints for legs. Wearer suffers the effects of a moderate virtual leg injury to both legs.",
        traits: ["restraint-leg-moderate-virtual-injury"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:scales-laboratory-digital",
        name: "Scales, Laboratory, Digital",
        weight: 3.2,
        tags: ["gear", "measuring"],
        barterValue: "GG25",
        streetPrice: 250,
        source: [SRC_243],
        description: "Digital laboratory scales accurate to 0.01 g, capacity 4 kg. Requires 2 small batteries (1-year life).",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:scales-laboratory-mechanical",
        name: "Scales, Laboratory, Mechanical",
        weight: 6.8,
        tags: ["gear", "measuring"],
        barterValue: "GG10",
        streetPrice: 100,
        source: [SRC_243],
        description: "Mechanical laboratory scales accurate to 0.1 g, capacity 4 kg. No batteries required.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:weights-standard",
        name: "Weights, Standard",
        weight: 0.111,
        tags: ["gear", "measuring"],
        barterValue: "GG1",
        streetPrice: 25,
        source: [SRC_243],
        description: "Laboratory-grade 1g, 10g, and 100g weights for calibrating scales.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "gear:zip-ties",
        name: "Zip Ties, Bag of 50",
        weight: 0.2,
        tags: ["gear", "fastener", "restraint"],
        barterValue: "GG0.5",
        streetPrice: 5,
        source: [SRC_243],
        description: "Heavy-duty plastic cable ties. Not reusable; must be cut off.",
    }),
];
exports.PERSONAL_CATALOG = [
    ...exports.PERSONAL_ACCESSORIES,
    ...exports.TIMEPIECES,
    ...exports.MISC_GEAR,
];
