"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SIGNAL_CATALOG = void 0;
const inventory_1 = require("./inventory");
exports.SIGNAL_CATALOG = [
    (0, inventory_1.createItemDefinition)({
        id: "signal:whistle",
        name: "Whistle",
        weight: 0,
        tags: ["signal", "non-electronic", "audible", "communication"],
        barterValue: "GG0.05",
        streetPrice: 2,
        notes: ["Source: Twilight 2013 Core OEF PDF p.221"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:mirror",
        name: "Signal Mirror",
        weight: 0.1,
        tags: ["signal", "non-electronic", "visual"],
        barterValue: "GG0.04",
        streetPrice: 2,
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
        description: "Aiming mirror used to flash long-range daylight recognition signals.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:panel-marker",
        name: "Signal Panel",
        weight: 0.1,
        tags: ["signal", "non-electronic", "visual", "marker"],
        barterValue: "GG0.18",
        streetPrice: 9,
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
        description: "High-contrast foldable panel for ground-to-air recognition and position marking.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:flare-aerial",
        name: "Flare, Aerial",
        weight: 0,
        tags: ["signal", "non-electronic", "visual", "pyrotechnic"],
        barterValue: "GG0.12",
        streetPrice: 3,
        duration: "3d6+10 seconds",
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:flare-gun",
        name: "Flare Gun",
        weight: 1,
        tags: ["signal", "non-electronic", "visual", "pyrotechnic", "launcher"],
        barterValue: "GG35",
        streetPrice: 70,
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:flare-ground",
        name: "Flare, Ground",
        weight: 0.1,
        tags: ["signal", "non-electronic", "visual", "marker"],
        barterValue: "GG0.3",
        streetPrice: 3,
        duration: "20+1d20 minutes",
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:flare-ground-ir",
        name: "Flare, Ground, IR",
        weight: 0.1,
        tags: ["signal", "non-electronic", "visual", "infrared", "marker"],
        barterValue: "GG3",
        streetPrice: 60,
        duration: "20+1d20 minutes",
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:flare-launcher-hand-held",
        name: "Flare Launcher, Hand-held",
        weight: 0.1,
        tags: ["signal", "non-electronic", "visual", "pyrotechnic", "launcher"],
        barterValue: "GG0.9",
        streetPrice: 15,
        notes: ["Source: Twilight 2013 Core OEF PDF p.220"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "signal:bugle",
        name: "Bugle",
        weight: 1,
        tags: ["signal", "non-electronic", "audible", "communication"],
        barterValue: "GG24",
        streetPrice: 120,
        notes: ["Source: Twilight 2013 Core OEF PDF p.221"],
    }),
];
