"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STORAGE_CATALOG = exports.DRY_GOODS_STORAGE = exports.LIQUID_STORAGE = void 0;
const inventory_1 = require("./inventory");
const SRC_244 = "Source: Twilight 2013 Core OEF PDF p.244";
// ── Liquid Storage ────────────────────────────────────────────────────────────
exports.LIQUID_STORAGE = [
    (0, inventory_1.createItemDefinition)({
        id: "storage:bulk-tank-750l",
        name: "Bulk Tank, 750 L",
        weight: 100,
        tags: ["storage", "liquid", "bulk-tank"],
        barterValue: "GG20",
        streetPrice: 400,
        source: [SRC_244],
        description: "Plastic container in protective metal frame for bulk liquid transport.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:bulk-tank-1000l",
        name: "Bulk Tank, 1,000 L",
        weight: 130,
        tags: ["storage", "liquid", "bulk-tank"],
        barterValue: "GG30",
        streetPrice: 600,
        source: [SRC_244],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:bulk-tank-2000l",
        name: "Bulk Tank, 2,000 L",
        weight: 250,
        tags: ["storage", "liquid", "bulk-tank"],
        barterValue: "GG37.5",
        streetPrice: 750,
        source: [SRC_244],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:bulk-tank-4000l",
        name: "Bulk Tank, 4,000 L",
        weight: 520,
        tags: ["storage", "liquid", "bulk-tank"],
        barterValue: "GG60",
        streetPrice: 1200,
        source: [SRC_244],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:drum-metal-200l",
        name: "Drum, Metal, 200 L",
        weight: 17,
        tags: ["storage", "liquid", "drum"],
        barterValue: "GG10",
        streetPrice: 45,
        source: [SRC_244],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:drum-plastic-200l",
        name: "Drum, Plastic, 200 L",
        weight: 10,
        tags: ["storage", "liquid", "drum"],
        barterValue: "GG15",
        streetPrice: 65,
        source: [SRC_244],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:folding-bladder-20l",
        name: "Folding Bladder, 20 L",
        weight: 0.3,
        tags: ["storage", "liquid", "bladder", "portable"],
        barterValue: "GG1",
        streetPrice: 9,
        source: [SRC_244],
        description: "Flexible clear plastic container with handle and pour spout. Folds flat when empty.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:fuel-bladder-300l",
        name: "Fuel Bladder, 300 L",
        weight: 70,
        tags: ["storage", "liquid", "fuel", "bladder"],
        barterValue: "GG20",
        streetPrice: 700,
        source: [SRC_244],
        description: "Reinforced rubber container for bulk fuel transport. Can survive a 100m drop from a slow-moving aircraft.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:fuel-bladder-1100l",
        name: "Fuel Bladder, 1,100 L",
        weight: 250,
        tags: ["storage", "liquid", "fuel", "bladder"],
        barterValue: "GG30",
        streetPrice: 1000,
        source: [SRC_244],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:jerry-can-20l",
        name: "Jerry Can, 20 L",
        weight: 2,
        tags: ["storage", "liquid", "fuel", "jerry-can"],
        barterValue: "GG5",
        streetPrice: 25,
        source: [SRC_244],
        description: "Rectangular metal fuel canister.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:pump-hand",
        name: "Pump, Hand",
        weight: 11.3,
        tags: ["storage", "liquid", "pump"],
        barterValue: "GG25",
        streetPrice: 100,
        source: [SRC_244],
        description: "One-man pump for transferring liquids. Designed for 200 L drums; flow rate 35 L/min. Includes 3 m hose.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:pump-motorized",
        name: "Pump, Motorized",
        weight: 16,
        tags: ["storage", "liquid", "pump", "powered"],
        barterValue: "GG25",
        streetPrice: 230,
        source: [SRC_244],
        description: "Electric pump; flow rate 50 L/min. Requires 0.2 kW power supply.",
        traits: ["ac-powered-0.2kw"],
    }),
];
// ── Dry Goods Storage ─────────────────────────────────────────────────────────
exports.DRY_GOODS_STORAGE = [
    (0, inventory_1.createItemDefinition)({
        id: "storage:ammo-can",
        name: "Ammo Can",
        weight: 3,
        tags: ["storage", "dry-goods", "container", "ammo"],
        barterValue: "GG0.8",
        streetPrice: 8,
        source: [SRC_244],
        description: "Steel box with rubber-gasketed hinged lid. Resistant to immersion and dust. Holds ~800 rounds of 5.56x45mm.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:cargo-pallet",
        name: "Cargo Pallet",
        weight: 20,
        tags: ["storage", "dry-goods", "pallet"],
        barterValue: "GG0.75",
        streetPrice: 15,
        source: [SRC_244],
        description: "1 m² wood framework for shipping; supports up to 2 tons of cargo.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:handgun-case-hard",
        name: "Handgun Case, Hard",
        weight: 1,
        tags: ["storage", "dry-goods", "gun-case", "hard"],
        barterValue: "GG20",
        streetPrice: 40,
        source: [SRC_244],
        description: "Hard-sided case for a Bulk 1 weapon with integral combination lock and room for two magazines.",
        traits: ["armor-1", "combo-lock"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:handgun-case-soft",
        name: "Handgun Case, Soft",
        weight: 0.5,
        tags: ["storage", "dry-goods", "gun-case", "soft"],
        barterValue: "GG15",
        streetPrice: 30,
        source: [SRC_244],
        description: "Soft-sided case for a Bulk 1 weapon with room for two magazines.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:long-gun-case-hard",
        name: "Long Gun Case, Hard",
        weight: 4,
        tags: ["storage", "dry-goods", "gun-case", "hard"],
        barterValue: "GG40",
        streetPrice: 80,
        source: [SRC_244],
        description: "Hard-sided case for a Bulk 2–4 weapon.",
        traits: ["armor-1"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:long-gun-case-mlbe",
        name: "Long Gun Case, MLBE",
        weight: 1.7,
        tags: ["storage", "dry-goods", "gun-case", "mlbe"],
        barterValue: "GG50",
        streetPrice: 100,
        source: [SRC_244],
        description: "Soft long gun case with 12 MLBE attachment points.",
        traits: ["mlbe-12-points"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:long-gun-case-soft",
        name: "Long Gun Case, Soft",
        weight: 1.5,
        tags: ["storage", "dry-goods", "gun-case", "soft"],
        barterValue: "GG32.5",
        streetPrice: 65,
        source: [SRC_244],
        description: "Soft-sided case for a Bulk 2–4 weapon with shoulder strap.",
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:portable-refrigerator",
        name: "Portable Refrigerator",
        weight: 18,
        tags: ["storage", "dry-goods", "refrigerator", "medical"],
        barterValue: "GG950",
        streetPrice: 1900,
        source: [SRC_244],
        description: "15 L medical refrigerator for vaccines and donor organs. Runs on AC (0.1 kW) or 4 large batteries (5-day life). Lockable.",
        traits: ["ac-powered-0.1kw", "battery-4-lg-5-days"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:shipping-container-6m",
        name: "Shipping Container, 6 m",
        weight: 2200,
        tags: ["storage", "dry-goods", "shipping-container"],
        barterValue: "GG50",
        streetPrice: 2000,
        source: [SRC_244],
        description: "Standard 6 m intermodal container (2.4 m × 2.4 m × 6 m). Armor 1. Max load ~15 tons.",
        traits: ["armor-1"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:shipping-container-12m",
        name: "Shipping Container, 12 m",
        weight: 3700,
        tags: ["storage", "dry-goods", "shipping-container"],
        barterValue: "GG75",
        streetPrice: 3000,
        source: [SRC_244],
        description: "Standard 12 m intermodal container. Armor 1. Max load ~30 tons.",
        traits: ["armor-1"],
    }),
    (0, inventory_1.createItemDefinition)({
        id: "storage:shipping-container-16m",
        name: "Shipping Container, 16 m",
        weight: 4700,
        tags: ["storage", "dry-goods", "shipping-container"],
        barterValue: "GG90",
        streetPrice: 3500,
        source: [SRC_244],
        description: "Standard 16 m intermodal container. Armor 1. Max load ~40 tons.",
        traits: ["armor-1"],
    }),
];
exports.STORAGE_CATALOG = [
    ...exports.LIQUID_STORAGE,
    ...exports.DRY_GOODS_STORAGE,
];
