"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SOFTWARE_ITEMS = exports.COMPUTER_PERIPHERALS = exports.COMPUTER_SYSTEMS = void 0;
const helpers_1 = require("./helpers");
const SRC_239 = "Source: Twilight 2013 Core OEF PDF p.239";
const SRC_240 = "Source: Twilight 2013 Core OEF PDF p.240";
const SRC_241 = "Source: Twilight 2013 Core OEF PDF p.241";
// ── Computer Systems ─────────────────────────────────────────────────────────
// Generation traits: archaic → ×5 time, obsolete → ×3 time, modern → no modifier,
// sota → +1 bonus, cutting-edge → +3 bonus.
exports.COMPUTER_SYSTEMS = [
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:desktop-archaic",
        name: "Desktop, Archaic",
        weight: 30,
        tags: ["computing", "desktop", "archaic"],
        barterValue: "GG100",
        streetPrice: 200,
        kilowatts: 1.5,
        traits: ["computing-gen:archaic"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:desktop-obsolete",
        name: "Desktop, Obsolete",
        weight: 15,
        tags: ["computing", "desktop", "obsolete"],
        barterValue: "GG150",
        streetPrice: 800,
        kilowatts: 1.25,
        traits: ["computing-gen:obsolete"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:desktop-modern",
        name: "Desktop, Modern",
        weight: 10,
        tags: ["computing", "desktop", "modern"],
        barterValue: "GG200",
        streetPrice: 2000,
        kilowatts: 1,
        traits: ["computing-gen:modern"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:desktop-sota",
        name: "Desktop, SOTA",
        weight: 11,
        tags: ["computing", "desktop", "sota"],
        barterValue: "GG500",
        streetPrice: 5000,
        kilowatts: 1.5,
        traits: ["computing-gen:sota"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:desktop-cutting-edge",
        name: "Desktop, Cutting-Edge",
        weight: 12,
        tags: ["computing", "desktop", "cutting-edge"],
        barterValue: "GG1,000",
        streetPrice: 10000,
        kilowatts: 2,
        traits: ["computing-gen:cutting-edge"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:notebook-archaic",
        name: "Notebook, Archaic",
        weight: 4.5,
        tags: ["computing", "notebook", "portable", "archaic"],
        barterValue: "GG100",
        streetPrice: 400,
        powerRequirement: "charge/4 hrs",
        runtimeHours: 4,
        traits: ["computing-gen:archaic"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:notebook-obsolete",
        name: "Notebook, Obsolete",
        weight: 3.5,
        tags: ["computing", "notebook", "portable", "obsolete"],
        barterValue: "GG200",
        streetPrice: 1000,
        powerRequirement: "charge/3.5 hrs",
        runtimeHours: 3.5,
        traits: ["computing-gen:obsolete"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:notebook-modern",
        name: "Notebook, Modern",
        weight: 2.5,
        tags: ["computing", "notebook", "portable", "modern"],
        barterValue: "GG300",
        streetPrice: 3000,
        powerRequirement: "charge/3 hrs",
        runtimeHours: 3,
        traits: ["computing-gen:modern"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:notebook-sota",
        name: "Notebook, SOTA",
        weight: 1.5,
        tags: ["computing", "notebook", "portable", "sota"],
        barterValue: "GG600",
        streetPrice: 6000,
        powerRequirement: "charge/2.5 hrs",
        runtimeHours: 2.5,
        traits: ["computing-gen:sota"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:notebook-ruggedized-obsolete",
        name: "Notebook, Ruggedized, Obsolete",
        weight: 5,
        tags: ["computing", "notebook", "ruggedized", "portable", "obsolete"],
        barterValue: "GG500",
        streetPrice: 2500,
        powerRequirement: "charge/3 hrs",
        runtimeHours: 3,
        traits: ["computing-gen:obsolete", "wear-environment-reduced"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:notebook-ruggedized-modern",
        name: "Notebook, Ruggedized, Modern",
        weight: 4,
        tags: ["computing", "notebook", "ruggedized", "portable", "modern"],
        barterValue: "GG1,000",
        streetPrice: 5000,
        powerRequirement: "charge/3 hrs",
        runtimeHours: 3,
        traits: ["computing-gen:modern", "wear-environment-reduced"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:pda-obsolete",
        name: "PDA, Obsolete",
        weight: 0.1,
        tags: ["computing", "pda", "portable", "obsolete"],
        barterValue: "GG20",
        streetPrice: 80,
        powerRequirement: "charge/8 hrs",
        runtimeHours: 8,
        traits: ["computing-gen:obsolete"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:smartphone-modern",
        name: "Smartphone, Modern",
        weight: 0.1,
        tags: ["computing", "smartphone", "portable", "modern"],
        barterValue: "GG100",
        streetPrice: 400,
        powerRequirement: "charge/6 hrs",
        runtimeHours: 6,
        traits: ["computing-gen:modern"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:smartphone-sota",
        name: "Smartphone, SOTA",
        weight: 0.1,
        tags: ["computing", "smartphone", "portable", "sota"],
        barterValue: "GG125",
        streetPrice: 500,
        powerRequirement: "charge/5 hrs",
        runtimeHours: 5,
        traits: ["computing-gen:sota"],
        source: [SRC_239],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:smartphone-gps-modern",
        name: "Smartphone, GPS, Modern",
        weight: 0.2,
        tags: ["computing", "smartphone", "portable", "gps", "modern"],
        barterValue: "GG125",
        streetPrice: 500,
        powerRequirement: "charge/5 hrs",
        runtimeHours: 5,
        traits: ["computing-gen:modern", "gps-civilian"],
        source: [SRC_239],
        description: "Smartphone with integrated civilian GPS receiver and preloaded navigation software.",
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:smartphone-gps-sota",
        name: "Smartphone, GPS, SOTA",
        weight: 0.2,
        tags: ["computing", "smartphone", "portable", "gps", "sota"],
        barterValue: "GG150",
        streetPrice: 600,
        powerRequirement: "charge/4 hrs",
        runtimeHours: 4,
        traits: ["computing-gen:sota", "gps-civilian"],
        source: [SRC_239],
        description: "SOTA smartphone with integrated civilian GPS receiver and preloaded navigation software.",
    }),
];
// ── Computer Peripherals ──────────────────────────────────────────────────────
exports.COMPUTER_PERIPHERALS = [
    (0, helpers_1.defineElectronicItem)({
        id: "computing:hard-drive-external",
        name: "Hard Drive, External",
        weight: 0.2,
        tags: ["computing", "peripheral", "storage"],
        barterValue: "GG10",
        streetPrice: 200,
        source: [SRC_240],
        description: "Paperback-sized portable hard drive; draws power from connected computer.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:hard-drive-pocket",
        name: "Hard Drive, Pocket",
        weight: 0,
        tags: ["computing", "peripheral", "storage"],
        barterValue: "GG5",
        streetPrice: 100,
        source: [SRC_240],
        description: "Thumb-sized flash memory drive for personal data transport.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:memory-card",
        name: "Memory Card",
        weight: 0,
        tags: ["computing", "peripheral", "storage"],
        barterValue: "GG2.5",
        streetPrice: 50,
        source: [SRC_240],
        description: "Unprotected flash memory chip for use in cameras and smartphones.",
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "computing:printer-portable",
        name: "Printer, Portable",
        weight: 3,
        tags: ["computing", "peripheral", "printer"],
        barterValue: "GG20",
        streetPrice: 400,
        powerRequirement: "charge/300 pg.",
        runtimeHours: 0,
        source: [SRC_240],
        description: "Portable color inkjet printer. One ink cartridge (0.1 kg, GG4, $80) prints ~300 pages or ~50 full-page images.",
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:router-wired",
        name: "Router, Wired",
        weight: 1,
        tags: ["computing", "peripheral", "network"],
        barterValue: "GG3",
        streetPrice: 60,
        kilowatts: 0.2,
        source: [SRC_240],
        description: "Connects four or more computers into a wired data-sharing network.",
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:router-wireless",
        name: "Router, Wireless",
        weight: 1,
        tags: ["computing", "peripheral", "network", "wireless"],
        barterValue: "GG5",
        streetPrice: 100,
        kilowatts: 0.3,
        source: [SRC_240],
        description: "Wireless network router; effective range approximately 30 meters. Only modern or higher hardware can connect wirelessly.",
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "computing:scanner-portable",
        name: "Scanner, Portable",
        weight: 2,
        tags: ["computing", "peripheral", "scanner"],
        barterValue: "GG4",
        streetPrice: 80,
        kilowatts: 0.2,
        source: [SRC_240],
        description: "Small flatbed scanner for documents up to A4/letter size.",
    }),
];
// ── Software ──────────────────────────────────────────────────────────────────
// Software has negligible weight (0.1 kg if installaton media present).
// Prices listed are for modern generation; ×0.1 archaic, ×0.25 obsolete, ×2 SOTA, ×4 cutting-edge.
exports.SOFTWARE_ITEMS = [
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-business",
        name: "Software, Business",
        weight: 0,
        tags: ["computing", "software"],
        barterValue: "GG100",
        streetPrice: 2000,
        source: [SRC_241],
        description: "Inventory tracking, payroll, and employee records suite. Valuable for organizing large-scale reconstruction.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-cryptography",
        name: "Software, Cryptography",
        weight: 0,
        tags: ["computing", "software", "security"],
        barterValue: "GG500",
        streetPrice: 5000,
        source: [SRC_241],
        description: "Full code analysis and breaking tools, including all encryption capabilities.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-cad",
        name: "Software, CAD (per specialty)",
        weight: 0,
        tags: ["computing", "software", "engineering"],
        barterValue: "GG250",
        streetPrice: 2000,
        source: [SRC_241],
        description: "Computer-Aided Design for architectural, mechanical, electrical, or electronic work. Purchased per specialty.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-diagnostic",
        name: "Software, Diagnostic (per device family)",
        weight: 0,
        tags: ["computing", "software", "repair"],
        barterValue: "GG80",
        streetPrice: 400,
        source: [SRC_241],
        description: "Access internal functions of computer-controlled machinery. Includes a wiring harness (0.1 kg). Purchased per device family.",
        traits: ["software-req:modern"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-encryption",
        name: "Software, Encryption",
        weight: 0,
        tags: ["computing", "software", "security"],
        barterValue: "GG100",
        streetPrice: 1000,
        source: [SRC_241],
        description: "Encrypts and decrypts data; modern+ also enables on-the-fly encryption of live radio transmissions.",
        traits: ["software-req:modern"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-graphic-design",
        name: "Software, Graphic Design",
        weight: 0,
        tags: ["computing", "software"],
        barterValue: "GG35",
        streetPrice: 700,
        source: [SRC_241],
        description: "Tools for generating or modifying still images.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-navigation",
        name: "Software, Navigation (per map set)",
        weight: 0,
        tags: ["computing", "software", "navigation"],
        barterValue: "GG6",
        streetPrice: 60,
        source: [SRC_241],
        description: "High-resolution pre-Collapse map data; can be connected to a GPS receiver for mapping navigation. Purchased by area and type.",
        traits: ["software-req:modern"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-publishing",
        name: "Software, Publishing",
        weight: 0,
        tags: ["computing", "software"],
        barterValue: "GG45",
        streetPrice: 900,
        source: [SRC_241],
        description: "Professional page layout and document management for print production or forgery.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-recording-audio",
        name: "Software, Recording, Audio",
        weight: 0,
        tags: ["computing", "software", "media"],
        barterValue: "GG25",
        streetPrice: 500,
        source: [SRC_241],
        description: "Converts raw audio data into finished media files.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-recording-video",
        name: "Software, Recording, Video",
        weight: 0,
        tags: ["computing", "software", "media"],
        barterValue: "GG75",
        streetPrice: 1500,
        source: [SRC_241],
        description: "Converts raw video data into finished media files.",
        traits: ["software-req:modern", "software-not-smartphone"],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "computing:software-reference",
        name: "Software, Reference (per topic)",
        weight: 0,
        tags: ["computing", "software", "reference"],
        barterValue: "GG10",
        streetPrice: 200,
        source: [SRC_241],
        description: "Portable encyclopedia for general knowledge or a specific field. Searching takes 15 minutes and an Education check; on success grants +2 to relevant EDU/COG-based checks.",
        traits: ["software-req:modern", "reference-edu-check-bonus-2"],
    }),
];
