"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ILLUMINATION_ITEMS = void 0;
const helpers_1 = require("./helpers");
exports.ILLUMINATION_ITEMS = [
    (0, helpers_1.defineElectronicItem)({
        id: "illumination:candle",
        name: "Candle",
        weight: 0.1,
        tags: ["illumination", "light-source", "flame"],
        barterValue: "GG0.01",
        streetPrice: 1,
        duration: "8 hours",
        description: "Typical candle with about an 8-hour burn time.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "illumination:chem-light-standard",
        name: "Chemlight, Standard",
        weight: 0,
        tags: ["illumination", "light-source", "chemlight"],
        barterValue: "GG0.3",
        streetPrice: 1.25,
        duration: "Several hours",
        description: "Cold-light chemical stick. Produces steady light for several hours before fading.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "illumination:chem-light-high-intensity",
        name: "Chemlight, High-Intensity",
        weight: 0,
        tags: ["illumination", "light-source", "chemlight"],
        barterValue: "GG0.6",
        streetPrice: 2.5,
        duration: "Short duration",
        description: "High-intensity chemlight with brighter but shorter duration output.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "illumination:chem-light-ir",
        name: "Chemlight, IR",
        weight: 0,
        tags: ["illumination", "light-source", "chemlight", "infrared"],
        barterValue: "GG2.4",
        streetPrice: 5,
        duration: "Several hours",
        description: "Infrared chemlight visible only to night-vision optics.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:flashlight-micro",
        name: "Flashlight, Micro",
        weight: 0,
        tags: ["illumination", "light-source", "flashlight"],
        barterValue: "GG2",
        streetPrice: 20,
        powerRequirement: "1 micro/40 hrs",
        batteryCount: 1,
        batterySize: "micro",
        runtimeHours: 40,
        description: "Keychain-sized battery flashlight for maps, locks, and close work.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:flashlight-hand",
        name: "Flashlight, Hand",
        weight: 0.1,
        tags: ["illumination", "light-source", "flashlight"],
        barterValue: "GG3",
        streetPrice: 30,
        powerRequirement: "2 sm/8 hrs",
        batteryCount: 2,
        batterySize: "sm",
        runtimeHours: 8,
        description: "Pocket flashlight that provides useful illumination at Personal and Gunfighting range.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:flashlight-tactical",
        name: "Flashlight, Tactical",
        weight: 0.1,
        tags: ["illumination", "light-source", "flashlight", "tactical"],
        barterValue: "GG12",
        streetPrice: 120,
        powerRequirement: "2 sm/30 min",
        batteryCount: 2,
        batterySize: "sm",
        runtimeHours: 0.5,
        description: "Compact high-output tactical flashlight with duty-light intensity.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:flashlight-duty",
        name: "Flashlight, Duty",
        weight: 1,
        tags: ["illumination", "light-source", "flashlight", "duty"],
        barterValue: "GG8",
        streetPrice: 80,
        powerRequirement: "3 med/6 hrs",
        batteryCount: 3,
        batterySize: "med",
        runtimeHours: 6,
        description: "Large flashlight that provides adequate illumination through CQB range.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:headlamp",
        name: "Headlamp",
        weight: 0.1,
        tags: ["illumination", "light-source", "headlamp", "hands-free"],
        barterValue: "GG8",
        streetPrice: 40,
        powerRequirement: "2 sm/4 hrs",
        batteryCount: 2,
        batterySize: "sm",
        runtimeHours: 4,
        description: "Hands-free LED headlamp on a flexible head strap.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:lamp-battery",
        name: "Lamp, Battery",
        weight: 1,
        tags: ["illumination", "light-source", "lamp"],
        barterValue: "GG3",
        streetPrice: 25,
        powerRequirement: "4 med/20 hrs",
        batteryCount: 4,
        batterySize: "med",
        runtimeHours: 20,
        description: "Portable omnidirectional battery lamp.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "illumination:lamp-oil",
        name: "Lamp, Oil",
        weight: 1,
        tags: ["illumination", "light-source", "lamp", "oil"],
        barterValue: "GG2",
        streetPrice: 40,
        duration: "30 hours",
        powerRequirement: "0.1 L/30 hr",
        description: "Portable oil-burning lamp with an internal fuel reservoir.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "illumination:searchlight-semi-portable",
        name: "Searchlight, Semi-Portable",
        weight: 1.4,
        tags: ["illumination", "light-source", "searchlight"],
        barterValue: "GG8.75",
        streetPrice: 75,
        powerRequirement: "1 lg/1 hr",
        batteryCount: 1,
        batterySize: "lg",
        runtimeHours: 1,
        description: "Painfully bright handheld searchlight that can also run from a car accessory socket.",
    }),
];
