"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PHOTOGRAPHY_ITEMS = void 0;
const helpers_1 = require("./helpers");
const SRC_238 = "Source: Twilight 2013 Core OEF PDF p.238";
exports.PHOTOGRAPHY_ITEMS = [
    // Stills
    (0, helpers_1.defineElectronicItem)({
        id: "photography:camera-35mm-consumer",
        name: "Camera, 35mm, Consumer",
        weight: 0.3,
        tags: ["photography", "camera", "35mm", "consumer"],
        barterValue: "GG5",
        streetPrice: 100,
        source: [SRC_238],
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "photography:camera-35mm-professional",
        name: "Camera, 35mm, Professional",
        weight: 0.5,
        tags: ["photography", "camera", "35mm", "professional"],
        barterValue: "GG25",
        streetPrice: 500,
        source: [SRC_238],
        description: "Professional 35mm SLR camera accepting a lens set.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "photography:camera-digital-consumer",
        name: "Camera, Digital, Consumer",
        weight: 0.1,
        tags: ["photography", "camera", "digital", "consumer"],
        barterValue: "GG25",
        streetPrice: 200,
        powerRequirement: "2 sm/500 ex.",
        batteryCount: 2,
        batterySize: "sm",
        runtimeHours: 0,
        source: [SRC_238],
        description: "Consumer digital still camera. One charge of 2 small batteries is good for approximately 500 exposures.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "photography:camera-digital-professional",
        name: "Camera, Digital, Professional",
        weight: 0.8,
        tags: ["photography", "camera", "digital", "professional"],
        barterValue: "GG175",
        streetPrice: 1400,
        powerRequirement: "4 sm/500 ex.",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 0,
        source: [SRC_238],
        description: "Professional digital camera accepting a lens set. One charge of 4 small batteries is good for approximately 500 exposures.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "photography:lens-set",
        name: "Lens Set",
        weight: 3,
        tags: ["photography", "lens", "accessory"],
        barterValue: "GG625",
        streetPrice: 5000,
        source: [SRC_238],
        description: "Padded attaché case containing zoom, wide-angle, and high-power lenses with a battery-powered flash. Attaches to any professional-grade film or digital camera.",
    }),
    // Video
    (0, helpers_1.defineRechargeableDevice)({
        id: "photography:camcorder",
        name: "Camcorder",
        weight: 0.6,
        tags: ["photography", "video", "camcorder", "consumer"],
        barterValue: "GG100",
        streetPrice: 800,
        powerRequirement: "charge/5 hrs",
        runtimeHours: 5,
        source: [SRC_238],
        description: "Consumer camcorder recording up to 50 hours of video to an internal hard drive.",
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "photography:video-camera-professional",
        name: "Video Camera, Professional",
        weight: 6,
        tags: ["photography", "video", "camera", "professional"],
        barterValue: "GG3,000",
        streetPrice: 27000,
        powerRequirement: "charge/6 hrs",
        runtimeHours: 6,
        source: [SRC_238],
        description: "Shoulder-carried professional video camera recording up to 4 hours of HD video per data cassette.",
    }),
];
