"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.POWERED_TOOLS = void 0;
const helpers_1 = require("./helpers");
exports.POWERED_TOOLS = [
    (0, helpers_1.defineElectronicItem)({
        id: "tool:air-compressor",
        name: "Air Compressor",
        weight: 39,
        tags: ["tool", "powered-tool", "compressor"],
        barterValue: "GG800",
        streetPrice: 3200,
        powered: true,
        powerRequirement: "see text",
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:aircraft-tools",
        name: "Aircraft Tools",
        weight: 75,
        tags: ["tool", "powered-tool", "aircraft-tools"],
        barterValue: "GG625",
        streetPrice: 2500,
        powerRequirement: "0.3 kW",
        kilowatts: 0.3,
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:aircraft-tools-model-specific",
        name: "Aircraft Tools, Model-Specific",
        weight: 20,
        tags: ["tool", "powered-tool", "aircraft-tools"],
        barterValue: "GG200",
        streetPrice: 20000,
        powerRequirement: "0.5 kW",
        kilowatts: 0.5,
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:basic-power-tools",
        name: "Basic Power Tools",
        weight: 15,
        tags: ["tool", "powered-tool", "workshop"],
        barterValue: "GG150",
        streetPrice: 1200,
        powerRequirement: "0.5 kW",
        kilowatts: 0.5,
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:cement-mixer-portable",
        name: "Cement Mixer, Portable",
        weight: 70,
        tags: ["tool", "powered-tool", "construction"],
        barterValue: "GG85",
        streetPrice: 680,
        powerRequirement: "0.6 kW",
        kilowatts: 0.6,
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:chainsaw-electric",
        name: "Chainsaw, Electric",
        weight: 3.3,
        tags: ["tool", "powered-tool", "chainsaw"],
        barterValue: "GG25",
        streetPrice: 100,
        powerRequirement: "2.2 kW",
        kilowatts: 2.2,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "tool:chainsaw-gasoline",
        name: "Chainsaw, Gasoline",
        weight: 4.5,
        tags: ["tool", "powered-tool", "chainsaw", "gasoline"],
        barterValue: "GG50",
        streetPrice: 200,
        powered: true,
        powerRequirement: "see text",
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:machine-shop-portable",
        name: "Machine Shop, Portable",
        weight: 2.5,
        tags: ["tool", "powered-tool", "machine-shop"],
        barterValue: "GG625",
        streetPrice: 5000,
        powerRequirement: "1 kW",
        kilowatts: 1,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "tool:rescue-saw",
        name: "Rescue Saw",
        weight: 11,
        tags: ["tool", "powered-tool", "rescue-saw"],
        barterValue: "GG350",
        streetPrice: 1400,
        powered: true,
        powerRequirement: "see text",
    }),
    (0, helpers_1.defineAcPoweredDevice)({
        id: "tool:vehicle-tools-model-specific",
        name: "Vehicle Tools, Model-Specific",
        weight: 10,
        tags: ["tool", "powered-tool", "vehicle-tools"],
        barterValue: "GG100",
        streetPrice: 10000,
        powerRequirement: "0.2 kW",
        kilowatts: 0.2,
    }),
];
