"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SENSOR_ITEMS = void 0;
const helpers_1 = require("./helpers");
const SRC_238 = "Source: Twilight 2013 Core OEF PDF p.238";
exports.SENSOR_ITEMS = [
    (0, helpers_1.defineElectronicItem)({
        id: "sensor:dosimeter",
        name: "Dosimeter, Box of 200",
        weight: 2,
        tags: ["sensor", "radiation", "dosimeter", "consumable"],
        barterValue: "GG300",
        streetPrice: 300,
        source: [SRC_238],
        description: "Box of 200 radiation-sensitive film badges. Each badge darkens as cumulative dose increases; not precise but warns when safe industrial exposure is exceeded. 5-year shelf life.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "sensor:gas-detector",
        name: "Gas Detector",
        weight: 0.5,
        tags: ["sensor", "cbrn", "gas", "chemical"],
        barterValue: "GG5,000",
        streetPrice: 5000,
        powerRequirement: "4 sm/12 hrs",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 12,
        source: [SRC_238],
        description: "Detects several hundred hazardous industrial and chemical warfare substances. Cannot detect at stand-off distance.",
        traits: ["no-standoff-detection"],
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "sensor:geiger-counter",
        name: "Geiger Counter",
        weight: 0.1,
        tags: ["sensor", "radiation", "geiger"],
        barterValue: "GG400",
        streetPrice: 400,
        powerRequirement: "4 sm/7 days",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 168,
        source: [SRC_238],
        description: "Audible and visual radiation alert device. Can record up to 36 hours of data; computer-connectable.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "sensor:hazmat-paper",
        name: "HAZMAT Paper, 12 Sheets",
        weight: 0,
        tags: ["sensor", "cbrn", "chemical", "consumable"],
        barterValue: "GG50",
        streetPrice: 25,
        source: [SRC_238],
        description: "Reactive paper with labeled squares that change color when exposed to nerve agents, mustard gas, chlorine, arsenic, hydrogen sulfide, or cyanide.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "sensor:weather-monitor",
        name: "Weather Monitor",
        weight: 0.2,
        tags: ["sensor", "weather", "navigation"],
        barterValue: "GG40",
        streetPrice: 160,
        powerRequirement: "1 med/7 days",
        batteryCount: 1,
        batterySize: "med",
        runtimeHours: 168,
        source: [SRC_238],
        description: "Handheld station with thermometer, anemometer, barometer, and humidity meter.",
    }),
];
