"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.THERMAL_IMAGING_ITEMS = exports.NIGHT_VISION_ITEMS = exports.MAGNIFICATION_ITEMS = void 0;
const helpers_1 = require("./helpers");
//We have a series of unpowered optics in the electronics catalog.
//We should separate those into a "vision" catalog, and then have the powered ones in the electronics catalog reference them as appropriate. This will make it easier to maintain the relationships between powered and unpowered versions of the same item, and also make it easier to find all vision-related items in one place.
//We should also tag them with the Vision tag.
//we should have special rules or special exceptions placed into their own section of the catalog, and then have the individual items reference those rules as needed. 
//Such as traits or mechanics. For example, Night vision reduces vision width, and thermal imaging treats all lighting conditions as adequate light. These should be traits that can be referenced by the items, rather than having the rules written into the item descriptions.
//In the future this will allow us to search for keys to apply these traits to the rolls automatically
// and also make it easier to maintain the rules in one place rather than having them scattered across item descriptions.
exports.MAGNIFICATION_ITEMS = [
    (0, helpers_1.defineElectronicItem)({
        id: "vision:binoculars-standard-mag-2",
        name: "Binoculars, Standard",
        weight: 1,
        tags: ["vision-enhancement", "magnification", "binoculars"],
        traits: ["Mag-2"],
        barterValue: "GG8",
        streetPrice: 80,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:binoculars-standard-mag-3",
        name: "Binoculars, Standard",
        weight: 1.2,
        tags: ["vision-enhancement", "magnification", "binoculars"],
        traits: ["Mag-3"],
        barterValue: "GG20",
        streetPrice: 200,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:binoculars-standard-mag-4",
        name: "Binoculars, Standard",
        weight: 1.4,
        tags: ["vision-enhancement", "magnification", "binoculars"],
        traits: ["Mag-4"],
        barterValue: "GG40",
        streetPrice: 400,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:binoculars-compact-mag-1",
        name: "Binoculars, Compact",
        weight: 0.2,
        tags: ["vision-enhancement", "magnification", "binoculars", "compact"],
        traits: ["Mag-1"],
        barterValue: "GG6",
        streetPrice: 60,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:binoculars-compact-mag-2",
        name: "Binoculars, Compact",
        weight: 0.3,
        tags: ["vision-enhancement", "magnification", "binoculars", "compact"],
        traits: ["Mag-2"],
        barterValue: "GG16",
        streetPrice: 160,
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:laser-designator",
        name: "Laser Designator",
        weight: 16,
        tags: ["vision-enhancement", "magnification", "laser-designator", "targeting"],
        barterValue: "GG7,500",
        streetPrice: 30000,
        powerRequirement: "1 lg spec/5 hrs",
        batteryCount: 1,
        batterySize: "lg spec",
        runtimeHours: 5,
        traits: ["Mag-3"],
        description: "Multi-function targeting device for guiding laser-homing munitions, combining a Mag-3 spotting scope with additional ranging, laser, and GPS functions.",
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:spotting-scope-mag-5",
        name: "Spotting Scope",
        weight: 5,
        tags: ["vision-enhancement", "magnification", "spotting-scope"],
        traits: ["Mag-5"],
        barterValue: "GG100",
        streetPrice: 1000,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:telescope-astronomical-mag-5",
        name: "Telescope, Astronomical",
        weight: 9,
        tags: ["vision-enhancement", "magnification", "telescope"],
        traits: ["Mag-5"],
        barterValue: "GG15",
        streetPrice: 750,
    }),
    (0, helpers_1.defineElectronicItem)({
        id: "vision:telescope-nautical-mag-2",
        name: "Telescope, Nautical",
        weight: 1,
        tags: ["vision-enhancement", "magnification", "telescope"],
        traits: ["Mag-2"],
        barterValue: "GG3.25",
        streetPrice: 65,
    }),
];
exports.NIGHT_VISION_ITEMS = [
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:night-vision-binocs-mag-1",
        name: "Night Vision Binocs",
        weight: 1.2,
        tags: ["vision-enhancement", "night-vision", "binoculars"],
        traits: ["Mag-1"],
        barterValue: "GG200",
        streetPrice: 800,
        powerRequirement: "4 sm/40 hrs",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 40,
        description: "Night-vision binoculars with low magnification.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:night-vision-binocs-mag-2",
        name: "Night Vision Binocs",
        weight: 1.4,
        tags: ["vision-enhancement", "night-vision", "binoculars"],
        traits: ["Mag-2"],
        barterValue: "GG300",
        streetPrice: 1200,
        powerRequirement: "4 sm/40 hrs",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 40,
        description: "Night-vision binoculars with moderate magnification.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:night-vision-viewer",
        name: "Night Vision Viewer",
        weight: 1.5,
        tags: ["vision-enhancement", "night-vision", "viewer"],
        barterValue: "GG100",
        streetPrice: 400,
        powerRequirement: "4 sm/40 hrs",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 40,
        description: "Non-magnifying handheld IR image viewer.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:nvgs-binocular",
        name: "NVGs, Binocular",
        weight: 0.7,
        tags: ["vision-enhancement", "night-vision", "nvgs", "binocular"],
        barterValue: "GG450",
        streetPrice: 4500,
        powerRequirement: "4 sm/40 hrs",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 40,
        description: "Helmet-mounted binocular night-vision goggles.",
        traits: ["night-vision-binocular-fov-limited", "night-vision-full-optics-no-reflex"],
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:nvgs-monocular",
        name: "NVGs, Monocular",
        weight: 0.4,
        tags: ["vision-enhancement", "night-vision", "nvgs", "monocular"],
        barterValue: "GG360",
        streetPrice: 3600,
        powerRequirement: "2 sm/40 hrs",
        batteryCount: 2,
        batterySize: "sm",
        runtimeHours: 40,
        description: "Monocular helmet-mounted NVGs with a narrower field penalty than binocular units.",
    }),
    (0, helpers_1.defineBatteryDevice)({
        id: "vision:nvgs-panoramic",
        name: "NVGs, Panoramic",
        weight: 0.8,
        tags: ["vision-enhancement", "night-vision", "nvgs", "panoramic"],
        barterValue: "GG900",
        streetPrice: 12000,
        powerRequirement: "4 sm/40 hrs",
        batteryCount: 4,
        batterySize: "sm",
        runtimeHours: 40,
        description: "Rare panoramic night-vision goggles with a wider field of vision.",
    }),
];
exports.THERMAL_IMAGING_ITEMS = [
    (0, helpers_1.defineRechargeableDevice)({
        id: "vision:thermal-imager",
        name: "Thermal Imager",
        weight: 2,
        tags: ["vision-enhancement", "thermal-imaging", "thermal-imager"],
        barterValue: "GG560",
        streetPrice: 2800,
        powerRequirement: "charge/6 hrs",
        runtimeHours: 6,
        description: "Portable thermal imager usable for observation and search.",
        traits: ["thermal-human-detection-sniping", "thermal-adequate-light"],
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "vision:thermal-imager-mag-1",
        name: "Thermal Imager",
        weight: 2.1,
        tags: ["vision-enhancement", "thermal-imaging", "thermal-imager"],
        traits: ["Mag-1"],
        barterValue: "GG850",
        streetPrice: 3400,
        powerRequirement: "charge/6 hrs",
        runtimeHours: 6,
        description: "Thermal imager with low electronic magnification.",
    }),
    (0, helpers_1.defineRechargeableDevice)({
        id: "vision:thermal-imager-mag-2",
        name: "Thermal Imager",
        weight: 2.1,
        tags: ["vision-enhancement", "thermal-imaging", "thermal-imager"],
        traits: ["Mag-2"],
        barterValue: "GG1,100",
        streetPrice: 4400,
        powerRequirement: "charge/6 hrs",
        runtimeHours: 6,
        description: "Thermal imager with moderate electronic magnification.",
    }),
];
